### ISSUE TITLE
Allow seed specified on command line to override seed specified in scenario YAML file

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1006]
For example,

I can play the word search with the default seed (`2`) as so:

    stack run -- --scenario data/scenarios/Challenges/word-search.yaml

However, if I want to play  with a different board arrangement, I would have to edit the YAML file.  I would like to instead run:

    stack run swarm -- --scenario data/scenarios/Challenges/word-search.yaml --seed 3

Currently this CLI-specified value is not respected.

**Comment by byorgey** [comment]
If the CLI-specified value is not respected that is definitely a bug!

**Comment by kostmo** [comment]
Nevermind, it works!
