### ISSUE TITLE
Release 0.3

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#1012]
We should make a new release, the first one of 2023! :partying_face: :clinking_glasses: 

## Wishlist

Here we can list PRs we would like to merge and Issues we would like fix before release:
- #986 ( @xsebek ) 
  - requires #991 
- #927 ( @kostmo )
  - #1054 (@xsebek we should fix this bug if possible)
- #863 ( @kostmo )
- #944 ( @kostmo )
- #1001 ( @byorgey )

## Release tasks :rocket: 

I forgot what is needed, I guess just:

- [x] update CHANGELOG #1061 
- [x] tag a release <kbd>0.3.0.0</kbd>

## After the release :newspaper: 

We should share the new features, e.g. on

- r/haskell (the simple OnHover could be interesting for wider Haskell community if that is fine with @kostmo :slightly_smiling_face:)

**Comment by kostmo** [comment]
@xsebek, ping for [help with the boolean parser](https://github.com/swarm-game/swarm/pull/927#discussion_r1064273464)

**Comment by xsebek** [comment]
Ping @kostmo and @byorgey 🔔 

Anything else that you would like to do before release? I am almost done with OnHover. 🙂

**Comment by byorgey** [comment]
I was hoping to fix #681.  I've been working on it but haven't quite gotten it right yet.  Give me another day or two, and I'll see if I can get it figured out.

**Comment by xsebek** [comment]
@byorgey that would be awesome 👍

Once we have everything merged we should write some release notes in changelog. 🤔 

I will probably make a new VSCode plugin release afterwards too. 🙂

**Comment by byorgey** [comment]
Actually, never mind, I had an epiphany in the shower which has now turned into a Super-Secret Master Plan for solving #681 *and* a bunch of other problems *and* removing a bunch of code all at once.  We'll see how it goes, but in any case it won't be ready for 0.3. :sweat_smile:

**Comment by xsebek** [comment]
@byorgey @kostmo It is done! :rocket: 

---

@byorgey if you want to make some small fixes, we can release `0.3.0.1` pretty easily. 

Now that this is over, we can get to work on `0.4`! :smile:

**Comment by kostmo** [comment]
Hmm... I wonder if the reddit post got removed?  I don't see it among the [top posts from this week](https://www.reddit.com/r/haskell/top/?t=week).  Perhaps on account of [new rules](https://www.reddit.com/r/haskell/comments/10ilrpj/rules_update/)?

Perhaps it would be good to also post in [haskellgamedev](https://www.reddit.com/r/haskellgamedev/) and [madeinhaskell](https://www.reddit.com/r/madeinhaskell/).

**Comment by xsebek** [comment]
@kostmo I see it there just fine, it simply does not have that many votes. 🙂

**Comment by kostmo** [comment]
On second look, it seems the post is only missing when I use a particular app (RIF) to view Reddit.  I do see the post when using the official Reddit app or the web browser.  Regarding the votes, I'd say it's doing relatively well. ⬆️
