### ISSUE TITLE
Goal is not checked between "drill" and "move"

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1013]
For efficiency of the solution checker in word search challenge (#999), we short circuit the goal condition check to `false` if the `base` is not standing on a "marked" (highlighted) cell.

The rationale is that the goal could only have been reached if the player has marked the three cells of the word.  If they have done that, then they would still be standing on the the third cell at the time the goal condition is evaluated.  With this prerequisite met, the rest of the verification logic runs---it checks that the three letters of the word are marked consecutively and colinearly.  Then the game is won.

However, as both I and @byorgey [encountered](https://github.com/swarm-game/swarm/pull/1004#pullrequestreview-1249199825) in our solutions to the challenge, if the player codes a loop like so:
```
doN 3 (
    drill down;
    // <--- the goal SHOULD be evaluated here
    move;
```
the win is never announced.  It seems as if the `move` happens before the goal condition is evaluated.  If I instead code my solution as follows:
```
drill down;
move;
drill down;
move;
drill down;
```
Then the solution verifier works properly.

**Comment by byorgey** [comment]
Hmm, weird. In theory `drill` and `move` are both tangible commands, at most one should be able to happen per tick regardless.

**Comment by xsebek** [comment]
@kostmo this is almost certainly a bigger issue than `drill`, there is nothing special about it for condition checking.

https://github.com/swarm-game/swarm/blob/b8bc2869ba15fe7842aa520ffab05616d1fdbdd5/src/Swarm/Language/Syntax.hs#L592-L593

I would suggest adding a line logging the condition on each check to the message queue. I was able to solve the `VResult` problem with it, but you could log anything, including for example the base position. :thinking:

**Comment by kostmo** [comment]
Cannot reproduce this today.  Going to close the issue for now, but will re-open if I see it again.
