### ISSUE TITLE
Input handler command

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#102]
I don't know yet exactly how it should work, but I think it's a really fun idea.  There should be a command something like
```
handleInput : (key -> maybe (cmd ())) -> cmd ()
```
where `key` is some sort of type to represent keypress events, the idea being that you specify how to handle each possible key press (with `nothing` indicating that the function should quit).  If you run `handleInput` at the REPL, it is now listening directly to any keypresses you make while the REPL is focused.  There are lots of fun uses you could imagine for this.

* You could create a set of "hotkeys" where you can press a single key to do various common actions.
* If you are eventually able to install some `treads` on your base, then you could drive your base around manually using arrow keys!
* Or you could remotely pilot another robot by broadcasting instructions to it!  Or you could remotely pilot a whole swarm of robots!

I don't know what happens if a robot other than the base tries to execute this command.  I guess it just sits there waiting for input forever, since you are not sitting there to push any keys.

**Comment by byorgey** [comment]
I guess this would require:

1. Adding a built-in primitive `key` type with lots of built-in constants to represent possible keypresses.  I guess this should be auto-generated somehow from the list of X11 keysyms or something like that.
2. Writing code to interpret `handleInput` by putting the REPL into a special state that just listens for keypresses and sends them directly to the provided callback.  This would be the easy part, I think.
3. We would also have to think carefully about what facilities we would provide for writing a function of type `key -> ...`.  Right now we have sum types and the `case` function.  But writing a handler for lots of different keypresses by nesting `case`s would be horrendous.  I guess there would need to be some kind of pattern-matching or at the very least a kind of built-in `switch` expression.

**Comment by byorgey** [comment]
Maybe we don't need special syntax for `switch`, pattern-matching, etc. after all --- users could just make their own function like  `lookup : list (a * b) -> (a -> maybe b)` and then use that to write a list of key/cmd pairs.

**Comment by xsebek** [comment]
I like that, we could just put a flag to game state that we would check in input handler. 

I think we should still handle a few global inputs, like Ctrl-Q, Ctrl-C or time control otherwise we could freeze the base. Luckily that’s easy to do, we’ll just put the flag check on the right line in input handler.

**Comment by byorgey** [comment]
So let me try to summarize the current design in one place:

* Create a new type `key` to represent keypresses
* Add a primitive function `key : text -> key` which can handle usual letters, numbers, etc. as well as special keys `"Down"` etc, and maybe even handles prefixes like `"Ctrl-p"` etc.
* Add a command `installKeyHandler : text -> (key -> cmd ()) -> cmd ()` which sets the "current key handler" (the `text` value is what to display in the shortcut hints line when the handler is running)
    - This command should be provided by some suitably advanced device
* Add a global keyboard shortcut for toggling key handler mode
* When in key handler mode, a few keyboard shortcuts (*e.g.* Ctrl-Q, Ctrl-C, the shortcut for toggling key handler mode itself) are still handled normally; all other keypresses are sent to the installed handler.

**Comment by kostmo** [comment]
I guess I'm a bit biased towards keeping "pilot mode" until we can see how ergonomic the input handler is for debugging.  Is the existing pilot mode code getting in the way?  I recall it didn't involve a huge amount of code to implement in #819.

Would the new input handler be independent of the REPL?  If not a third enum [could be added](https://github.com/swarm-game/swarm/blob/9e0e6fa666b7d602c64dc8da3ff5d433ca48fd5b/src/Swarm/TUI/Model/Repl.hs#L222-L224).

**Comment by byorgey** [comment]
It's not so much getting in the way as it just seemed like it would be easier to replace the existing pilot mode than to add a separate, parallel code path.  But sure, we can keep the pilot mode for now.

And yes, adding a third option to that enum is exactly what I've done.
