### ISSUE TITLE
Values referenced after a recursive call get overwritten

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1032]
**Describe the bug**

The following program produces unexpected output in the log:
```
      def go = \n.
          if (n > 0) {
              idx <- random 4;
              log $ "In: " ++ format idx;

              go $ n - 1;

              log $ "Out: " ++ format idx;
              move;
          } {};
          end;

      go 4;
```
Output in log:
```
In: 1
In: 3
In: 0
In: 2
Out: 0
Out: 0
Out: 0
Out: 0
```

**Comment by xsebek** [comment]
@byorgey this looks to me like a case of #681, am I right? :thinking:

**Comment by byorgey** [comment]
Yep, almost certainly #681, although to be honest I don't quite understand why we don't see the final `2` being repeated, like this:
```
In: 1
In: 3
In: 0
In: 2
Out: 2
Out: 2
Out: 2
Out: 2
```
Most likely duplicate, but I'll leave this open for now so when we fix #681 we can make sure it fixes this too.

**Comment by xsebek** [comment]
@kostmo better workaround: use a let binding
```
def go = \n.
    if (n > 0) {
        idx <- random 4;
        let indx = idx in
        log $ "In: " ++ format indx;

        go $ n - 1;

        log $ "Out: " ++ format indx;
        move;
    } {};
end;

go 4;
```

---

@byorgey when I tried the example code by @kostmo right now, it did repeat the last value.

Maybe we have a different version or @kostmo made a typo. :slightly_smiling_face:

**Comment by byorgey** [comment]
After looking at #1033 , I am now 100% certain this is caused by #681.  It turns out that #1021 is also causing issues here which is why I was confused.
