### ISSUE TITLE
Defining custom attributes in Scenario files

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1034]
I should be able to define custom colors within my scenario, which can then be referenced by way of the `display: attr:` property of my custom entities.

**Comment by xsebek** [comment]
Looks like we can change the `AttrMap` based on `AppState`:
```Haskell
        , appAttrMap :: s -> AttrMap
        -- ^ The attribute map that should be used during rendering.
```
https://hackage.haskell.org/package/brick-1.6/docs/Brick-Main.html#t:App


So we could load custom attributes and add them to our `AttrMap` in runtime. :slightly_smiling_face:
