### ISSUE TITLE
device to provide `teleport` capability

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#1041]
Some kind of space-time machine?  See some discussion at https://github.com/swarm-game/swarm/pull/406 .

**Comment by xsebek** [comment]
We could make a reference to Hitchhikers guide and have:

- [infinite improbability device](https://hitchhikers.fandom.com/wiki/Infinite_Improbability_Drive)
  - a few bitcoins (a reference to [Heart of Gold](https://hitchhikers.fandom.com/wiki/Heart_of_Gold))
  - tea (made in a furnace from plant and water)
  - at least 3 PhD
  - atomic vector writer (rubber band, type-writer, compass and counter)

The last ingredient could be completely useless on its own and its description could just poke fun at how it's just a combination of words that make no sense together.

It could be fun to add some randomness for non-system robot teleportation. Both in space and time - but I am not sure how we could remove the teleported robot from the map for some time until it reappears. :thinking:

We could goof around with some more improbable effects in the area, like randomly changing a few entities. :smile:
