### ISSUE TITLE
Scenarios with condition but no goal description should not pop up a tiny empty box

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#1049]
I noticed a small issue where scenarios with a `condition` but no goal description etc. (e.g. the `Speedrun` scenarios) pop up a tiny, empty box at the beginning.  (Also, I should add goal descriptions to those Speedrun scenarios.)

_Originally posted by @byorgey in https://github.com/swarm-game/swarm/pull/927#pullrequestreview-1268670090_

**Comment by kostmo** [comment]
#937 would help to enforce having goal descriptions.

**Comment by byorgey** [comment]
Oh, right, I had forgotten about that.  Yeah, let's definitely do #937 .  I'm going to close this (and add some goal descriptions to the speedrun scenarios).
