### ISSUE TITLE
Nicer type variable names in inferred types

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#1050]
Currently we get things like 
```
atWS : forall a258 a259 a260. cmd a260 -> cmd a259 -> cmd a258 -> cmd a258
```
:vomiting_face: 

After type inference finishes, we should try renaming the type variables that end up in the types.  Level 1 would be to just pick names `a`, `b`, `c` in order.  Level 2 would be to also try to remember type variable names that were given by users in type annotations, and use those when possible.

**Comment by xsebek** [comment]
I wonder how GHC does it, it looks like it might be this module:
https://hackage.haskell.org/package/ghc-9.4.4/docs/src/GHC.Types.Name.Occurrence.html#TidyOccEnv

The notes in section “Tidying them up” deal with renaming, though I am not sure its the one making type variables pretty. 🤔

**Comment by byorgey** [comment]
Yes, that file mostly has to do with figuring out nice small numbers it can use on type variables so they are unique but don't have things like `a260`. Note another thing GHC does is that it goes to some lengths to keep the original name of any variables that came from a user-specified type.  We currently don't do this at all.  For example, if you define
```
def f : b -> c -> b = \x. \y. x end
```
and then ask for the type of `f`, you get not `b -> c -> b`, but instead `forall a0 a1. a0 -> a1 -> a0`. yuk.
