### ISSUE TITLE
No longer possible to scroll long goals

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#1054]
**Describe the bug**
When the goal dialog is open and the goal description text is too large for the dialog (either because there is a lot of text or the window is too small), a scrollbar will show on the right edge, but it is not possible to scroll it to read the rest of the description.

**To Reproduce**
The `conditionals` tutorial is a good one to exhibit this bug since it has a very long description.  Open the `conditionals` tutorial and then decrease the window size until the goal does not fit.

**Screenshots**
![unscrollable-goal](https://user-images.githubusercontent.com/533859/214703200-15c10c85-5c32-43ff-92de-50d8fd32a379.png)

**Additional context**
This was caused by the below code, which was added as part of #927 .  All modals used to fall through to the call to `handleInfoPanelEvent`, which is poorly named since really all it is doing is handling keys like arrows/PgUp/PgDown etc. in a scrollable panel.  However, now arrow keys are used to select a highlighted item in the list of objectives.

https://github.com/swarm-game/swarm/blob/bf8a9a66c5f69d3a61f3d4dc01029fdcc4282aaf/src/Swarm/TUI/Controller.hs#L408-L416

I am not sure of the best way to fix this.  At the very least, when there is no list of objectives to show, arrow keys etc. should work to scroll the goal.  But that's not a solution, since sometimes we might need to scroll around in the list of objectives **and** scroll the goal description text...

**Comment by byorgey** [comment]
@kostmo any ideas?

**Comment by xsebek** [comment]
Should we not know what is the `Name` of the selected Brick element?

I.e. if I click on the goal list (or tab to it) the list action should be on the goal list, otherwise on the goal description.

I would almost hope this happens automatically, but maybe we are missing setting the name somewhere or the name is not used in the logic here. :thinking:

**Comment by byorgey** [comment]
There is no such thing as a "selected Brick element" here.  But yes, maybe creating a little two-element "focus ring" within the goals dialog (like we currently do for the four panels) is the right way to do it, so we can scroll whichever thing currently has focus.
