### ISSUE TITLE
Tutorial 9: "Build", flower ID bug, flower place bug

### ISSUE THREAD

**Issue by AishmanTaylor** [swarm-game/swarm#1062]
Level nine needs you to harvest and place a flower by the waterside. The 'flower' is ID'd as 'pickerelweed' while the game has been calling it a flower up until this point. Had to ask Dr. Yorgey via Teams what the ID of this flower was so it could be placed to complete the level. When trying to place the flower, it just says to place it by the water. The water is a 3 space wide feature of the level, there is no indication of where to place it near the water. Instead of all of the squares being valid spaces like the tutorial suggests just one is, the one directly bellow where you harvested the flower. This is not communicated by the tutorial.

**Comment by xsebek** [comment]
Hi @AishmanTaylor, thanks for reporting this issue.

The "pickerelweed" name problem has been fixed recently in #1056 which will be part of the 0.3.0.0 release soon.

**Comment by byorgey** [comment]
It should be acceptable to place the flower in any of the three cells next to the water.  I tried it just now to be sure and I was able to successfully complete the level by placing the flower in any one of the three cells.  Do you have an example where it did not work for you?

**Comment by AishmanTaylor** [comment]
@byorgey the space right below the lander does not count for completing the level.
