### ISSUE TITLE
Remove per-module copyright and maintainer fields

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1120]
The copyright/maintainer header adds clutter, is cumbersome to maintain, and imputes questionable ownership by single individuals as more contributors edit a given file.

And putting the Module name in the header comment is simply redundant.

See [this comment](https://github.com/swarm-game/swarm/pull/793#discussion_r1007568533):
> maybe we should discuss something more systematic like putting "Swarm contributors", or not listing a copyright field at all.

The root-level copyright doc already covers all of the source files.  If one is interested in module-level authorship, `git` can be queried, e.g.:
```
$ git log --format=%an src/Swarm/Util.hs | sort -u
Brent Yorgey
Karl Ostmo
Ondřej Šebek
Paul Brauner
Tristan de Cacqueray
```

Let's remove the copyright from each Haskell module to maximize information density.

**Comment by byorgey** [comment]
Agreed!
