### ISSUE TITLE
Consider using `brick-list-search` package

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#1127]
Following [this discussion on Reddit](https://www.reddit.com/r/haskell/comments/114i0pj/comment/j8z6sg0/), @amano-kenji published [`brick-list-search`](https://hackage.haskell.org/package/brick-list-search) to Hackage.  We should evaluate whether we can/should depend on it instead of using [our own custom list search code](https://github.com/swarm-game/swarm/blob/main/src/Swarm/TUI/List.hs), and/or whether there is any way we can contribute to the package.

**Comment by xsebek** [comment]
Both that package and [`brick-tabular-list`](https://hackage.haskell.org/package/brick-tabular-list) look amazing!

It's great to see the `brick` ecosystem growing. :slightly_smiling_face:

**Comment by amano-kenji** [comment]
Thanks for recognizing my work. I really worked hard. I appreciate being recognized.

**Comment by amano-kenji** [comment]
I probably need to loosen upper version boundaries considerably for my packages in the near future.

**Comment by amano-kenji** [comment]
The inability to show the separators at the top and the bottom bothered me, but I made it possible to show them at the top and the bottom by adding two functions.

I think you will be satisfied with my library. I think the library is roughly finalized at this point.
