### ISSUE TITLE
Structure templates in YAML

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1138]
Building upon #112, there should be a mechanism to define multi-cell structures.  It should follow the model of Entities, which can be defined both globally in a dedicated YAML file and can have custom definitions in scenario files.

Structures should support:
* orientation
* transparency (aka "masking")
* location

Structures would be defined similar to maps are today, and will include their own "palette".  The palette shall reference pre-existing entities (either built-in or defined elsewhere in the scenario).  See also [this comment](https://github.com/swarm-game/swarm/issues/242#issuecomment-1133773741) on composing structures from plain entities.

One of the entries in the palette shall represent "transparent" cells, allowing the underlying map content to show through.  This could be represented by the "Blank" terrain element, by default.

## Locating structures
The location of the structure shall be specified externally to the scenario map, as with the [`loc` field of robots](https://github.com/swarm-game/swarm/tree/main/data/scenarios#robots).
However, in contrast with how the `robots` section operates today, to facilitate multiple copies of structures, there should be a separate toplevel "placement" section of the scenario file, aside from the structure definitions section.

### Recursive structures

Potentially, we could allow a structure definition to have its own "placement" section.  This would facilitate recursive structures, allowing one to statically compose buildings and towns from smaller units.

## Handling cell conflicts

Overlaying structures on the map might be done *destructively* or *non-destructively*.  For "static" structures, the entities of the overlaid structure shall supersede whatever entity placement had been defined in the map.  Since a cell can only contain one entity, the previous entity is simply "gone".

Looking forward, we may want to use "dynamic" structures to represent "vehicles".  In that case, a parallel "plane" of the world would have to be defined to keep track of the dynamic structures, so that the underlying entities in the world are preserved as the "vehicle" passes over.

At the outset, perhaps we should focus only on static structures.

**Comment by byorgey** [comment]
To me, this seems more general than "structures", it's really just about being able to compose a map out of multiple pieces, i.e. define multiple smaller maps and then overlay them, copy them, etc. to create a larger map (perhaps recursively). (And while we're at it, how about being able to rotate and/or flip them, too.)  Is there something in particular you have in mind that distinguishes "structures" from "maps"?

So what I'm thinking is that instead of the single `map` section we have now, we can have a collection of named maps, where each map can be specified somehow as a combination of explicit drawings (using a palette) and other maps.  I'm not sure off the top of my head what that would look like.  Sometimes you might just want to *draw* the placement of sub-maps on a map --- *i.e.* perhaps a single character in the palette could stand in for an entire map.  But sometimes you might want to just specify e.g. their coordinates.

**Comment by byorgey** [comment]
> Looking forward, we may want to use "dynamic" structures to represent "vehicles". In that case, a parallel "plane" of the world would have to be defined to keep track of the dynamic structures, so that the underlying entities in the world are preserved as the "vehicle" passes over.
> 
> At the outset, perhaps we should focus only on static structures.

Yes, so far I have only been thinking of "structures" in terms of "a collection of cells that we draw/generate all together" but once the cell contents have been generated, we just have a grid of cells as usual, and there is nothing within the game itself that "knows" these cells "go together".  Having the game actually keep track of groups of cells that form a "structure" that can e.g. move all together sounds like it would introduce a ton of complexity.

**Comment by kostmo** [comment]
> Is there something in particular you have in mind that distinguishes "structures" from "maps"?

Nope, and we can adopt the terminology "submaps" if it is a better fit.  Perhaps one distinction is that a "structure" would certainly require a (single-bit) "alpha channel", whereas a simple "map" might not necessarily.  But I do plan to support transparency regardless.

> Sometimes you might just want to draw the placement of sub-maps on a map

I thought about this, but I'm not convinced it's worth supporting.  Currently, map cells have 1:1 correspondence with entity or robot placement, but this would no longer hold true for multi-cell structures.  So the "visualization" benefit evaporates.  And trying to draw the complete overlay of a submap onto a parent map leads to overspecification/maintainability problems.

**Comment by byorgey** [comment]
> Perhaps one distinction is that a "structure" would certainly require a (single-bit) "alpha channel", whereas a simple "map" might not necessarily. But I do plan to support transparency regardless.

Yes, I would think transparency would be a useful feature no matter what you are drawing.

> I thought about this, but I'm not convinced it's worth supporting. Currently, map cells have 1:1 correspondence with entity or robot placement, but this would no longer hold true for multi-cell structures. So the "visualization" benefit evaporates. And trying to draw the complete overlay of a submap onto a parent map leads to overspecification/maintainability problems.

Makes sense, agreed.  So you can just specify the placement of sub-maps by coordinates --- and I would strongly argue for those coordinates to be *relative* to the map on which they are being placed.

**Comment by LeshaNewsomc** [comment]
The proposed mechanism should follow the model of entities, which can be defined globally in a YAML file and have custom definitions in scenario files. The structures would be defined similarly to maps and would include their own palette, which should reference pre-existing entities. Additionally, the structures should support orientation, transparency, and location.

The placement of the structure should be specified externally to the scenario map, and there should be a separate top-level "placement" section of the scenario file to facilitate multiple copies of structures. It may be possible to allow a structure definition to have its own "placement" section, which would facilitate recursive structures, allowing one to statically compose buildings and towns from smaller units.

Regarding cell conflicts, overlaying structures on the map might be done destructively or non-destructively. For "static" structures, the entities of the overlaid structure shall supersede whatever entity placement had been defined in the map.

The idea of dynamic structures that represent vehicles is mentioned, but the conversation suggests focusing only on static structures at the outset.

Finally, the conversation touches on whether "structures" is the best term for this feature, and the authors consider whether "submaps" might be a better fit. They discuss whether it would be useful to draw the placement of sub-maps on a map but ultimately decide against it.
