### ISSUE TITLE
Getting a reference to a specific entity

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#114]
Normally, entities can be looked up and referred to by their name, even though entity names are not actually guaranteed to be unique. This works fine most of the time---if you refer to a `log`, it really doesn't matter which one you get since they are all identical.  However, in some scenarios specific entities will need to be differentiated.  The motivating use case is `box`es: if you have several `box`es in your inventory and put some items in one of them, you now want to be able to refer to the specific box containing your items as opposed to the others.  I propose two operations to assist with this:

* `rename : string -> string -> cmd ()` takes one entity with the first name (it's undefined which) and renames it to have the second name.   For example if you want to pick out a specific `box` to put some items in, you could first execute `rename "box" "mybox"`.  Now `mybox` will show up in your inventory separate from the other `box`es.
* `unique_name : string -> cmd string` will generate a name based on the given one which is guaranteed to be globally unique.  Maybe you are programming some robots to do an automated task and you don't plan to ever look at their inventories, so you would rather just name some boxes automatically and pass around their names in variables.

I'm very open to other suggestions re: API.

**Comment by byorgey** [comment]
After thinking about this more, it seems a bit arbitrary / unsafe to continue doing everything with strings.  Another possibility might be to do something similar for entities that we have done for robots in #303 : introduce a new `entity` type, and give every entity a unique (internal) ID.  (Entities of which we have many copies would continue to all share the same ID.)  Then instead of `rename` we could have something like `get_entity : string -> cmd entity` which would actually get a reference to a specific entity with the given name (i.e. it would assign a new ID to one specific entity and return a reference to that).  I'm not sure about all this --- it seems there must be a more elegant way to do it.

**Comment by byorgey** [comment]
Brainstorming a bit more about having a specific `entity` type.

- Suppose e.g. `give` now has type `give : robot -> entity -> cmd ()`.  How would you get an `entity` value to pass to it?
    - If it's something you just harvested, this is no problem, since presumably we would have `grab : cmd entity`.
    - But otherwise it seems like it's going to be annoying managing entity references.
- I suppose there needs to be a way to turn `string` values into `entity` references, or perhaps just make `string` a subtype of `entity`?
    - `entity : string -> entity` ?  If an entity of that name doesn't exist, we get a "null entity", perhaps.  Having it be ` -> maybe entity` would be more correct but would be harder to use in the early game...

**Comment by xsebek** [comment]
Relatedly I needed a way to get a specific `robot` by its name that is specified in a challenge.

Maybe we could come up with a unified way to turn `string` into a proper type like `entity` or `robot`.

**Comment by byorgey** [comment]
I'm going to close this issue and move the focus to #455 (which also includes a link back here so we can still read the historical discussion).
