### ISSUE TITLE
isPresent command

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1140]
Let's define a command that can answer whether a certain entity exists within a rectangular region.

It takes arguments of a scalar integer "distance" (using [Chebyshev distance](https://en.wikipedia.org/wiki/Chebyshev_distance)) and an entity name:

    isPresent :: int -> text -> bool

It would require `god` capability, or perhaps some other system-robot-exclusive capability that we might call `"detect"` or `"senseremote"` (a counterpart to `sensefront` and `sensehere`).  Come to think of it, maybe the command itself should be named `detect`?

There are probably good non-system applications for such a command, provided that the radius is capped.

Perhaps an [olfactometer](https://en.wikipedia.org/wiki/Machine_olfaction) device could provide the `senseremote` capability.

## Motivation

I found myself wanting to create a Goal that involved completely clearing an irregularly-shaped forest (not just harvesting, but removing entirely).  However, to check this with a system robot would entail a raster scan over the area in question and is inefficient.

## Alternative approaches

Another, more precise alternative may be to supply exact coordinates:

    isPresent :: (int * int) -> (int * int) -> text -> bool

The coordinates would be relative to the robot issuing the command.

**Comment by byorgey** [comment]
Sounds good to me.  I think I prefer the version that takes coordinates.  That seems like it would be easier to use and doesn't require thinking about distances.
