### ISSUE TITLE
Nethack homage: Amulet of Yoneda

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1146]
In [NetHack](https://www.nethack.org/) ([wiki](https://nethackwiki.com/wiki/Amulet_of_Yendor)):
> The ultimate goal of a game of NetHack is to find the **Amulet of Yendor** 

We should make obtaining the "Amulet of [Yoneda](https://en.wikipedia.org/wiki/Yoneda_lemma)" a goal of a custom scenario, or maybe even make it the toplevel goal of the game?

**Comment by byorgey** [comment]
Yendor Amulet = Yoneda LU Term
Yoneda Lemma = Deem Anomaly = Yam Lemonade = Yeoman Medal

Hmm, maybe you can get a Yeoman Medal for completing a farming challenge...
