### ISSUE TITLE
Conceptually related games

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1154]
Let's use this issue to track other programming-oriented games.

**Comment by kostmo** [comment]
Came across [Joy of Programming](https://store.steampowered.com/app/2216770/JOY_OF_PROGRAMMING__Software_Engineering_Simulator) in [this Reddit post](https://www.reddit.com/r/Python/comments/11l0a09/a_programming_game_where_you_use_python_to/).

It is Python-based and entails solving 3D puzzles, by a C.S. professor (Prof. Scherer).

**Comment by kostmo** [comment]
[Quadrilateral Cowboy](https://en.wikipedia.org/wiki/Quadrilateral_Cowboy) is another 3D game, [mentioned](https://www.reddit.com/r/Python/comments/11l0a09/comment/jbdeyd6/?utm_source=reddit&utm_medium=web2x&context=3) in the same [Reddit post](https://www.reddit.com/r/Python/comments/11l0a09/a_programming_game_where_you_use_python_to/).

**Comment by byorgey** [comment]
These are great links, thanks!

Maybe we can turn this into a wiki page or something?  It bothers me to have an issue which can never be closed as "completed" since it's just a discussion/repository of information and doesn't represent any kind of task... :stuck_out_tongue:

**Comment by byorgey** [comment]
Moved this information to https://github.com/swarm-game/swarm/wiki/Inspiration-and-Prior-Art .
