### ISSUE TITLE
drill command should return the name of the entity obtained

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1157]
When drilling, either an entity will be obtained in one's inventory, or it will be changed in place on the ground.

This proposal is to change the type of the `drill` command from

    dir -> cmd unit

to

     dir -> cmd (unit + text)

The command shall return either `unit` (if nothing was brought into the inventory) or the name of the entity obtained.
Since it is possible for recipes to have multiple `portable` outputs, the entity returned by the command shall be the **first** portable output listed in the recipe.

This new behavior aligns it with the `grab` command, which also returns the name of the thing that was added to the inventory.

**Comment by byorgey** [comment]
Makes sense to me!  And just to make sure I understand, the reason the type should be `cmd (unit + text)` instead of just `cmd text` (like `grab`) is that the `drill` command can in some cases succeed without adding anything to your inventory?

**Comment by kostmo** [comment]
> the reason the type should be `cmd (unit + text)` instead of just `cmd text` (like `grab`) is that the `drill` command can in some cases succeed without adding anything to your inventory?

Yes, exactly.
