### ISSUE TITLE
Implement more sensory commands

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1171]
- [x] `sniff` command (#1181)
- [x] `sniff` capability (#1181)
- [ ] `sniff` recipe (device defined in #1263)
- [x] `chirp` command (#1181)
- [x] `chirp` capability (#1181)
- [ ] `chirp` recipe
- [x] `resonate` command (#1204)
- [x] `resonate` capability (#1204)
- [ ] `resonate` recipe

From [this comment](https://github.com/swarm-game/swarm/pull/1170#discussion_r1142555693):
> 
> ```
> sniff : text -> cmd int
> ```
> Olfactory.  Physically interpreted as a "point sensor", thus cannot infer direction.  Return the **distance** to the nearest entity of a given name.  To use it, the player can move around in different directions to see whether they are getting "hot" or "cold".
> 
> ```
> chirp : text -> cmd dir
> ```
> Sonar based on two "ears" will return the **direction** to the nearest entity of a given name.  To use it, the player can move in said direction until the reported direction reverses, and then progressively home in on it (or switch to another close-range sensing modality).
> 
> ```
> resonate : text -> ((int * int) * (int * int)) -> cmd bool
> ```
> The original Boolean type signature.  Usage would entail a [quadtree](https://en.wikipedia.org/wiki/Quadtree) search strategy.  The physical justification is more of a stretch, but could entail something like MRI, where a strong magnetic field is applied over a given area, and a stimulating pulse is emitted, exciting the particles of the entity in question.  A non-directional signal is returned from the excited area, with a receiver being tuned to the frequency of the entity's particles.

**Comment by byorgey** [comment]
Collecting some ideas here for recipes + new devices (will fill in more detail later).

- `rolex`:
    - 1 `clock`
    - 1 `scanner`
    - This would be kind of difficult to make, but `watch` doesn't really add a whole lot of expressive capability, it's just more efficient (without `watch` you can just use a `scanner` to poll the adjacent location).
- `olfactometer`:
- `dozer blade`:
- Proposed device for `chirp`:
- Proposed device for `resonate`:
