### ISSUE TITLE
format subcommand is a misnomer

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1185]
The `format` subcommand claims to "[format a file](https://github.com/swarm-game/swarm/blob/9e2f8b29613223b7eaded5690257abbc6553ac93/app/Main.hs#L46)", but what it really does is validate parseability and just [dump the input verbatim](https://github.com/swarm-game/swarm/blob/9e2f8b29613223b7eaded5690257abbc6553ac93/app/Main.hs#L155-L159).

**Comment by byorgey** [comment]
I think the original intention is that it *will* format a file, but we haven't implemented that part yet.  But perhaps we should make the help text more truthful in the meantime. :smile:   Related: #7, #11.
