### ISSUE TITLE
Multi-cell movement command

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1218]
A command should exist that allows moving multiple tiles in a single tick:

    stride : int -> cmd unit

A maximum distance (say, `64`) shall be hard-coded.
The robot proceeds up to the specified cell count or until an `unwalkable` entity is encountered.

Perhaps a new entity property `resistive` (or synonym) could be introduced that is able to halt a `stride`, but not prevent passage with the standard `move` command.

This command operates in contrast to the trick of using a non-normalized initial orientation in the `chess` scenario, in which the movement vector is fixed at the outset and unchangeable.

We may choose not to make this command available in the "Classic" game, but could provide custom devices in Challenge scenarios which would allow the player to implement algorithms that require `O(1)` array access.

**Comment by byorgey** [comment]
I agree maybe we don't want this available in the "Classic" game, but I like the idea of being able to have O(1) access to physically simulated arrays in some scenarios.
