### ISSUE TITLE
Command for changing robot display attribute (e.g. color)

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1230]
We could either create a new command, or modify the existing `appear` command to accept another (optional) argument.
The type signature might change to:

    appear : text -> unit + text -> cmd unit

The `unit + text` represents either the new attribute name or no attribute override.

There is little usage of the `appear` command so far, so changing it should be easy.

**Comment by byorgey** [comment]
Yeah, the `appear` command is really kind of a placeholder, I'm totally fine with changing it.
