### ISSUE TITLE
Sokoban support

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1234]
Swarm already supports most of the elements required to implement [Sokoban](https://en.wikipedia.org/wiki/Sokoban).  All that is really needed now is a `push` command.

The `push` command would have the same type signature as `move`.  Both the robot and the entity directly in front of it will move forward by one space, so long as no entity already occupies the destination space.  An entity can be `push`ed if it is `portable`, even if that entity is `unwalkable`.

**Comment by byorgey** [comment]
Great idea!  Maybe `tank treads` could provide `push`?  Like in order to push you need more power/traction than what you need just to move.
