### ISSUE TITLE
YAML attribute to enable instantaneous execution of all commands for a given system robot

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1245]
See rationale in #1244:

"Judge" robots suffer from some lag due to finite command duration, and therefore sometimes "miss" the events they are supposed to observe.  One mitigation is the `instant` command, but...

> inserting `instant` requires some care; it can cause the game to freeze if it gets tangled with a recursion.
>
> Perhaps a better solution in the long term would be to have some way to make system robots (in particular, invisible "judge" robots) execute *all* commands in zero ticks.  This should not be the default for all system robots, especially those that are not `invisible`; sometimes we prefer that their commands have finite duration to interact plausibly with the player.

**Comment by byorgey** [comment]
I'm not against this, but I'm not sure I understand why inserting `instant` requires some care and can cause the game to freeze.  Can you give an example?  Independently of whether we implement this issue, I'm curious to see whether there's any way to improve the way `instant` works to make it less fragile.

**Comment by kostmo** [comment]
Here's one way to cause a freeze in creative mode in the REPL:

    instant (wait 1);

**Comment by byorgey** [comment]
Ah, I see, because the machinery for running an atomic/instant command wants to keep running it until it completes, but the `wait` can't complete until the next tick, so it just sits there trying to step the CESK machine infinitely.  Actually, this makes me wonder, do `Waiting` robots just get stepped a bunch (with no effect) until they run out of steps for the tick? That seems a bit silly.

**Comment by byorgey** [comment]
Now that #1267 is addressed, I'm not sure this is necessary any more.  It should be possible to just use `instant` as needed.  I'm going to close this, but feel free to reopen if there is a compelling argument for this feature I haven't considered.
