### ISSUE TITLE
Inventory search

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#126]
As you progress through the game, most likely the inventory will get very long and it will be annoying to have to scroll through the whole thing to find that one item for which you forgot the syntax or need the recipe or whatever.  We should add an incremental search mode, so that when the inventory is highlighted you can hit the `/` key and then start typing a few characters of the thing you're looking for to narrow the list based on your search term.  Maybe `brick` already has something like this built in for lists? I am not sure.

**Comment by fryguybob** [comment]
I've wanted to explore `brick` for a while, so I started working on this.

**Comment by byorgey** [comment]
Here's another idea: if we got rid of the j/k key navigation in the inventory panel (though I know that would make some people sad), what if simply typing in the inventory panel causes it to narrow?  I'm imagining something like

- There is a notion of a "current search string"
- Every time you hit a key that denotes a character, it appends to the current search string.
- The inventory list is filtered according to some sort of (fuzzy?) search based on the search string.
- The current search string could be displayed somewhere, maybe along the bottom edge of the panel
- There is some other key (Esc, perhaps?) to clear the current search string.

I think this would be fairly simple and wouldn't require coding any kind of independent "search mode".

**Comment by byorgey** [comment]
Note that #151 contains an initial (but currently abandoned) attempt at this.

**Comment by byorgey** [comment]
@kostmo I see you assigned yourself to this issue a long time ago --- had you written any code for it yet?  Or did you have any ideas beyond what's recorded here?  I might work on it if you're not.  The lack of inventory search is something that annoys me often. :smile:
