### ISSUE TITLE
`instant (wait 1)` causes the game to freeze

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#1267]
In creative mode, or with a system robot, it is possible to completely freeze the game by executing something like `instant (wait 1)`.  See the original comment here: https://github.com/swarm-game/swarm/issues/1245#issuecomment-1546731939

What *should* `instant (wait 1)` do?  I think the fact that it causes a freeze should be considered a bug, but it is unclear to me what it ought to do instead.  Options include:
1. `wait` commands executed inside `instant` are simply ignored, so *e.g.* `instant (move; wait 1; move)` would be equivalent to `instant (move; move)`
2. `wait` commands inside `instant` terminate:
    - No error: If a `wait` command is executed inside `instant` then it goes into effect and immediately terminates the `instant` command; any subsequent commands are ignored.  *e.g.* `instant (move; wait 1; move)` would only end up moving once.
    - With error: If a `wait` command is executed inside `instant` then an exception is thrown.  *e.g.* `instance (move; wait 1; move)` would only move once, and would fail with an exception.
4. If a `wait` command is executed inside `instant`, then it goes into effect immediately, any any subsequent commands will be executed `instant`ly once the robot wakes up.  *e.g.* `instant (move; move; wait 1; move; move)` would move twice in one tick and then twice in the next tick.

I think these are ordered roughly from easiest to hardest in terms of implementation difficulty.

**Comment by byorgey** [comment]
See also [this comment](https://github.com/swarm-game/swarm/issues/1245#issuecomment-1553245276):

> Ah, I see, because the machinery for running an atomic/instant command wants to keep running it until it completes, but the wait can't complete until the next tick, so it just sits there trying to step the CESK machine infinitely. Actually, this makes me wonder, do Waiting robots just get stepped a bunch (with no effect) until they run out of steps for the tick? That seems a bit silly.

**Comment by xsebek** [comment]
Would it be OK to throw an exception?

At least we would be able to notice it in tests.

**Comment by byorgey** [comment]
That is different from option 2, I added it as another option.
