### ISSUE TITLE
Draw annotated contiguous boundaries with proper wall glyphs

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1271]
Can create a new entity property called `"boundary"` for which, upon loading the scenario, contiguous boundaries of this entity will be automatically replaced with the appropriate corner or straight wall entities.

E.g.:

```
entities:
  - name: wall
    display:
      char: '#'
    description:
    - Solid boundary
    properties: [known, unwalkable, boundary]

........
..####..
..#..#..
..#..#..
..####..
........
```
would be replaced with:

```

........
..┌──┐..
..│..│..
..│..│..
..└──┘..
........
```

Should be a fun programming exercise.

**Comment by byorgey** [comment]
To keep it simple, you could just check each `boundary` entity to see which of the four adjacent cells also contain a `boundary` entity, and replace it with the appropriate type of wall --- not just corner or straight but also 3- or 4-way T junctions.  Then we don't have to fiddle at all with any kind of graph search and it has a very straightforward semantics.

For example,

```
....#...
..####..
..#.##..
..#..#..
..####..
........
```
could be replaced with
```
....╷...
..┌─┼┐..
..│.└┤..
..│..│..
..└──┘..
........
```

**Comment by xsebek** [comment]
To make this more universal (e.g. for `wires` or different fonts), how about:
```yaml
entities:
  - name: wall
    display:
      char: '│'
      connections: {"nWsE": "─", "NwSE": "┤", ...}
```
Internally we could use a different constructor inside display, so that most entities never have to know about this.

Diagonal connections are probably not worth it, though there are a few characters for them like `╱` or `╳`.

**Comment by byorgey** [comment]
Also, to be clear, I think it sounds much more reasonable if this is simply about how to *render* boundary entities, not about literally *replacing* boundary entities with various straight and corner wall entities.  I know we do currently have entities called "upper right corner" and so on, but I'd like to get rid of those.
