### ISSUE TITLE
Perform requirements analysis on static argument to `use` command

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1301]
From https://github.com/swarm-game/swarm/pull/1287#discussion_r1210858714:

If you write a program like `build {move; use "flerb" forward; move}` it will fail, because the requirements analysis will not figure out that we should automatically equip a `flerb` when building the child robot. You would have to explicitly write e.g. `build {move; require "flerb"; use "flerb" forward; move}`. We might consider adding something to the requirements analysis which will at least work when use is applied to a statically known device name, as in this example.

**Comment by byorgey** [comment]
I might do this at some point, but in case someone else wants to tackle it first, it would require adding a special case for `TApp (TConst Use) (TText device)` to the `requirements'` function, right before the generic case for `TApp`:

https://github.com/swarm-game/swarm/blob/5a034b59395fea20cfe80af9aad5569002a4e126/src/swarm-lang/Swarm/Language/Requirement.hs#L222-L225

I suppose it should return `singletonDev device` in that case.
