### ISSUE TITLE
Device to give exceptions capability

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#132]
Right now the `try` and `raise` commands are available to all robots, but the intention is that there should be a device to give this capability.  I don't think it should be available too early in the game.  Suggestions welcome!

**Comment by polux** [comment]
What about a device called "second chance"? :) Or a "stack rewinder".

**Comment by byorgey** [comment]
I was thinking of some kind of "time travel" device, but I guess it would make more sense for that to go with #133 .  I like the idea of a "stack rewinder", that's pretty literally what an exception does.  Or maybe some kind of "catching" device, like a baseball glove or a butterfly net, or something like that...

**Comment by byorgey** [comment]
I've played through the game a few times after the addition of iron etc. in #373 , and without using exception handling at all, it's very possible to set up some comfortable automatic resource extraction operations to amass on the order of thousands of basic resources (trees, lambdas, bits, copper/iron ore, sand, water, etc.)  Exceptions will be particularly useful as a player then wants to expand beyond the initial screen and send robots out to explore (to *e.g.* be able program robots to deal with running into/going around things in their way).  So whatever device we come up with, it should transitively have a large cost, *e.g.* hundreds or thousands of one or more basic resources.

**Comment by byorgey** [comment]
How about just a device called a `net` (for catching errors)?   As for the recipe, I imagine a net has to be made out of a bunch of `string`.  One idea would be:
- Add a growable `cotton` entity to the world (mixed in with the flowers + grass currently in the small/soft/natural biome)
- Add a recipe for producing 1 `string` from 4 `cotton`
    - Possibly requiring some kind of catalyst? Like a "spinning wheel"?  I don't know if I want to add yet another device though. Maybe we could just require a `small motor` as a catalyst?
- A `net` can then be made from 256 `string`.
