### ISSUE TITLE
better name for `--cheat` CLI option

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1324]
There may be a name that better reflects the capabilities afforded by the `--cheat` option.  Possible alternatives:
* `--omnipotent`
* `--superuser`

Also related: #1270

**Comment by xsebek** [comment]
How about `--debug`? 🙂

**Comment by xsebek** [comment]
Related Issue:
- #1112

We could go further and have `--debug` imply `--debug=CESK;...`.

I think it might be best to allow players to turn on any debugging/cheating features during run. That is how other games do it. The flag would simply enable them at start, which is sometimes necessary. In same way, we could add `--creative` to start in creative mode which can also be useful for debugging early failures.

**Comment by byorgey** [comment]
> I think it might be best to allow players to turn on any debugging/cheating features during run. That is how other games do it. The flag would simply enable them at start, which is sometimes necessary. In same way, we could add `--creative` to start in creative mode which can also be useful for debugging early failures.

Adding a `--creative` flag to start in creative mode makes sense, as does adding some kind of `--debug` flag to start in debug mode.  However, I am not sure about always allowing players to turn on any debugging/cheating features.  It would suck if you just happened to accidentally hit Ctrl-V during a run and it invalidated any records/achievements.

**Comment by xsebek** [comment]
> if you just happened to accidentally hit Ctrl-V during a run

If it brought up a dialog with list of debugging features and a confirm/cancel buttons, then you could always cancel. 🤔

**Comment by byorgey** [comment]
> dialog with list of debugging features and a confirm/cancel buttons

True, that might be a good way to do it.

**Comment by xsebek** [comment]
Related:
* #2073

It would be useful to refactor/split `--cheat` so that it does not do as many things.
