### ISSUE TITLE
Recommend Fourmolu v11  locally

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1328]
It seems that fourmolu version `0.10.1.0` (and `0.10.0.0`) is much slower than `0.9.0.0`.  It takes 50 seconds vs. previously 2-3 seconds.

Upgrading to version `0.11.0.0` or `0.12.0.0` seems to correct the regression.
Even though restyled.io supports only `0.10.1.0`, perhaps we could recommend a later version for local use.

However, there are some problems:

* Before fourmolu `0.12.0.0`, all data constructor comments were formatted with `-- ^`.  For `0.12.0.0` and afterward, they use `-- |` (see https://github.com/tweag/ormolu/issues/844 ).  This would cause thrashing between a local fourmolu and restyled.io.
* fourmolu `0.11.0.0` fixes the perf regression, but lacks the `single-constraint-parens` config option (added in v12, see https://github.com/fourmolu/fourmolu/pull/304 ).  So a bunch of parentheses will get added if v11 is run locally.  However, this may be less painful than the 50 second runtime of `0.10.1.0`, and should be easily revertible once restyled.io starts supporting fourmolu v12.

**Comment by xsebek** [comment]
@kostmo thanks for investigating the situation. 👍

It seems [Fourmolu 0.13.0.0](https://github.com/fourmolu/fourmolu/releases/tag/v0.13.0.0) just released two days ago, but I assume it does not help us with Restyled.io compatibility. 😅
