### ISSUE TITLE
Fire that spreads

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1355]
Perhaps this could be generalized to "spreadable growth", but I will discuss with the use case of fire in mind.
A new entity property, `combustible`, may be introduced.

Setting an entity on fire would work something like the inverse of "growth" and the `harvest` command; the entity is replaced by a system robot that depicts (and animates) "burning", as opposed a to a bot that represents "growing".

While burning, there should be a random (customizable) chance of spreading to an adjacent tile each tick.  For now perhaps all entities will have a default duration that they may "burn" before self-extinguishing.  As some future extension, perhaps the duration could be customized analogously to the `"growth"` property.

By default, after extinguishing, all burned entities will yield an `"ash"` entity.  Again, as a future extension, this might be customized to yield other kinds of entities based on what entity it started as.

Other potential spreadable phenomena:
* radiation
* weeds
* water (coastline erosion)
* sand (desert erosion)

Scenario ideas:
* plow a fire break
* Build a radiation [containment dome](https://en.wikipedia.org/wiki/Chernobyl_New_Safe_Confinement)

This may make use of #1343 to customize the display sequence.

**Comment by xsebek** [comment]
With this we could have impassable trees. 😁
Spreading a forest fire is somewhat common in Factorio to clear space for buildings.

Their world DSL could be modified with trees in clamps _and a discrete probability (say x%2 == 1)_. (Maybe only for the scenario.)

Thinking about this, is there a way to stop the fire with water? it would be a shame if you set your fields on fire and could only contain, but not stop it.

**Comment by kostmo** [comment]
> Thinking about this, is there a way to stop the fire with water? it would be a shame if you set your fields on fire and could only contain, but not stop it.

Resorting to containment is somewhat realistic; see [video](https://youtu.be/0ZjCOAnmUaQ?si=ZFCkQ4_jrh9n7rL3&t=30).
