### ISSUE TITLE
Use a lens to modify robot state for "Say" command

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1372]
See [this code](https://github.com/swarm-game/swarm/blob/485e6ace1f9d4860416667568f24929d357a0680/src/Swarm/Game/Step.hs#L1585-L1592) (originally added [here](https://github.com/swarm-game/swarm/pull/565/files#r1264589864)).

It makes use of the `addRobot` function which seems like a non-idiomatic way to modify robot state.

**Comment by byorgey** [comment]
Agreed, I think.  I was worried at first that `addRobot` is doing something special but I don't think it is.  It should be possible to just modify the robot map for each robot in range.
