### ISSUE TITLE
Cosmic teleportation command

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1381]
The current `teleport` command operates only within a single subworld.  Introduce a new variant of this command that accepts both a subworld name and planar coordinates.

**Comment by byorgey** [comment]
Suggestion: `warp : Actor -> Text -> (Int * Int) -> Cmd Unit` ?

**Comment by byorgey** [comment]
Oh! Hah, I forgot that we already have `warp`. :smile:
