### ISSUE TITLE
.swarm_history still around without any use

### ISSUE THREAD

**Issue by noahyor** [swarm-game/swarm#1387]
When I ran swarm and entered some commands, the `.swarm_history` file remained unchanged.

**Comment by noahyor** [comment]
It remained unedited even on exit for some reason.

**Comment by byorgey** [comment]
Oh! I remember.  See https://github.com/swarm-game/swarm/pull/253 : the REPL history is no longer stored in `.swarm_history`, it is stored somewhere like `~/.local/share/swarm/history` (but possibly somewhere different depending on if your `$XDG_DATA_HOME` environment variable is set).

**Comment by noahyor** [comment]
Would it make sense to remove this file, since it has no current use?

**Comment by byorgey** [comment]
There is no `.swarm_history` file checked in to the repo, so if there is one in your `swarm` directory it's probably just an old file from when Swarm used to store its history that way (git will not delete files that are not tracked by the repo).  It should be completely safe for you to delete it.

**Comment by noahyor** [comment]
Thanks!
