### ISSUE TITLE
Reverse direction without generalized turning

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1399]
I want to create a scenario in which the only two movements available are **forward** and **backwards**.  The two ways to accomplish this I can think of are:
1. Further partition the capabilities required to reference specific `Direction`s (see `COrient`), such that the `turn` command can execute `turn back` but not `turn left` (or any other direction, for that matter).
2. Provide a new command that simply moves the robot backwards (call it `Backup`).  `Backup` shall be identical to `Move` except in the opposite direction.

Option 2 seems simpler for an implementation standpoint.

**Comment by byorgey** [comment]
Another way to accomplish it could be to add a negated objective that checks whether you ever face e.g. north or south?

**Comment by kostmo** [comment]
> add a negated objective

That's a clever idea, though I think a bit harder to justify "physically" that turning the wrong way should result in a loss.  Absence of "lateral control", with only "longitudinal control" available, can be explained by physical equipment.

In this hypothetical scenario, the only means to turn might be portals.  Forward-only movement restricts the robot to a single track, whereas the addition of backwards movement would allow for a branching track.

And perhaps later in the same scenario, the player may gain full ability to turn.

**Comment by byorgey** [comment]
Makes sense, just trying to list all possible options, but I agree the options you listed are better.  A `backup` command could be independently useful as well.

**Comment by kostmo** [comment]
For posterity: see also https://github.com/swarm-game/swarm/issues/950#issuecomment-1369730049
