### ISSUE TITLE
Words reflowed across a line break in objective text are missing a space between them

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#1409]
![markdown2](https://github.com/swarm-game/swarm/assets/533859/eae4a0af-302b-483d-a07a-816ef7d21dc9)

Notice "nextto" and "samedirection" in the screenshot above.  Notice that "to build" has a space even though those words are also on separate lines in the `.yaml` file.  I think the difference may be that "next to" and "same direction" are contained in quoted (i.e. starting with a `|`) text in the `.yaml` file whereas "to build" is in unquoted text.  For reference, here is the relevant `.yaml` file:

https://github.com/swarm-game/swarm/blob/1eb2f9c567b51a5242323bdf59277aff5879618a/data/scenarios/Tutorials/build.yaml

**Comment by byorgey** [comment]
I think this was introduced in #1106 .

**Comment by xsebek** [comment]
@byorgey it was for sure, I was just lucky to not hit this during testing or did not notice. 😄

I am debugging it and will have a fix soon or revert.

**Comment by xsebek** [comment]
Oh no, I did not realise the parser splits on every single token, so the created tree looks like this:
```Haskell
d =
    Document
        { paragraphs =
            [ Paragraph
                { nodes =
                    [ LeafText (fromList []) "A"
                    , LeafText (fromList []) " "
                    , LeafText (fromList []) "pedestal"
```
There are spaces in this structure where they should be, but this is definitely not what I expected when writing code that works with it.

**Comment by byorgey** [comment]
> the parser splits on every single token

Hah, that is an interesting choice.  So if you just concatenate all the parsed nodes do you get back the exact original text?

**Comment by xsebek** [comment]
@byorgey yes, now that I fixed chopping, you should get almost exactly the original text.
