### ISSUE TITLE
Use a new "Changelog" label on PRs to suggest their inclusion in Changelog.md

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1429]
Would be convenient to have a way to distinguish PRs that are "minor fixups", or otherwise not worth mentioning in the upcoming release changelog, from the notable PRs.

This label can either be added by the PR author as a "self-nomination" or by the author of the Changelog to facilitate bookkeeping.

**Comment by byorgey** [comment]
Good idea. The tag could also be added by reviewers.

**Comment by byorgey** [comment]
I created a `CHANGELOG` label.  Are there any steps we can take to help ourselves remember to use it?

**Comment by byorgey** [comment]
See #1434 .
