### ISSUE TITLE
Sub-worlds

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#144]
A crazy idea that just came up in IRC is to have certain cells function as entrances and exits to other sub-worlds.  e.g. there could be caves, buildings, ...  This seems like it would be fun and could be an easy way to add new stuff to the world without taking up a ton of space.

Concretely I don't think this would be all that hard to add (famous last words, right?).  A meta-world will now consist of a collection of worlds, each with an integer ID.  A location now consists of a pair of (world id, coordinates).  An entrance to another area just stores the location that it links to.

**Comment by xsebek** [comment]
So to store this we would have sections world<sub>1</sub>,world<sub>2</sub>,... and entrances `Bimap Location Location`?

I'd really like to `drill` through mountains and `view` the robot. The border tiles of mountain terrain could be the entrances. :thinking: 

Possibly related:
- could improve the user experience of #143 
- could slightly complicate #50 (but we can design the save format with sub-worlds in mind)

**Comment by byorgey** [comment]
> So to store this we would have sections world1,world2,... and entrances `Bimap Location Location`?

Well, I think it is up for debate whether the entrances should be a `Bimap`.  That would mean you can always immediately get back to where you came from and the worlds would form a proper undirected graph.  Letting it be a simple `Map` instead of a `Bimap` opens the possibility for bugs ("oops, I forgot to connect this thing back to that thing...") but also for more interesting topologies, e.g. several worlds connected by a loop, or one-way dungeons (once you go in, the only way out is to fight your way through to the exit...).

**Comment by byorgey** [comment]
Just thinking about the mechanics of moving between sub-worlds... a simple idea might be to use the `down` and `up` directions (well, we already have `down` but we could add `up`).  So `turn down; move` would move into a subworld.  To be clear, I'm not proposing to make the world 3D, but rather, that every sub-world portal would be specified as being in either the "up" or "down" direction.

Amusingly, when testing this I realized that executing `turn down` causes a robot to look like the base.

**Comment by byorgey** [comment]
An important question is how you would be able to see the sub-worlds.  Can you `view` a robot that is in a subworld?  Maybe you would have to develop mapping technology first, so you could send in robots to explore?  Or maybe you just have to put tank treads on the base and go explore yourself?
