### ISSUE TITLE
Split documentation generators into separate executable

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1443]
I've introduced `pandoc` as a dependency for #1436.

If the documentation generation was split off into a separate binary, say `swarm-docs`, then `pandoc` would not need to be compiled when just running `swarm`.

**Comment by xsebek** [comment]
@kostmo could we make it a [Stack](https://stackoverflow.com/a/65540046)/[Cabal](https://stackoverflow.com/a/65541020) script? It seems the table generation does not depend on Swarm and we could run it as a one file script as long as Stack/Cabal provided the dependencies.

One thing to consider is that we depend on Swarm functions in DocGen, so if you wanted to add new generated content and it required a change in Swarm, you would have to release Swarm first or tell cabal to download sources from Git.

The other advantage to having doc generation be part of Swarm is that we can use it in integration tests to check that our docs are up to date. I am sure it could be done with separate executable as well, it just gets slightly more complicated.
