### ISSUE TITLE
Check scenario ordering errors in CI

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#1449]
Oddly it seems some warnings sneaked past our integration tests:

<img width="505" alt="Screenshot 2023-08-23 at 10 14 15" src="https://github.com/swarm-game/swarm/assets/44544735/d3a1e33d-677d-47a0-8d6a-43276a20c64c">

While benign, there is no reason players should see those.

**Comment by byorgey** [comment]
Agreed, I guess we have not actually been checking that in CI, but we should definitely add something so CI will fail if any such warnings are generated.

**Comment by byorgey** [comment]
Currently in the integration test suite we call `initPersistentState`, but by that point it is too late: `initPersistentState` takes all the warnings generated by *e.g.* `loadScenarios` and adds them to the message log.  I think we should just add a new test that calls `loadScenarios` directly and checks to make sure the generated list of warnings is empty.
