### ISSUE TITLE
Add solution for World101 tutorial

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#1450]
The tutorial world101 is missing a solution.

Now that we have a world DSL we should test that it produces a playable world.

**Comment by xsebek** [comment]
@byorgey I noticed this thanks to this comment 😄 

https://github.com/swarm-game/swarm/blob/888ee44d18abb926c0af4eb88254c9ba943805c1/test/integration/Main.hs#L295-L301

**Comment by byorgey** [comment]
Hah, you're right, it doesn't have a solution, does it?  We should definitely be able to add one, since it has a fixed seed.
