### ISSUE TITLE
Make "get current time" effect

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#1502]
There are several places where we have a `Has (Lift IO)` constraint *only* because we need to get the current time.  Instead, we should create a custom effect for getting the current time, and then interpret it into IO later.  This way we have a much clearer picture of what effects we actually need.

I'll probably get around to this sooner or later, but could also be a nice issue for someone who wants to learn more about how `fused-effects` works.

**Comment by p3rsik** [comment]
I can't find where the definitions for existing effects are(in fact, I don't see any effects outside of default `State` and the like). Can you point me to them, so that I would know where to start, please?

**Comment by byorgey** [comment]
I don't think we currently define any custom effects.  See https://github.com/fused-effects/fused-effects/blob/main/docs/defining_effects.md for an explanation of how to define new effects with the `fused-effects` library.

**Comment by p3rsik** [comment]
@byorgey I was asking since I'm not sure where would be the ideal place to add this, maybe you could point me to something?
