### ISSUE TITLE
Framework for flashing temporary messages somewhere

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#1506]
I think it would be nice to have a generic framework for flashing up temporary messages, *e.g.* have the message appear and persist for a few seconds, then disappear.

- This would be useful for flashing a message when you get an achievement --- currently there is no way to know when you have unlocked an achievement, other than looking at the Achievements menu later.
- We could also flash a message when new recipes or commands are unlocked.
- I imagine we would find other uses for such a facility as well.

Some thoughts/considerations:

- Perhaps such messages could be flashed in the key hint menu area, between the world panel and REPL panel.  The key hints are not so critical that they can't be hidden for a few seconds.  So something like this:
```    ││▒▒▒▒▒?▒▒▒▒▒???▒????????▒▒?▒▒▒▒▒▒▒????????▒????▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
   ││▒▒?▒▒▒▒▒▒▒▒???▒▒▒▒??????▒▒▒▒▒▒▒▒▒????????▒??????▒▒??▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
───┘│▒▒▒▒▒▒▒▒??????▒▒?▒?▒▒▒▒?????▒▒▒▒???????▒▒??▒▒????????▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒?▒▒▒▒▒▒
───┐└── 0 0 ──────────────────────────────────────────────────────────────── 16 ticks / s ──
   │ You unlocked a new achievement! - Watery Grave
   │ 
   │┌───────────────────────────────────────────────────────────────────────────────────────
   ││ >                                                                                     
   ││                                                                                       
```
- The amount of time the messages persist could be configurable.
- Perhaps the messages could be put in a queue.  If multiple messages are generated at the same time (*e.g.* getting a new entity unlocks both new recipes and commands, or you get an achievement at the same time as unlocking new recipes), we want to make sure each one is displayed for an appropriate amount of time.
- The messages could use our existing Markdown framework.

So in practice this could look something like adding two new fields to the `UIState`: one a queue of messages, and the other a `Maybe (Message, TimeSpec)` which is `Nothing` when no message is being displayed and `Just (msg, t)` when message `m` started being displayed at time `t`.  If the queue is nonempty but there is no currently displayed message, we remove the message from the head of the queue and start displaying it.  When the currently displayed message times out we remove it.

**Comment by kostmo** [comment]
#916?

**Comment by byorgey** [comment]
Oops, thanks, I forgot we already had #916.  I'll close this and add some thoughts to that issue.
