### ISSUE TITLE
Add type synonyms (or just generalize to System Fω)

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#153]
## Problem
I find the tuples not as usable when I can not give a name to my user type.
This would be even more frustrating with sum types (#46).

## Solution
I would like `type` similar to `def`:
```haskell
type usertypename
  = forall typeparam1 ... typeparamn.
  {{some construction using + and *}}
end
```

## Alternatives
Generate the boilerplate with Bash/Python to inline human-readable type definitions.

**Comment by byorgey** [comment]
Agreed, this would be nice indeed.  As a nitpick, I think the syntax should be
```
type usertypename typeparam1 ... typeparamn = 
  {{some construction using + and *}}
end
```
because we are defining a parameterized type, not a synonym for a polymorphic type.  (The latter quickly gets us into rank-n polymorphism, which I am emphatically avoiding.)

**Comment by byorgey** [comment]
Note this would also require adding kinds and kind checking.

**Comment by xsebek** [comment]
> kinds and kind checking

Ouch, a `C-Project` it is then. :disappointed:

**Comment by byorgey** [comment]
> > kinds and kind checking
> 
> Ouch, a `C-Project` it is then. 😞

I mean, we can get away without kind checking if we require type synonyms to always be fully applied, like in Haskell. However, the reason Haskell requires that (type families) doesn't apply here, and especially if we want things like `rec` we are going to want partially applied type synonyms.

`C-Project` is probably justified, but I actually don't think it will be all that bad.=)

**Comment by byorgey** [comment]
So one potentially nice way to do this is to generalize the language to [System Fω](https://en.wikipedia.org/wiki/System_F-omega) and explicitly add `Type`, the type of types, and allow lambda expressions that send types to types.  In other words we could just write
```
def usertypename : Type -> Type -> Type = \a. \b. a + b * () end
```
or something like that.  This is conceptually nice since we no longer need a separate syntax for type definitions at all.  Of course it complicates type checking; I definitely haven't worked out the details yet, but at any rate it's worth considering further.

**Comment by byorgey** [comment]
Possibly relevant: https://pure.tue.nl/ws/files/1931163/9511421.pdf

**Comment by xsebek** [comment]
@byorgey maybe as a stepping stone, how about adding _not prametrized_ type synonyms first?

It would be useful for annotating code and would make the final task a bit easier by introducing the `type` syntax.

**Comment by byorgey** [comment]
If we do generalize to System Fω, doing #1583 first would help a lot (since it would make parsing less ambiguous).
