### ISSUE TITLE
Growth that spreads

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1533]
As a continuation of #1355 (which addressed only fire/combustion), should implement a new `spread` attribute for `Growable` entities.

It was proposed in #1355 that there may be some common base between spreading weeds and fire, but having implemented the latter, there is less overlap than anticipated.

**Comment by xsebek** [comment]
It would be nice to have this in new game options - for example if some spreading entities are blocking, that could be fun/annoying for some players.

**Comment by byorgey** [comment]
I think there need to be some natural way(s) to limit spread.  E.g. perhaps some entity only spreads on top of one particular type of terrain. (See also #742.)  Or perhaps a patch can only grow to a certain size before it stops spreading.  Or perhaps each entity has a counter, and when it spawns a child its childxs counter is one less; when the counter gets to zero no more spread happens.
