### ISSUE TITLE
Sensing position of met robots

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1535]
There are now a lot of entity sensing commands (related: #1171), but a dearth of robot-sensing commands.

Define a new command named `ping` for obtaining relative coordinates to an already met robot (i.e., you have obtained a "reference" to that robot).  This command would be enabled by a `transponder` device (perhaps, required by both robots).

The physical justification/rationale could be that initially meeting "face-to-face" allows exchange of "transponder codes" between friendly robots.

This may call for a new `Robot` attribute that distinguishes between robots that are "friendly" or not.  Perhaps we should not be allowed to `give` items to an unfriendly robot.

## Avoiding "instantaneous communication" loophole

This functionality should have a limited range so that information can not be leaked over great distances.

**Comment by xsebek** [comment]
Maybe the robots that share the same ancestors are friendly?

For other robots, we could have a handshake system where the robots have to mutually meet (within some timeout). A game state map of initiated handshakes in the last tick(s) could be checked when meeting robots and if the handshake is completed we would update those robots friendly set.

**Comment by byorgey** [comment]
Why does it require keeping track of "friendly" robots?  Simply requiring an `actor` value as argument to the `ping` command sounds great.

As for keeping track of friendly robots, see #462 and #506.

**Comment by kostmo** [comment]
> Why does it require keeping track of "friendly" robots?

In the adversarial case, I might not want the base to know the position of my "bad guy" just due to having "met" him once in passing.

Though, perhaps there is a case for an alternate command, `track`, that might allow such a thing despite being an adversary, as if an AirTag were stealthily slipped into their pocket...

**Comment by byorgey** [comment]
Re: limited range, see `RobotRange` and the comments on the `focusedRange` function: https://github.com/swarm-game/swarm/blob/main/src/Swarm/Game/State.hs#L868-L901.

> In the adversarial case, I might not want the `base` to continuously know the position of the "bad guy" just due to having "met" him once in passing.

I guess that makes sense, I'm just trying to prevent unnecessary complexity.
