### ISSUE TITLE
`path` type mentions `entity` which is not a real type

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#1547]
**Describe the bug**
The `Typecheck` module contains `Path -> [tyQ| (unit + int) -> ((int * int) + entity) -> cmd (unit + dir) |]`, but we do not have any built-in type named `entity` (not yet at least; see #455), so it is interpreted as a type variable.  Writing `path` at the prompt displays the type
```
∀ a. unit + int -> int * int + a -> cmd (unit + dir)
```
where you can see that the `entity` has been replaced with a generic quantified type variable `a`.  However, the `path` command is expecting a `text` value, so we can use this to cause a fatal crash by typing e.g. `path (inl ()) (inr 3)` (see the below screenshot).

**Expected behavior**
Presumably the type of `path` should be `(unit + int) -> ((int * int) + text) -> cmd (unit + dir)`.

**Screenshots**
![path-type-bug](https://github.com/swarm-game/swarm/assets/533859/7f123795-a93e-41a3-9c09-679892d72172)

**Comment by xsebek** [comment]
@byorgey will these type variables be already renamed or could we test that their names are reasonable (a, b, c,…)?

**Comment by byorgey** [comment]
@xsebek you mean as a test to make sure this kind of mistake doesn't happen again?    We could test them right after parsing.  *e.g.* perhaps we could add a flag to the parser for types whether it should allow type variable names other than single lowercase letters (since we would not want to restrict what type variables users can write).

We might also want to consider making built-in type names start with an uppercase letter (`Int`, `Text`, etc.).

**Comment by xsebek** [comment]
@byorgey sounds good - could we apply that flag in all our Template Haskell splices? There might be some other place where we write types that would have the same issue. 🤔 

Since swarm is case insensitive I am not sure using uppercase would help or cause more issues. It might be easier to read and would look more like Haskell though.

**Comment by byorgey** [comment]
> sounds good - could we apply that flag in all our Template Haskell splices?

Sure, I'll put together a PR fixing this issue and also adding that check.

Good point re: swarm being case insensitive, I had forgotten that.  So it seems we have 3 choices that I can think of:
1. Leave things as they are.
2. Update all our documentation and examples to use titlecase for types, to recommend it as good style, but keep the parser case insensitive.
3. Change the parser so type names must start with uppercase and type variables must start with lowercase, as in Haskell.

Personally I think I'm in favor of option 3.  Even with option 2, if you make a typo in the name of a type it will be silently treated as a type variable which could be confusing.

**Comment by byorgey** [comment]
Oh, I just thought of an option 4 - keep everything case insensitive, but stop implicitly quantifying type variables, so you must explicitly write a forall when you want a polymorphic type.
