### ISSUE TITLE
Refactor `Capability` type to have a single constructor for common case of "capability to execute command X"

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#1548]
We have many capabilities that are just of the form "capability to execute X" where X is a command.  We might consider refactoring to have one constructor that embeds a command, i.e.
```
data Capability
  = CExecute Const
  | ... etc.
```

This should make the code shorter and cut down on some repetition.  Of course there are still some capabilities which are not of this form.  I have not thought through all the detailed implications of such a change but it seemed worth considering at least.

**Comment by xsebek** [comment]
@byorgey sadly we were too smart and created couple of workarounds using the old system.

Namely the parsing and printing is vexing and I would like to do it right this time. Suggestions welcome in the PR.
