### ISSUE TITLE
Do not suggest commands that require God capability outside creative mode

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#1572]
Players should ideally not get suggestions for not relevant commands.

But they should definitely not get suggestions for commands requiring `CGod` capability unless they are in creative mode.

For example `in` should complete with `inl` but not `instant`.

**Alternatives**

We could also use current robot capabilities or known commands.

**Comment by byorgey** [comment]
Good idea.  We decide what to suggest in `Swarm.TUI.Controller.tabComplete`:

https://github.com/swarm-game/swarm/blob/346f960085bc382a95daa78dba61eb3ab82abe3a/src/Swarm/TUI/Controller.hs#L1243

You can see that we simply suggest all reserved words + variables in scope.  Currently, `tabComplete` does not have enough information to make a more informed decision about which things to suggest, but it is called from a context that has access to the entire `AppState` so it should be easy to thread through the required information.

**Comment by p3rsik** [comment]
Hey! Is there a way to know which commands are creative only? I looked through code and haven't found a way to distinguish them from the usual once.

**Comment by xsebek** [comment]
@p3rsik Sure, its the ones that require a God capability:

https://github.com/swarm-game/swarm/blob/3592b4ea6d84395b47953c1d075f82a88774a5af/src/Swarm/Language/Capability.hs#L290

**Comment by p3rsik** [comment]
Didn't see that one, thanks @xsebek!
