### ISSUE TITLE
Structure recognizer

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1575]
There already exists a mechanism to define structures at the scenario level (#1332).

It would make an interesting game mechanic to have predefined structures that the player robot can assemble out of raw materials (i.e. `place` on the ground according to the structure template), and then be automatically recognized when complete, either to achieve a scenario goal or confer some ability/privilege.

In a sense, these would be like "recipes" but with a spatial component.  A subset of the structure template definitions in a scenario file could be marked as "participating" in recognition, perhaps by virtue of associating a "reward" or "output".

# Philosophical considerations

As a programming game, a particularly appealing aspect of Swarm is the spatial dynamism of seeing one's programs affect the world.  

Besides programming, Swarm gameplay involves "spatial activity" and "stationary activity".  Spatial activity entails movement and is visually interesting.  As examples:

* exploration, farming, and hauling resources place-to-place (i.e. in a resource pipeline) are spatial activities
* crafting (the `make` command) is a stationary activity
* subsequent to exploration, mining itself (i.e. the `drill` command) is a stationary activity.

Construction of structures would be another general game mechanic involving "spatial activity".  It can integrate with the classic "open world" mode without requiring the hermetic contrived environment of standalone scenarios.  This game mechanic could apply to both large scale structures (e.g. buildings like power plants) and small structures (perhaps described as "runes", encompassing tetrominoes or other pixellated glyphs).

## As programming challenge

Repeating patterns or symmetry within single structures provide an opportunity for players to craft parsimonious construction programs.  Across multiple structures, one may attempt a compact tiling of structures on the plane, or (if there were mutual exclusivity constraints on inventory occupancy, see #944) optimizing a construction assembly line.

# Technical considerations

Programming the word search scenario (#999) provided a taste of the complexity of recognizing "structures" in swarm-lang.  For performance, let alone the complexity, structure recognition would require built-in support.

<table>
<tr><th>Reference structure</th><th>Completing one row</th><th>Partial assembly</th><th>Nearly complete</th></tr>
<tr><td>

```
aBaBaBa
BxxoxxB
axoooxa
BxxoxxB
aBaBaBa
```

</td><td>

```
.......
Bxxoxx.
.......
.......
.......
```
</td><td>

```
aBaBaBa
BxxoxxB
.......
Bxxo.xB
aBaBaBa
```

</td><td>

```
aBaBaBa
BxxoxxB
a.oooxa
BxxoxxB
aBaBaBa
```

</td></tr>
<caption>Construction progress</caption>
</table>

## Search triggering

The ideal gameplay experience would be that a structure is instantly recognized once the player `place`s the last piece, no matter where within the structure that is.

A callback would be set up [here](https://github.com/swarm-game/swarm/blob/346f960085bc382a95daa78dba61eb3ab82abe3a/src/Swarm/Game/Step/Util.hs#L70) to scan for structure matches when an item is placed.

## Matching algorithm

Two matching steps, possibly utilizing different strategies, may be used to identify the constructed 2D structure.

### Row matching

In the first stage, perhaps [`AhoCorasick`](https://hackage.haskell.org/package/AhoCorasick) could be used.  That library searches for multiple "needles" simultaneously in one "haystack".  Each needle (or "key"), and the haystack itself, is a list of "key symbols".

Upon scenario initialization, each "row" constituting each participating structure template would be [added to the searcher state machine](https://hackage.haskell.org/package/AhoCorasick-0.0.3/docs/Text-AhoCorasick.html#v:makeStateMachine).  Rows of all participating structure definitions are the "needles", while the "haystack" is the horizontal world span extending `N` cells both to the left and right of the placed entity, where `N` is `max(all structure row lengths)`.  The "key symbols" don't necessarily have to be textual characters; they could be actual `entities`.

As an optimization, an entity-keyed `Map` of different [`StateMachine`s](https://hackage.haskell.org/package/AhoCorasick-0.0.3/docs/Text-AhoCorasick.html#t:StateMachine) could be precomputed, each including only the rows which contain a given entity.The right and left offset `N` could also be precomputed and keyed by entity, so that we don't have to examine as many neighboring cells.

Each "match" returned by [`findAll`](https://hackage.haskell.org/package/AhoCorasick-0.0.3/docs/Text-AhoCorasick.html#v:findAll) would be added to a cache of "partial structure candidates" stored in the world's state (or the `GameState`, keyed by subworld), keyed by coordinates.  Perhaps [`IntervalMap`](https://hackage.haskell.org/package/fingertree-0.1.5.0/docs/Data-IntervalMap-FingerTree.html#g:2) would be used for this data structure.

### Structures from rows

Matches against a known structure's row would trigger a second stage of matching in the vertical direction.  Perhaps this stage could also use AhoCorasick, but this time the "key symbols" are entire rows of a structure.

Instead of querying world cells directly, the search would be performed entirely within the "partial structure candidates" cache, among rows that are aligned vertically with the just-placed row candidate.  Again, the search would extend `M` rows both above and below the current row, where `M` is `max(all structure heights)`.

A complete structure may then be recognized, and possession granted to its creator.

A cell can participate in only one structure at a time, so the new structure's constituent rows are evicted from the "partial structure candidates" cache.

## Orientation

The method described above requires that the constructed orientation matches the structure definition.  It could be generalized to orientation-independence by adding the three other possible orientations to the searcher.

## Structure morphology

The structure shapes that we allow will depend on the matching algorithm.

* Should the structure recognition templates allow "transparent" cells?  If so, should the structure be required to be "convex"?
* Should the structure templates have a minimum length (in at least one dimension)?

<table>
<tr><th>Convex template with transparent cells</th><th>Non-convex template</th></tr>
<tr><td>

```
   x     
  xxx    
 xxxxx
xxxxxxx
 xxxxx
  xxx   
   x
```

</td><td>

```
xx  xx
 xxxx
 xxxx
xx  xx
```

</table>

It might be possible to implement matching in AhoCorasick that accommodates "transparent" cells with an `Ord` instance that is always [`EQ`](https://hackage.haskell.org/package/base-4.18.1.0/docs/Prelude.html#v:EQ) (i.e. it is a "don't care" cell that is always a match).

### Ownership

Upon placing the last piece, the placing robot should be granted "ownership" of and is conferred the privileges of that structure.

This could facilitate an adversarial gameplay mechanic, perhaps where players take turns to place pieces (like a reverse [Chomp](https://en.wikipedia.org/wiki/Chomp)) and try be the last placement, or even one player (perhaps a system robot) does most of the construction and another (the player) swoops in to place the last piece.

# Other enhancements

Incidentally,  #1271 would make structures with walls look nice.

**Comment by xsebek** [comment]
I like the detailed proposal! 👍 In particular I imagine creating portals could be fun and a add a lot to the gameplay.

As usual I am worried a bit about performance and complexity, so here are a few nitpicks:

---
The caching seems like a lot of overhead. Could we use some simpler and rarer trigger?
Presumably the robot knows what it is doing and could activate or take ownership of the structure.

For example in Minecraft the portal is activated by putting fire in it, which is much rarer than placing blocks.

I seem to remember that you optimised the gated paddock scenario to only check the paddock structure when the new entity connected with another. This seems like the same idea - paying once vs paying all the time.

---
As a note, the search library has almost no dependencies, but does not seem to be maintained. 

Your algorithm makes sense, but you do not discuss the length and number of rows. I assume the maximum structure size in all directions could be used? 🤔 

---
Do we have structures stored already in game? I assume we would need to track when they stop existing as well.
