### ISSUE TITLE
System robot should recognize lock combo in single tick

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1598]
In #1591, the system robot re-checks the lock for the correct combination "instantly" upon every change to the lock members.

However, if the player "toggles" a member of the lock twice immediately in succession, such that the correct combination is "skipped over", the system robot will not detect that the correct combination had been reached.  See https://github.com/swarm-game/swarm/pull/1591#issuecomment-1772127739.

It may require some investigation as to why the `instant` command is not sufficient to perform the detection in a single tick.

**Comment by byorgey** [comment]
The first step is probably to try to come up with a minimal example that reproduces the issue.  Single-stepping the debugger might help too --- though I'm not sure whether that lets you step through system robot code.
