### ISSUE TITLE
Cannot scroll in goals screen (Bind notation window)

### ISSUE THREAD

**Issue by simplyclever** [swarm-game/swarm#1603]
**Describe the bug**
In tutorial when I complete one subtask next one is impossible to scroll. Arrows and PgDn/PgUp only swich tasks.
Mouse scroll is not working too.

**To Reproduce**
I've build this using dockerfile:
```
FROM ubuntu:bionic

RUN apt update 
RUN apt install -y --no-install-recommends git curl ca-certificates unzip

WORKDIR /swarm

RUN curl -sL https://github.com/swarm-game/swarm/releases/download/0.4.0.0/swarm-Linux >> ./swarm
RUN curl -sL https://github.com/swarm-game/swarm/releases/download/0.4.0.0/swarm-data.zip >> ./swarm-data.zip

RUN chmod +x ./swarm
RUN mv ./swarm /usr/local/bin
RUN mkdir -p ~/.local/share/swarm/
RUN unzip ./swarm-data.zip -d ~/.local/share/swarm
```

Then run it: `docker run -it <image> bash`
I've started Tutorial and in mission with Artifact I've problem.

**Expected behavior**
I want to scroll down to see what is written below (see screenshot).

**Screenshots**
<img width="538" alt="image" src="https://github.com/swarm-game/swarm/assets/84372791/aa00e5f4-0bf2-4f57-98d9-ffa4e839c374">

**Additional context**
I use:
Windows terminal - 1.18.2822.0
PowerShell - 5.1.22621.2428
Windows 11 - Version	10.0.22621 Build 22621
Docker - v4.24.2 (with WSL)

**Comment by byorgey** [comment]
Thanks for the report!  I *think* you can hit Tab to switch focus to the text, and then you should be able to scroll.  However, even if I'm right about that, clearly the UI could be improved. Maybe we should put focus on the text pane by default?  What else do you think might help?

**Comment by simplyclever** [comment]
Tab works! Yes, default focus on text should do the work 😄

**Comment by byorgey** [comment]
Ah, it looks like in https://github.com/swarm-game/swarm/commit/b01406237 we also added a footer with a hint to use Tab, which should help once it is released.

Making the text focused by default would clearly be the right default in this case, but in other cases (complex scenarios with multiple non-linear goals) it would not be.  Maybe we should focus on the text IF the text is larger than the dialog, and focus on the goal list otherwise?

**Comment by simplyclever** [comment]
Note should be fine. No need to add default. Thanks 😄

**Comment by byorgey** [comment]
OK, in that case I will close this, but feel free to re-open if you think there's something else that could be improved here.  Thanks again for the report.  We hope to put out an 0.5 release soon which will have this fix (+ other things).
