### ISSUE TITLE
Migrate to brick 2.0

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#1607]
vty 6.0 and brick 2.0 support windows! 🚀 So we could too and close #53

**Comment by jtdaugherty** [comment]
We might have a wrinkle or two left to work out, but heavier users of `vty` like `swarm` will help us surface remaining issues. Keep me and @chhackett in the loop!

**Comment by chhackett** [comment]
Hello,
I updated the cabal and App module to allow for running on Windows. I did some playtesting, and I didn't find any rendering or gameplay issues. All the keyboard commands seem to behave well. I've addressed comments on the PR.

Keep in mind that right now only command line and Powershell terminals are supported.

Btw, what a neat game!

**Comment by chhackett** [comment]
Actually, I do see 2 issues so far:
- mouse mode isn't working for some reason
- program expects the data files to be present in the C:\Users\Chris\AppData\Roaming\swarm\data directory. Or is that a feature? Not sure, haven't played it before...

**Comment by chhackett** [comment]
Disregard my previous comment about mouse mode. I did not realize mouse mode was only enabled for some menus. For example, the main menu doesn't respond to mouse clicks, but other UI elements do. So mouse mode does work.

**Comment by byorgey** [comment]
> program expects the data files to be present in the C:\Users\Chris\AppData\Roaming\swarm\data directory. Or is that a feature? Not sure, haven't played it before...

That's normal.  You can get the latest data files from https://github.com/swarm-game/swarm/releases under swarm-data.zip.  That actually reminds me that if we are updating to support Windows we should probably include changes to https://swarm-game.github.io/installing/ to mention the proper instructions.  But we can do that separately.
