### ISSUE TITLE
Add built-in `undefined` and/or `error` primitives

### ISSUE THREAD

**Issue by RustemB** [swarm-game/swarm#161]
**Describe the bug**
Formatter doesn't format if variables does not exist

**To Reproduce**
Just format any file with not declared variable

**Expected behavior**
It must format anyway

**Additional context**
It's important for not implemented but in future variables

**Comment by xsebek** [comment]
I do not understand what exactly is "future variable". Do you mean lambdas? (`def id = \x.x end`)

If you mean "unbound variables", then that is currently a very sensible requirement, as `run` replaces your environment:
- file "a.sw":
  ```haskell
  say x
  ```
- running `swarm format a.sw`:
   ```
  a.sw:1: Unbound variable x
  ```
- in REPL:
  ```haskell
  > def x = "hi" end
  > run "a.sw"
  base: run: Error in a.sw
   1: Unbound variable x
  ```

**Comment by RustemB** [comment]
For example
I'm implementing some function, in this function I typed some undefined function or variable
then I want to format it to check what I wrote
then I'll move forward and implement thous undefined funcs and vars

**Comment by TristanCacqueray** [comment]
Actually the `format` command does not format at the moment, it simply echo back the code when it is valid. Though I think it is expected that the `format` command fails when the code is not valid.

It seems like what we could use instead is a special `undefined` placeholder value that would be valid for any type.

**Comment by xsebek** [comment]
@TristanCacqueray by the use you mean defining the variable as `undefined` in the file?
- in the previous example in file "a.sw":
  ```haskell
  x = undefined
  say x
  ```
If so, then maybe we could rename the Issue since `format` does not format :smile:

**Comment by xsebek** [comment]
@byorgey what do you think about adding a new constant `undefined : a`?

I think it would also need a new `VUndefined` value which we would catch in `badConst` and raise a `User` exception.

We could also go with `error : str -> a` and let users do `def undefined = error "undefined" end`.

**Comment by byorgey** [comment]
@xsebek makes sense to me.  We could add both.

I don't think there needs to be a new `VUndefined`.  We just immediately raise a `User` exception when evaluating `error` or `undefined`.
