### ISSUE TITLE
Add Windows build to CI

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#1622]
> I forgot it was so linux specific, we can look into it separately - let's just add an Issue for Windows CI.

_Originally posted by @xsebek in https://github.com/swarm-game/swarm/issues/1617#issuecomment-1811006130_

**Comment by byorgey** [comment]
Note that [GitHub Actions does have Windows runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners), but `haskell-ci` (which we currently use to auto-generate our CI action) [does not support it](https://github.com/haskell-CI/haskell-ci/issues/199).

**Comment by xsebek** [comment]
I wonder if we could use something simpler than Haskell-CI - Pandoc uses `ghcup` and has Windows and Mac support:

https://github.com/jgm/pandoc/blob/2b60b1a1bc062f37174cb1c29178c5aa02f7c651/.github/workflows/ci.yml#L168-L177

**Comment by byorgey** [comment]
Yes, good idea, I think what we should do is just make a separate workflow with a simple Windows build, modeled on something like the above.  It won't be as sophisticated as the `haskell-ci`-generated workflow, but it will still be better than nothing.

**Comment by nitinprakash96** [comment]
I think we can also consider directly using `haskell-actions/setup` actions on a windows runner to have ghc and cabal installed. Here's what we do in one of the libraries https://github.com/Holmusk/elm-street/blob/d8fc99b8be419525dd9d266b904422cfc13b2e87/.github/workflows/haskell-ci.yml#L26-L53
