### ISSUE TITLE
Fix or deprecate `stack build`

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1624]
Since #1617, `cabal build` works but `stack build` no longer does.

Do we believe that `cabal` has parity with `stack` for the purposes of our project?  Then we should scrub/replace references to `stack` in our scripts and documentation.

**Comment by byorgey** [comment]
I don't think we should be so quick to get rid of `stack`.  I use it for building swarm, and it's quite useful because anyone wanting to build swarm can be sure they will get a reproducible build, without worrying about whether they have the right version of GHC installed.

**Comment by byorgey** [comment]
I didn't realize #1617 broke the stack build, but I will happily fix it.

**Comment by kostmo** [comment]
See https://github.com/swarm-game/swarm/pull/1798#discussion_r1586949897 for a demonstration of a `stack` bug regarding rebuilding a target that does not occur with `cabal`:

> Try the following:
> 1. Add a newline to the end of `src/swarm-tournament/Swarm/Web/Tournament/Validate.hs`
> 2. Run `stack build swarm:exe:swarm`
> 3. Observe that it recompiles `swarm-tournament`, despite that library not being a dependency of the `swarm` executable.
> 
> Now do the same cycle, but with `cabal build swarm:exe:swarm` instead, and observe `Up to date` is printed.
