### ISSUE TITLE
Type parentheses dropped in markdown rendering

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1625]
Given the following markdown text (from [this `.yaml` file](https://github.com/swarm-game/swarm/blob/f9ef0094f0bfbe57d589e44a355446a54566d4bd/data/scenarios/Fun/horton.yaml#L55)):

    `path : (unit + int) -> ((int * int) + text) -> cmd (unit + dir)`

It is rendered as:
![Screenshot from 2023-11-14 16-52-38](https://github.com/swarm-game/swarm/assets/261693/21b971f0-af3e-410a-87e4-87b66207eedd)

The dropped parentheses make it unclear whether the second argument is supposed to be a product type within a sum type `((int * int) + text)` or a sum type within a product type `(int * (int + text))`.

**Comment by byorgey** [comment]
This is not a bug; by convention * binds tighter than + (just like with arithmetic).  But I agree it can be a bit hard to read. We can certainly consider e.g. giving them the same precedence when pretty printing.

**Comment by byorgey** [comment]
It can even be hard to read when `->` is mixed with `+` or `*`, e.g. compare `unit + int -> int * int -> cmd unit` to `(unit + int) -> (int * int) -> cmd unit`.  Maybe we should just always use parentheses around `+` and `*`.
