### ISSUE TITLE
Children of system robots do not bypass device requirements

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1664]
Normally, system robots are not required to possess devices in order to use any particular command.

However, a robot built by a system robot becomes subject to the requirement (see worker bee code in #1599).

Also related: #1430

**Comment by kostmo** [comment]
> Do you have a simple minimal example to reproduce this behavior?

Test case created in #1677.

**Comment by byorgey** [comment]
A random thought I just had while reviewing #1677 : it might have something to do with the dynamic checks we do when `build`ing child robots.  We should look into the logic used to determine which devices need to be installed when executing `build`.
