### ISSUE TITLE
Give `view` a limited broadcast range

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#17]
_This issue used to be about adding an `antenna` entity to enable `view`, but see comments below for some reasons why I no longer think we should do that._

I'm thinking there can be an "Antenna" entity.

* An antenna provides a `broadcast` capability, with a corresponding `broadcast` command.
* Only robots (besides `base`) which have executed `broadcast` can be viewed with the `view` command.
* The recipe for an antenna could involve, say, 5 copper wires, + maybe something else?  Depends on how hard it should be to obtain early in the game.  It would probably be pretty helpful for debugging etc. so probably shouldn't be too hard to get.
* Perhaps later, an antenna can have a limited broadcast range, and there can be more difficult ways to craft more powerful antennas.  But probably for a first crack we can just make antennas have an unlimited range.

**Comment by Anrock** [comment]
Would also be nice to have API for antenna to allow some semi-autonomous robots maybe.

**Comment by byorgey** [comment]
Hi @Anrock , thanks for the idea!  However, I'm not sure I understand what you mean.  What kind of API do you imagine?  And can you explain what you mean by "semi-autonomous"?

**Comment by Anrock** [comment]
> What kind of API do you imagine?

In Colobot there were "Exchange posts" buildings, where robots could store/retrieve info. API was basically a wrapper for string-string map, like `store("topic", "some value", distance)`. When executed it would put "some value" as value for "topic" key in all exchange posts in `distance` radius. Same for `retrieve` command.

So if we replace "exchange post" with "any entity with antenna" that would go as API for swarm. Distance argument in Colobot was there since every robot had depletable battery and distance affected how much energy was spent for a broadcast, we can drop that since bots seems to have indefinite batteries in swarm.

Further improvement of API could include storing something more interesting than strings for values, for example scan data or functions. Some kind of callback/notification mechanism when some broadcast is received seems to be good to have too.

> And can you explain what you mean by "semi-autonomous"?

If understand correctly, in Swarm once robot is built it will execute its program and there is no way to alter it or control robot dynamically. With antennas you can write something like that by broadcasting commands from base and writing an interpreter on bot side to execute those commands. Using base REPL it can be done interactively.

**Comment by byorgey** [comment]
Ah, now I see what you mean.  Yes, inter-robot communication is absolutely something we want!  It should definitely require an antenna but probably more stuff as well.  The antenna described in this issue is for a capability you should be able to get pretty early on, whereas inter-robot communication seems like a much more powerful feature that should only be obtained deeper into the game.  Anyway, I've created a new issue to track this idea: #94.

**Comment by byorgey** [comment]
For limited broadcast ranges, I had a fun idea: instead of just being a sharp cutoff at a specific distance, there could be a gradual falloff in signal strength, such that when you `view` a robot, the farther away it is, the fewer grid cells you can see.  Like each grid cell has a probability of being visible, with the probability depending on the distance.  Invisible grid cells would just be rendered as blank.  So an antenna would have two critical distances d1 and d2: closer than distance d1, everything is visible with 100% probability; outside d2, cells are visible with 0% probability; between d1 and d2 the probability falls off according to some function.  So if you `view` a robot and it is moving away from you, you would see your view of the world develop more and more "holes" or "static" until you finally can't see anything.

Concretely, for each cell we could generate a pseudorandom number which is a deterministic function of its coordinates, uniformly distributed between 0 and 1 (i.e. via some kind of hash function on the coordinates); we display the cell or not depending on how its number compares to the visibility probability.  This means the pattern of visible and invisible cells would remain stable as the robot moves around etc.  Or, if we want to simulate more dynamic "static", we could e.g. have a counter which goes up once per second or something like that, and include the current counter value as an input to the hash function along with the coordinates, so that the pattern changes every second (having the static pattern change every *frame* would probably be too much).

**Comment by byorgey** [comment]
I intentionally did not include this issue in the roadmap for an alpha release (https://github.com/orgs/swarm-game/projects/1) --- I don't think it's critical, and it would actually make the game harder.  Perhaps we might consider having this be part of some kind of "hardcore" mode.

**Comment by byorgey** [comment]
So as of #483 we have a robot list panel.  At this point I think we should just say that standard robot chassis have a basic antenna built in, and not require installing them separately for purposes of viewing robots in the list or executing `view`.  However, I do still think `view` should have a range limit (just as the robot list does).  And perhaps one can construct more powerful antennas to get a bigger range.

**Comment by byorgey** [comment]
This is now the least-recently-edited issue, and also one of our oldest, and I think it shouldn't be too hard to tackle now.  Here's my current plan: (1) make visibility drop off with distance when `view`ing.  (2) When an `antenna` is installed somewhere, make the viewing range larger.  Maybe installing an `antenna` on both the base and the robot being viewed makes the range even bigger than just having one `antenna`.

**Comment by kostmo** [comment]
Terminology for reference: [Fog of war](https://en.wikipedia.org/wiki/Fog_of_war#In_video_games)
