### ISSUE TITLE
Make sure all doctests run in CI

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#1728]
I verified manually that the doctests are now passing, but it looks like our CI is not running all of them.  I will open a new issue.

_Originally posted by @byorgey in https://github.com/swarm-game/swarm/pull/1724#issuecomment-1890800604_

**Comment by nitinprakash96** [comment]
Is this really the case? I tried running `cabal-docspec` with `--verbose` flag and all the doctests run fine. There are 90 doctests to run and I think that's what run in CI too.
```shell
➜  swarm git:(main) ✗ ggrep -r -- "-- >>>" . | wc -l
      84
➜  swarm git:(main) ✗ ggrep -r -- "--   >>>" . | wc -l
       6
```

**Comment by byorgey** [comment]
Hmm, maybe you're right.  I don't remember why I originally thought that not all of them were running.  I guess we can close this issue.
