### ISSUE TITLE
Fatal error: Bad machine state in stepRobot: FApp of non-function

### ISSUE THREAD

**Issue by kabuhr** [swarm-game/swarm#1796]
There appears to be a scoping problem with `<-` bindings that shadow pure bindings.  The following commands on the base console generate a fatal "FApp of non-function" error:
```
> def x = \x.x end
> def foo = x <- return 0; noop end
> foo
it0 : unit = ()
> return (x 42)
it1 : int = 42
> foo; return (x 42)
[Fatal error: Bad machine state in stepRobot: FApp of non-function ∪· E· (return (0 ◂42▸))
```

**Comment by kabuhr** [comment]
Looks like this is a duplicate of issue #681.

**Comment by byorgey** [comment]
@kabuhr Yes, I think you're right that this is #681, but I appreciate the report!  I think I know how to fix it, but unfortunately it is rather complex and I can't really give an estimate on when it will happen.
