### ISSUE TITLE
Recommend `cabal` instead of `stack`

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#1820]
See discussion at https://github.com/swarm-game/swarm/pull/1798#discussion_r1578765506 and https://github.com/swarm-game/swarm/issues/1624#issuecomment-2092836195 .

**Comment by kostmo** [comment]
Filed https://github.com/commercialhaskell/stack/issues/6569

**Comment by byorgey** [comment]
Independently, it also seems that recently I haven't been able to get emacs + HLS to work at all with stack, but it works great with `cabal`, so I have personally switched away from using `stack` as well.
