### ISSUE TITLE
Add "Login with GitHub" to swarmgame.net

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1847]
Need authentication to attribute scenario and solution uploads to real people.

Tutorial: https://docs.github.com/en/apps/creating-github-apps/writing-code-for-a-github-app/building-a-login-with-github-button-with-a-github-app

**Comment by kostmo** [comment]
@byorgey, the first step would be for you to grant me permissions in the `swarm-game` org to create a GitHub app: https://docs.github.com/en/organizations/managing-programmatic-access-to-your-organization/adding-and-removing-github-app-managers-in-your-organization

Then I will follow [these instructions](https://docs.github.com/en/apps/creating-github-apps/writing-code-for-a-github-app/building-a-login-with-github-button-with-a-github-app).

**Comment by byorgey** [comment]
@kostmo , done!
