### ISSUE TITLE
Update editor language modes for uppercase types

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#1883]
All the editor modes (e.g. `swarm.el` for emacs, etc.) still refer to types with lowercase names, which means syntax highlighting won't work anymore.  This should have been part of #1583 but I didn't think of it at the time.

**Comment by nitinprakash96** [comment]
I believe the problem is more than that. If I load `swarm-mode` locally from path, both `int` and `Int` gets highlighted. The current config doesn't respect case sensitivity.
I have a solution in mind along with other simplifications to the elisp code. Let me see if I can make it work.

**Comment by byorgey** [comment]
Ah, that makes sense, because the language wasn't case-sensitive before.

**Comment by nitinprakash96** [comment]
I believe this is remaining only for VSCode (I'm not sure though, I don't really know how to setup the requirements in vscode). Emacs and Vim should be up to date.

**Comment by byorgey** [comment]
Actually, it looks like VSCode was updated too, in #1895:

https://github.com/swarm-game/swarm/blob/1cbc22e2dea52c0aa153e414bce184432c1a3b93/editors/vscode/syntaxes/swarm.tmLanguage.yaml#L201

I'm going to close this issue.
