### ISSUE TITLE
Delete `stack.yaml`

### ISSUE THREAD

**Issue by noahyor** [swarm-game/swarm#1960]
Stack currently cannot compile swarm on windows and I think it is currently not recommended.

However, we still have a stack.yaml, which is very annoying for me because VS Code defaults to stack, so I have to delete it manually every time I pull, and then explicitly not stage the deletion when I commit.

**Comment by nitinprakash96** [comment]
I think this should be fine. Because deleting stack.yaml has no effect on compilation whatsoever. And on loading HLS either.

**Comment by noahyor** [comment]
Yes! I would like to make a PR.
