### ISSUE TITLE
Map editor shortcut conflicts with move-to-end-of-line shortcut

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#1962]
It has happened to me several times that while in creative mode, I have hit Ctrl-E to move to the end of the REPL input and was susprised when it opened up the map editor instead.  I think we should pick a different keyboard shortcut for the map editor.

**Comment by noahyor** [comment]
What do you think the new shortcut should be?

**Comment by byorgey** [comment]
I'm not sure, it's always tricky coming up with keyboard shortcuts.  It has to be (1) a combination that is passed along by terminals (for example `Ctrl-M` probably doesn't work since on a lot of terminals that is turned into a newline), (2) something that is not already in use for something else, and (3) ideally something mnemonically related to the map editor.

**Comment by xsebek** [comment]
We should use the keymap feature from Brick, and then everyone can customize it. 🙂 #523
