### ISSUE TITLE
Update release action

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#1970]
I checked on the `Release` action (https://github.com/swarm-game/swarm/actions/workflows/haskell-release.yml) and it looks like it needs a few updates:

- Use GHC 9.8 to build instead of  GHC 8.10
- Check whether any imported actions should use a more recent version
- Anything else?

**Comment by nitinprakash96** [comment]
We should also check for deprecated commands. Eg: `set-output` is deprecated https://github.com/swarm-game/swarm/blob/37617e091033466a864d4caa69ba529d94d2ea9e/.github/workflows/haskell-release.yml#L161

Refer: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Fix: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
