### ISSUE TITLE
Add a `CustomName Text` Constructor to `Name`

### ISSUE THREAD

**Issue by noahyor** [swarm-game/swarm#1976]
In my quest to create [Termite](https://github.com/noahyor/termite), I need to be able to create a Brick Editor. However, this requires a name constructor to be provided, and I cannot use my own type, or else Swarm Embedding will not function correctly. I also cannot use one of Swarm's because it is undefined which you will get if you try to perform a widget lookup by name, which will also break Swarm.

I propose that we add a `CustomName Text` constructor to the `Name` type (in Swarm.TUI.Model.Name) to allow external/custom widgets to be made.

**Comment by byorgey** [comment]
Sounds reasonable to me.  Pull requests welcome!

**Comment by noahyor** [comment]
There we go!
