### ISSUE TITLE
Consider making the `log` command intangible

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#1991]
Currently, the `log` command is specified as a tangible command, meaning that robots can only run it at most once per tick.  However, I am not sure why we decided this in the first place.  The general idea is that tangible commands are ones which could have an observable effect to other robots, but there is no way for robots to observe some other robot's log entries (not without doing something like `salvage` first).  The one exception is that if you `view` another robot you can see its log, but that is only observable within the UI, and you cannot programmatically react to it.

**Comment by xsebek** [comment]
I suppose it came over from `say` where you can `listen`. 🤔

It seems reasonable to want to log and not introduce timing problems, so I am all for this change. 👍
