### ISSUE TITLE
Remove redundant `transformers` dependency

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#1993]
In a couple different places in `swarm.cabal` we have `transformers` listed twice with different version bounds:
```
    transformers >=0.5 && <0.7,
    transformers >=0.5.6.2 && <0.6.2.0,
```
Does anyone know why this is?  Is there a specific reason we need version 0.5.6.2?

Relatedly, if we can get away with requiring `0.6`, then we can close #1151.

**Comment by nitinprakash96** [comment]
Builds fine with just `transformers >=0.6 && <0.7`. I think we can get rid of the 0.5.6.2 dependency.
And as for the linked issue, I see that we're already using `hoistMaybe`. So I think that can be closed as well.

**Comment by byorgey** [comment]
No, the linked issue still requires a small bit of work.  I added a comment there to clarify.  Yes, we are using `hoistMaybe` in some places, but at the moment it is defined in `Swarm.Util`.  The idea is that if we depend on `transformers >= 0.6` we can switch to using the one defined there.

**Comment by nitinprakash96** [comment]
Ah now I see what you mean. Thanks for clarifying 👍
