### ISSUE TITLE
Standardize on place for Swarm hangout/chat

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#2009]
For a long time we've had an IRC channel, `#swarm` on Freenode.  It used to be quite active in the first year or so, and it was a fun and helpful way to hash out designs, for users to be able to ask for help, etc., but recently I'm pretty much the only one of the active developers who hangs out there.  I still personally like IRC, but I know it's not very mainstream and I'm not wedded to any particular platform.  I'd rather have something that people will actually use.

So, thoughts?  Should we set up a Discord server? Slack?  Some other cool thing I don't know about?  Or should we just double down on IRC?

**Comment by byorgey** [comment]
> That being said, I think slack does allow retaining more than 10k or 90 days of msgs on it's free tier.

I tried looking it up and I don't think this is true: https://slack.com/pricing/free  Maybe it's Discord you're thinking of?  I'm having trouble finding clear information about what features are included in the Discord free tier.

**Comment by byorgey** [comment]
Apparently there is also https://www.linen.dev/ which looks like some kind of open-source alternative to Slack/Discord which is supposedly free for open-source communities.

**Comment by byorgey** [comment]
Reading more stuff online I am getting the impression that Slack is very corporate-oriented and generally people prefer Discord's free tier over Slack's.  I think I'm going to veto Slack.

**Comment by nitinprakash96** [comment]
Oh I didn't know about linen. But reading about, it does seem pretty good. +1 from me for that.

**Comment by byorgey** [comment]
@xsebek @kostmo any thoughts/preferences?

**Comment by kostmo** [comment]
Discord sounds good to me.

**Comment by xsebek** [comment]
Discord seems like a good choice for a game. 👍

**Comment by xsebek** [comment]
There is also Mattermost which has a brick client. Could be fun to use brick to chat about brick game. 😁

**Comment by byorgey** [comment]
"Accelerating mission-critical work in defense, government, and critical infrastructure enterprises"  yes, that sounds exactly like Swarm... :grin: 

OK, let's go with Discord.  (If we want we could also set up a linen.dev mirror of the Discord to make it more easily searchable.)  Anyone want to volunteer to set it up?

**Comment by byorgey** [comment]
I set up a Discord server at https://discord.gg/kp8MuSgkPw !

**Comment by byorgey** [comment]
Before we close this we should make sure to update documentation etc. with links to Discord instead of IRC.
