### ISSUE TITLE
Cursor mode in world panel

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#203]
One very annoying aspect of the early game is the need to precisely measure distances to various objects so you can send robots to fetch them: without any kind of conditionals or repetition, the only thing you can do is specify an exact distance to travel.  Of course there are clever things you can do besides squinting at your screen and trying to carefully count, such as sending robots to measure distances for you etc. But I wonder if it would be nice to add a "cursor" mode to the world view, where you can move a cursor around the world and see the coordinates of the current location of the cursor (and maybe even e.g. paste the current coordinates into the REPL when you hit Enter).

**Comment by byorgey** [comment]
Ah, yes, brick does have mouse support, that would be handy too.

**Comment by byorgey** [comment]
I tried briefly and was unable to figure out how to use the mouse support... it doesn't look like it should be that hard though, I was probably just missing something simple.  In theory it looks like you call the `clickable` function on a widget to make it receive mouse clicks, and then you handle mouse events in the `handleEvent` function.

**Comment by TristanCacqueray** [comment]
Perhaps it's an issue with your terminal emulator? You can check for mouse events support by running `echo -e "\e[?1003h"`, then clicking on the window should show the raw event.

**Comment by byorgey** [comment]
Wow, what kind of voodoo escape sequence is that!  Anyway, when I try it, there are lots of random characters getting printed out as I move my mouse and click, so it seems like the terminal is indeed detecting mouse events.

**Comment by byorgey** [comment]
I just filed https://github.com/jtdaugherty/brick/issues/366 .  Does the brick mouse demo work for anyone else?
