### ISSUE TITLE
VSCode plugin release to go with swarm 0.6

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#2053]

**Comment by xsebek** [comment]
There is some issue with pushing to the VSCode plugin repository:
https://github.com/swarm-game/swarm/actions/runs/10049297138/job/27775053278

**Comment by xsebek** [comment]
Done!

* https://open-vsx.org/extension/swarm-game/swarm-language
* https://marketplace.visualstudio.com/items?itemName=swarm-game.swarm-language

Thanks, @kostmo, for adding my personal account to the swarm org on VSCode marketplace - I made it with my old account and needed to regenerate the Token:
https://code.visualstudio.com/api/working-with-extensions/publishing-extension#get-a-personal-access-token
