### ISSUE TITLE
UI improvement

### ISSUE THREAD

**Issue by jrvieira** [swarm-game/swarm#206]
The current 3 pane UI is cumbersome. Users often report typing in the wrong pane which is frustrating and error prone. Screen usage can also be optimized.

### Better key based navigation

Navigating the interface should be intuitive and immediate. The more frequent an action is expected to be taken, the less painful we need to make it for the user. Single key mode change should always be a guarantee (for instance, currently there are situations where we force user to either press Tab twice or use a modifier combination, which is bad).

### Collapsable panes

Panes like the inventory could be collapsable. The UI should leave space for future complexity.

### Unobtrusive REPL

The REPL doesn't need to be a pane nor does it need to be visible while inactive. It can be activated with a convenient key press such as `/` or `Enter` before each command, or alternatively we could demand that the user closes the REPL before continuing using the rest of the interface. I can't think of any reason for it to occupy more than 1 line on screen (except when inserting multiline commands) so i propose that it stays a single line (plus borders) at bottom of the screen that grows when multilining and disappears when inactive.

**Comment by byorgey** [comment]
Thanks for the ideas!  Yes, I often end up typing in the wrong pane too.  Something definitely needs to be improved.

Having the REPL occupy only one line makes sense, that would be an easy change.

Should the REPL be focused by default, and require a special key press to do anything else in the UI?  Or should a special key press be required to open the REPL, as you suggest? I kind of feel like I personally would prefer the former but I am actually not sure.

**Comment by xsebek** [comment]
Some thoughts:
- related is #134 
- collapsible panes sound great, but would need a special brick widget to replace them when collapsed (no idea how hard that is)
- currently it does not make sense to start the game without REPL, see #82 
- maybe it would be possible to add keys to **increase size** of panels
- related #136 could be used to store user configuration including custom action keys (the `m` in world is my annoyance)

---

> use a modifier combination, which is bad

Actually I could use *more* modifier combination - say <kbd>Ctrl</kbd>+<kbd>X</kbd> moves selection in inventory panel or <kbd>Alt</kbd>+<kbd>↑</kbd> to move map.

**Comment by byorgey** [comment]
> * collapsible panes sound great, but would need a special brick widget to replace them when collapsed (no idea how hard that is)

Don't think it would be that hard, actually.

**Comment by xsebek** [comment]
> Better key-based navigation

I suggest implementing #523 so that everyone can customize to their hearts' content. :wink:

> Collapsable panes

What I imagine is putting a button on the panel line, so that clicking it toggles the panel. That way beginners will not be too lost. There could of course be a keyboard shortcut too. :slightly_smiling_face: 

The button could look like <kbd>Open REPL</kbd> or just simple <kbd>^^^</kbd>.

_The thing is, we do not currently allow clicking on buttons in the game._ :sweat_smile:

> Unobtrusive REPL

Sure, it could just be collapsed or we could allow resizing it. A configuration file would be nice for this.

We could also add buttons for increasing/decreasing panel size (<kbd>^</kbd>/<kbd>v</kbd>) or figure out how to let the mouse drag the separating line.

**Comment by byorgey** [comment]
> The thing is, we do not currently allow clicking on buttons in the game.

This is easy though.  We already allow clicking on things in the game.  You just have to declare a `Widget` to be `clickable` and then handle the resulting click events.  It just so happens we don't have anything called a "button" but it's really no different than handling any other kind of mouse clicks.

> or figure out how to let the mouse drag the separating line

That does actually sound harder.  I don't actually know how to handle dragging with `brick`.

**Comment by xsebek** [comment]
Closing this in favour of #813 and #523.
