### ISSUE TITLE
Consolidate structure assembly code between `WorldDescription.hs` and `Structure.hs`

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#2069]
See:
https://github.com/swarm-game/swarm/blob/6a3f84e514c2c8cf50e084bdf29368145b7993b2/src/swarm-scenario/Swarm/Game/Scenario/Topography/WorldDescription.hs#L85-L94
vs.
https://github.com/swarm-game/swarm/blob/6a3f84e514c2c8cf50e084bdf29368145b7993b2/src/swarm-topography/Swarm/Game/Scenario/Topography/Structure.hs#L105-L115

**Comment by xsebek** [comment]
@kostmo, could you please add a description to this issue?

I am unfamiliar with world internals, so I wonder what this is about. 🙂
