### ISSUE TITLE
Option to start the game paused

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#2076]
**Is your feature request related to a problem? Please describe.**

Sometimes (#2064), I need to debug the first tick of the game.
That is hard because the game starts in a running state.

**Describe the solution you'd like**

Add command line option `--paused` to initialize the game state with the `runState == ManualPaused`.

**Describe alternatives you've considered**

I would not mind writing `--debug=startPaused` from #1324.

Starting with the game paused could be useful for competitive play, but probably not a good default.

**Comment by xsebek** [comment]
I tried to initialize the game while paused and was surprised it did not do anything. Apparently, other game state initialization functions use the scenario description. I wonder if the first game state is used outside of tests.

**Comment by xsebek** [comment]
@byorgey to test this, I set the scenario code to always start paused:
```diff
diff --git a/src/swarm-engine/Swarm/Game/State/Initialize.hs b/src/swarm-engine/Swarm/Game/State/Initialize.hs
index 5e716353..86715151 100644
--- a/src/swarm-engine/Swarm/Game/State/Initialize.hs
+++ b/src/swarm-engine/Swarm/Game/State/Initialize.hs
@@ -88,6 +88,7 @@ pureScenarioToGameState scenario theSeed now toRun gsc =
   gs = initGameState gsc
   preliminaryGameState =
     gs
+      & temporal . runStatus .~ ManualPause
       & robotInfo %~ setRobotInfo baseID robotList'
       & creativeMode .~ scenario ^. scenarioOperation . scenarioCreative
       & winCondition .~ theWinCondition
```

This gets to a really strange state where the side panels are empty, and the goal is not yet shown, but REPL works:
<img width="1418" alt="Screenshot 2024-07-23 at 0 12 12" src="https://github.com/user-attachments/assets/fcbbff0e-d131-4dea-98f8-e3a4ff90ced2">

After one step with `C-o`, the panels load, and the goal modal pops up.

**Comment by kostmo** [comment]
Not quite the same as pausing, but sometimes for debugging I have started the game at a very slow speed, e.g.:
```
scripts/play.sh -i Tutorials/move --autoplay --speed -3
```

**Comment by xsebek** [comment]
Thanks for the tip @kostmo !

I will try that out, though I would expect speed 0 to mean 0 ticks per second.

**Comment by byorgey** [comment]
Speed n means 2^n ticks per second.  We should improve the help text to make that clearer.  Right now it says "Initial game speed multiplier" which seems ambiguous at best.

**Comment by noahyor** [comment]
> This gets to a really strange state where the side panels are empty, and the goal is not yet shown, but REPL works.

This is because the Inventory and Info panels update on Frame events, which causes this strange behaivior.

I had to deal with this when I was integrating Swarm with [Termite](https://github.com/noahyor/termite/), because I forgot to spawn a thread which sends Frame events.

**Comment by xsebek** [comment]
Thanks for the info, @noahyor; I will file a separate Issue to update the panels at the start. 👍
