### ISSUE TITLE
Show the panels and goal dialog at game start

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#2081]
**Describe the bug**

> > [Starting the game paused] gets to a really strange state where the side panels are empty, and the goal is not yet shown, but REPL works.
>
> This is because the Inventory and Info panels update on Frame events, which causes this strange behavior.
> 
> I had to deal with this when I was integrating Swarm with [Termite](https://github.com/noahyor/termite/), because I forgot to spawn a thread which sends Frame events.

_@noyahor in https://github.com/swarm-game/swarm/issues/2076#issuecomment-2245665697_

**To Reproduce**

Run the game with `--paused` from #2080 and observe the game dialog showing up after one tick.

Alternatively, try running the move tutorial - this may require more retries.

**Expected behavior**

The UI should always be fully functional at the game start and not wait for events or robots to finish.

This is especially important with the goal dialog, as the player needs to know what to do in the scenario, and a long pause loading the robots would be confusing. This was noted by @byorgey in https://github.com/swarm-game/swarm/pull/2064#issuecomment-2241726548.

**Screenshots**
<img width="1418" alt="351126876-fcbbff0e-d131-4dea-98f8-e3a4ff90ced2-2" src="https://github.com/user-attachments/assets/9ae1e2c1-149d-4b4f-839f-4f800dca6eb5">

**Comment by byorgey** [comment]
I think I understand why this happens.  The `updateUI` function does a whole lot of stuff, including calling `doGoalUpdates` which is responsible for setting the proper modal.  However, `updateUI` is not called when the game is paused.  Perhaps the solution is to split `updateUI` into two functions, one that should always be called on every frame event and one that should only be called if we just ran the game for some ticks?
