### ISSUE TITLE
`build-game.sh` should not require `pandoc`

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#2083]
Currently, `swarm-web` depends on `swarm-doc`, which uses `pandoc`.  Since the `swarm` executable depends on `swarm-web`, we end up compiling `pandoc` just to play the game.

We probably should be able to remove the `swarm-doc` dependency from `swarm-web`.

**Comment by byorgey** [comment]
Are you saying that swarm-web only depends on parts of swarm-doc that don't use pandoc?  Perhaps the solution is to split swarm-doc?

**Comment by xsebek** [comment]
@kostmo, thanks for bringing this up. 👍 

I just had to recompile Swarm with older GHC and noticed a lot of time was spent compiling Pandoc.
