### ISSUE TITLE
Tutorial levels no longer prompt to start the next level upon goal completion

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#2117]
It used to be that the "Congratulations!" dialog popped up, with the "Next challenge!" button preselected, as soon as the player completes the tutorial goals.

Now, however, the "Goal" dialog (which the user has already seen) pops up instead.

I think it is important to provide a sense of continuity between tutorial stages by automatically prompting the user to continue to the next one.  As it is now, the user needs to somehow know to press <kbd>CTRL</kbd>+<kbd>q</kbd> to advance to the next tutorial stage.

**Comment by byorgey** [comment]
Eek!  This is most definitely a bug.  It would probably be helpful to do a `git bisect` to figure out where this was introduced; I may do so later if no one else gets around to it first.

**Comment by xsebek** [comment]
Ups, I used git bisect to confirm I caused this by #2095.

**Comment by byorgey** [comment]
@xsebek Ah, I wondered if that was it.  However, I think this means that previously, the congratulations dialog just "happened to" override the goals dialog because it popped up first and then the UI wasn't updated after that.  Hopefully now the logic will be clearer.
