### ISSUE TITLE
After selecting "Keep playing", game gets re-paused upon every keypress

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#2174]
To reproduce:
```
./scripts/play.sh -i data/scenarios/Tutorials/grab.yaml --autoplay
```
1. Hit <kbd>Enter</kbd> to dismiss Goals dialog and wait until the scenario is won
2. Hit <kbd>Tab</kbd> and <kbd>Enter</kbd> to select "Keep playing"
3. Hit <kbd>Enter</kbd> to dismiss the "Have fun" dialog
4. Hit <kbd>Enter</kbd> to dismiss Goals dialog again
5. Notice that the game is unpaused
6. Type any key in the REPL
7. Notice that the game has become re-paused
8. Hit <kbd>Ctrl</kbd>-<kbd>P</kbd> to manually un-pause
9. Go to step (5), repeat

**Comment by byorgey** [comment]
Can confirm, I observe this behavior as well.  Currently trying to git bisect to figure out when this was introduced.

**Comment by byorgey** [comment]
65c5ef94ec7331c88e98ca58fc65b259ef830ada seems to be the culprit, which makes sense.

**Comment by xsebek** [comment]
Ups, it probably needs a check that the announcement queue is nonempty to pause.
