### ISSUE TITLE
Tutorial via challenge mode

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#25]
Once we implement #15 , I think it would be nice to have a simple tutorial that advances through a series of simple challenges, guiding the user through doing a few of the kinds of things they will need to do at the start of the game (build some robots, make some definitions, craft some devices, etc.)

**Comment by byorgey** [comment]
To make this work well might also require some kind of facility for stepping automatically through a specific list of challenges, with an option to continue to the next challenge after completing each one.

**Comment by xsebek** [comment]
@byorgey would you mind if I also pinned this?

There can be at most three pinned issues, so we should choose where to focus. :slightly_smiling_face:
