### ISSUE TITLE
Improvements to challenge mode

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#296]
Some left over ideas from #285 :

- [x] Provide a mechanism for a sequence of challenges, e.g. a tutorial where after doing one challenge you can progress to the next.  Perhaps put a bunch of challenges in a list in a single file, and provide a way for the user to signal when they are ready to progress to the next challenge.
    - Split out into #355 . 
- [x] Perhaps some improvements to the way challenge descriptions/goals are shown, winning is flagged, etc.
    - Split out as #356.
- [x] Possibly generalize challenges to just descriptions of how to initialize a game --- so classic and creative modes can be "just" generated by descriptions of how to initialize the game rather than special built-in modes.
- [x] Write up some documentation on how to author a challenge
    - Split out as #354 . 

We could further split out some of these into their own issues, but I just wanted to make sure they got preserved.

**Comment by xsebek** [comment]
Also related to documentation :slightly_smiling_face: 
- [ ] Fix README to mention challenges:
  >  (TBD) In Challenge mode, where you attempt to program robots in order to solve pre-designed puzzles or challenges.

And a bit more futuristic:
- [ ] Integrate with #4 (this would be awesome :star_struck: )
- [ ] Save challenge status (Not started/In progress/Finished) in XDG_WHATEVER_DIR (for browsing in the menu)

**Comment by noahyor** [comment]
On the idea of

> Provide a mechanism for a sequence of challenges, e.g. a tutorial where after doing one 
> challenge you can progress to the next,

in each challenge file, you could have a `next` value which references another challenge file to be done next (if the player so chooses).

**Comment by noahyor** [comment]
You could also have a 'meta challenge' which is just a list of challenge file paths. This way, the challenge ~~sequences~~ collections don't even have to be linear!

Note: this was originally @byorgey 's idea.

**Comment by byorgey** [comment]
Closing this issue since all the mentioned ideas have now been split out into their own separate issues.
