### ISSUE TITLE
Ability to access past REPL results

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#304]
From #303 ; depends on implementing #98 first.

The idea might be to have a special primitive array available which is notionally appended to every time a new REPL value is returned. We could change the REPL output to show the index, e.g.
```
> 3 + 5
res[0] = 8
> build {move}
res[1] = <r0>
> def r = res[1] end
```
or something like that.

**Comment by byorgey** [comment]
A couple related questions come to mind: (1) how early do we want players to be able to access past REPL results? (2) What device(s) will be necessary to use arrays?

**Comment by byorgey** [comment]
I just realized that even without an array to access all past REPL results, it would already be extremely useful to have a special variable `it`, like GHCi has, which is always bound to the most recent result.  We would need to make sure that something like
```
build {move; move}
def mover = it end
1 + 2
view mover
```
works properly --- the (potential) problem is that the definition of `mover` isn't evaluated immediately, so by the time it is actually used the value of `it` will be different.  However, I *think* this should actually work properly --- evaluating `1 + 2` will shadow the definition of `it`, but the definition of `mover` should still refer to the `it` that was in scope at the time it was defined.

**Comment by valyagolev** [comment]
I want to note that if there's only plans to implement arrays with fixed type, it will be impossible to use them to implement this feature. In that case there's no need to wait for the arrays to land, and we can simply introduce indexed variables like `it0`, `it1`, etc

**Comment by byorgey** [comment]
@valyagolev oh, of course, that's a very good point!
