### ISSUE TITLE
Commands to meet other robots

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#306]
This is an idea that came out of the discussion on #212 .  The basic version would be to have a command like `meet : cmd (() + robot)` which gives you a reference to another robot in the same cell as you (or perhaps up to a certain distance away), if there is one.  With lists (see #97 and #154), there could also be some kind of `meetAll : cmd (list robot)`.

**Comment by byorgey** [comment]
Instead of a function that returns a list, we could have a function that lets you fold over the robots nearby.  This is just as good as having a list but without requiring any special data structures.  Something like `meetAll : (robot -> b -> b) -> b -> cmd b`.

**Comment by xsebek** [comment]
@byorgey I like the second `meetAll` that takes the function `(robot -> b -> cmd b)`.

I take it will not be possible to use it with atomic? :smile:

**Comment by byorgey** [comment]
I had almost convinced myself that the version with `robot -> b -> b` is better, but after playing with things for a while I'm convinced that the `robot -> b -> cmd b` version is superior.
- It is easy to implement the `robot -> b -> b` version in terms of the `robot -> b -> cmd b` version:
    ```
    def meetAllPure : (robot -> b -> b) -> b -> cmd b = \f. meetAll (\r. \b. return (f r b)) end
    ```
    Going the other direction is also possible but not as nice.
- The version with `cmd` will often be convenient when you want to run some command for each nearby robot, e.g. `give` each one a `bitcoin`:
    ```
    def makeItRain : cmd unit = meetAll (\r. \b. give r "bitcoin") () end
    ```
- The version with `cmd` is implicitly running the resulting commands in some particular order under the hood, but since it's going to iterate through the nearby robots in some arbitrary order anyway, you can't really complain about that.
- If you want complete control over the order in which the resulting commands get run or anything more fancy, you can always use `b = cmd unit`. (You just might have to throw in a call to `join` or two.)

**Comment by byorgey** [comment]
Any ideas for what device could provide the `meet` capability?  Currently I added it to `scanner` just to put it somewhere but `scanner` is already rather overloaded...

**Comment by xsebek** [comment]
I would suggest something made out of mid game material like iron or silver.

- shaky iron arm (for handshakes)
- antenna (for communication)
- radar (to scan around for robots)

**Comment by byorgey** [comment]
Good idea.  We've talked about adding `antenna` before for other things, so I added it.  Current recipe is 2 `silver` + 2 `copper wire` but I'm open to other ideas.
