### ISSUE TITLE
Why is Value defined as a GADT?

### ISSUE THREAD

**Issue by nanonaren** [swarm-game/swarm#331]
Apologies if this is the wrong place to ask this question. Is there a reason `Value` is defined as GADT? Given that `Value` has no parameters, does defining it as a GADT still offer some advantage over defining it as an ADT?

**Comment by byorgey** [comment]
This is a perfectly fine place to ask the question!  No, there is no technical advantage to defining `Value` as a GADT.  I just like GADT syntax better than "normal" ADT syntax, that's all.
