### ISSUE TITLE
Add sand entity

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#336]
Sand can be used to make glass in a furnace, which could in turn be required to make a solar panel, needed for a calculator.  See the discussion at #26 .

My idea is that sand can be found on some edges of water, perhaps at the boundary between two specific biomes.

**Comment by byorgey** [comment]
Maybe sand could also be made from rocks somehow.

**Comment by xsebek** [comment]
> from rocks

We do have drills that robots use to get through mountains, maybe they could be used to drill down rocks to sand?

But having sand on some of the edges of water could be visually nice too - there does not need to be much of it if it's a growing entity like water. :slightly_smiling_face:
