### ISSUE TITLE
Compass device

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#341]
In some challenges it is undesirable to be able to turn to cardinal directions.

For example in some algorithmic challenges the robot should only turn `left` or `right`, to teach thinking relative to the robot.

The chess horse challenge sets the robot direction to `[2,1]` so it moves like the knight piece. Turning north cheeses the challenge. :sweat_smile: 

## Solution
Create a compass device, some cardinal orientation ability which will be required for cardinal directions.

The recipe could be something really simple like:
```
1 water ─┬───── compass
1 copper ┘
   wire
```

## Alternatives

We could limit abilities directly in challenges, but it would still require creating some compass ability.

---

- credit for the idea goes to @byorgey in #339

**Comment by xsebek** [comment]
Well iron plate would be more realistic. We could even add lodestone, if magnets were useful in other recipes (lodestone + iron plate -> magnetized iron plate + lodestone).

- see #93

**Comment by byorgey** [comment]
Should be pretty easy to add a new capability, maybe called `orient`, and update capability checking so `orient` is required any time a cardinal direction is mentioned.
