### ISSUE TITLE
Robot to name or id and back

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#343]
This is a meta issue for discussion of the way we convert between robot, its name and id.

```
      self
       │
       ▼
   ┌─────────────┐◄───┐
   │current robot│    │setname
   └──────┬──────┴────┘
    whoami│
          └───►┌──────────┐
               │          │
┌─────────────►│robot name│◄───────────┐
│as r {whoami} │          │           ?│
│          ┌───┴──────────┴───┐        │
│          │find             ?│        │
│          ▼                  ▼        │
│ ┌──────────┐◄─────────────┬────────┐ │
└─┤          │      ?       │        ├─┘
  │robot type│              │robot ID│
┌─┤          │      ?       │        │
│ └──────────┴─────────────►└────────┘
│  ▲     ▲   ▲
└──┘     │   │
parent  base └─build
```

Why the robot ID? Because it is unique, stored in `VRobot Int` and printed in REPL:
```
> build {move; move}
<r1> : robot
```
The problem is that typing `<r1>` in REPL does not return `robot` value. What shall we do?

**Comment by xsebek** [comment]
Also, since #303 each robot gets a random name, like Fermi or Gagarin. :smile:  This funny detail is sadly not shown to users. 

To kick off the discussion, my idea would be to add two functions:
```c
robotNamed : string -> cmd robot // current 'find'
robot      : int    -> cmd robot // currently missing
```

Then the `VRobot 1` could be shown as `robot 1`.

**Comment by xsebek** [comment]
@byorgey what do you think? I can still rename `find` in #339. :slightly_smiling_face:

**Comment by xsebek** [comment]
Btw. when `view`ing the robot, we do show its name in the inventory panel:
```
┌──────────────────────────────────┐
│    trusting_euclid  (2, 0)  >    │
│                                  │
│ ────────Installed devices─────── │
```

So I would argue for just printing `robotNamed "trusting_euclid" : robot` for consistency and fun.
<sub>I almost want to have that power in a regular game, could `robot registry` be a thing? :smile: </sub>

If we wanted to make it really opaque, we could print `undefined : robot` or make `unnamed` constant so it reads better and provides some nice error message.

**Comment by byorgey** [comment]
One problem is that names are not guaranteed to be unique.  So printing out `robotNamed "foo"` as the value of the robot doesn't seem like a good option to me, since it might not actually evaluate to the same robot.

**Comment by byorgey** [comment]
I guess in general I don't see the need to be able to look up robots by name.  If you are just dealing with a few robots directly at the REPL, you can just put them in memorably named variables.  If you are writing a program to deal with many robots, then you will have them in some sort of data structure, and it really doesn't make a difference whether you're dealing with strings or `robot` values.

**Comment by xsebek** [comment]
> `robotNamed "foo"` might not actually evaluate to the same robot

Sure, but `robotNamed "foo#1"` will. I tried it and passing the name along with id in `VRobot` and `TRobot` is not a big change.
Alternatively, we could make the function giving names unique.

Pairing the REPL command to the robot that logged some error seems quite important.

For debugging, I need the robot numbers. Even if I occasionally do `error "---"` to mark the current time in the log, seeing the number of the robot helps to alert me to how many `build` commands actually worked or did not work. But this use case could be limited to some `--debug` flag.

**Comment by byorgey** [comment]
I was frustrated today when I forgot to bind the result of `build` to a variable name and it got me thinking about some related things again.  What if every robot has a "registry" of robots that it has built, accessible by "child id"?  In particular, I propose:
- adding a primitive `child : int -> robot`
- `child n` evaluates to the nth child built by the robot evaluating it
- when printing a robot value, print it in the form `child n` *when possible* (this will be most of the time)
- maybe there could also be `friend : int -> robot` which is a registry of other robots you know about
- evaluating some robot which is not a child will cause it to get added to the friend index, so it can be printed as `friend k`
- note friend and child indices will be specific to each robot; they will have nothing to do with internal (globally unique) robot ids, which will be completely hidden

**Comment by xsebek** [comment]
@byorgey I like it, sounds very user `friend`ly 🙂 

Maybe if you have a spare counter you could make an indexed log of robots:

- counter + log -> robots index

```
Indexes the robots created and met.

————— Index ——————

// built mad_max
child 0
// built crazy_ed
child 1
// met weird_al
friend 0 // or 3?
```
This would be helpful for debugging, maybe we could add that to cheating:
- `—cheating [log,index]` to always add those devices

**Comment by byorgey** [comment]
Ah, I like the idea of making it a device!  I don't know if it needs to be a separate cheating option; if you turn on `--cheat` and you want a robot index it seems easy enough to do `Ctrl+K, create "robot index"; install self "robot index", Ctrl+K` or something like that.

**Comment by xsebek** [comment]
@byorgey I can do something like that, but until we get multiline REPL (#134) it would eat a lot of my visible line.
I guess `require` (#201) would help with that.

**Comment by byorgey** [comment]
I'm not sure I understand what you mean.  But in any case I don't really care, if you think adding a special command-line flag would be much more convenient, then feel free to add it.

**Comment by xsebek** [comment]
The diagram above is filled now with `robotNamed` and `robotNumbered`, let's discuss better ways for mortals to do it in other issues.
