### ISSUE TITLE
Export JSON schema for scenarios

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#346]
It would be nice to get editor support for writing scenarios.

[JSON schemas for YAML](https://json-schema.org/learn/getting-started-step-by-step.html) seem to do the job, but can we generate them somehow without much work?

**Comment by byorgey** [comment]
https://github.com/NorfairKing/autodocodec might be helpful here, although I am not sure how it would interact with our need for custom `FromJSONE` instances.
