### ISSUE TITLE
Add missing ToJSON instances

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#347]
I would like to have [`ToJSON`](https://hackage.haskell.org/package/aeson-2.0.3.0/docs/Data-Aeson.html#t:ToJSON) to complement the current [`FromJSON`](https://hackage.haskell.org/package/aeson-2.0.3.0/docs/Data-Aeson.html#t:FromJSON). 

- **With #337 adding a `ToJSON Scenario` would solve 99% of #50!** But for purposes of this issue adding most of the necessary instances would already be great.
- If designing `ToJSONE`, consider making the class generate JSON Schema for free and solve #346.

**Comment by xsebek** [comment]
We would probably want to create a custom class given that we need some environment references.

Though at the top level I would not mind just splicing in the entire `data.yaml` and `entities.yaml`, they are not that long. :smirk:

**Comment by TristanCacqueray** [comment]
What about CESK machine, is it possible to implement the full serialization of its state and the continuation Frames? Or is there a more desirable encoding strategy?

It seems like we would need to add many instances, should they be added to each modules, or should we collect them all in an extra module using orphaned instances?

**Comment by byorgey** [comment]
It is definitely possible to fully serialize a CESK machine --- in fact, part of the original reason I chose to use something like a CESK machine is that it represents higher-order functional programs in a completely first-order way, making it possible to serialize them.  (As mentioned elsewhere, `WorldUpdate` and `RobotUpdate` actually contain functions and hence make this impossible at the moment --- but we can and should replace them with first-order representations that enumerate the specific types of update functions we need.)

**Comment by byorgey** [comment]
> It seems like we would need to add many instances, should they be added to each modules, or should we collect them all in an extra module using orphaned instances?

At the moment it seems we have gone with having each instance live in the same module as the data type it is for, so I guess we should stick with that approach for now.  There are pros and cons to either choice.

**Comment by xsebek** [comment]
The autodocodec package has a lot features we want and looks nice:
- https://github.com/NorfairKing/autodocodec

It might be worth investigating if it can work with select parts requiring environment.

**Comment by byorgey** [comment]
At this point I think we have `ToJSON` instances for pretty much everything, including `CESK` --- I am not aware of any important types with missing `ToJSON` instances.  The big problem now is serializing to something small (#1907).  I am going to close this issue, and if we discover any types with a missing instance we can create individual issues for them as necessary.
