### ISSUE TITLE
Generalize properly when inferring the type of a bind

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#351]
Returning a generic type seems to crash the typing:
```
> r <- return (\i.undefined)
\i. undefined : ∀ a1 a2. a1 -> a2
> 1
```
```
swarm: Maybe.fromJust: Nothing
CallStack (from HasCallStack):
  error, called at libraries/base/Data/Maybe.hs:148:21 in base:Data.Maybe
  fromJust, called at src/Swarm/Language/Types.hs:285:11 in swarm-0.1.0.0-inplace:Swarm.Language.Types
```
The game crashes immediately once it starts to type the next expression. :bomb:  :boom:

**Comment by byorgey** [comment]
Weird, just typing `\i. undefined` or `return (\i. undefined)` by themselves don't trigger the bug, the bind `r <-` seems to be necessary...

**Comment by byorgey** [comment]
So I found the place in `inferModule` where we typecheck a binder.  At first I thought it was as simple as adding a call to `generalize`, just like we have in the branch of `inferModule` that infers the type of a `def`.  However, it didn't work, and it took me a long time to figure out why.  The problem is that when trying to generalize over the type of `r : u0 -> u0` (where `u0` represents a unification variable, i.e. `IntVar (-9223372036854775807)` in the above), it doesn't consider `u0` free, since `u0` actually shows up in the context: the type of `r` itself is in the context---as it should be, since `r` may occur later in the term in addition to having its type exported to the top level.  (Indeed, even in this example, `r <- return (\i.i)` is really syntax sugar for `r <- return (\i.i); return r`.)

Perhaps the right answer is that it simply doesn't make sense to bind polymorphic things via `<-` at the top level.

**Comment by xsebek** [comment]
Thanks, @byorgey for investigating this, I found it quite surprising and the GHCi example is even more baffling. :exploding_head:

**Comment by byorgey** [comment]
https://stackoverflow.com/questions/61805899/why-ghc-types-any-here is relevant, and further strengthens my conviction that we shouldn't allow polymorphic types as the result of a top-level `<-`.  

In general, if `x : cmd t` then if we do `r <- x`, we will have `r : t`.  But consider that `return (\i.i)` actually has type  `forall a. cmd (a -> a)`, not `cmd (forall a. a -> a)` (indeed, Swarm doesn't support this kind of non-top-level quantification), so it would be strange for `r <- return (\i.i)` to result in `r : forall a. a -> a`.  Instead it should result in `r : t -> t` for some specific type `t`.  If `t` is constrained by later uses of `r`, well and good; but if not, the situation in this ticket (and in the linked StackOverflow post) arises.

**Comment by xsebek** [comment]
I can imagine the usage with constraining the type immediately after could be somewhat common.
I can only type in def/let and even for that I am sometimes lazy.
But as long as I write in one file all will be resolved well. In REPL it is a slight problem. 😅

Could we add this check as a validation pass so the type checker gets its chance to constrain the variables?

**Comment by byorgey** [comment]
@xsebek I'm currently thinking something along these lines, what do you think?
```
> r <- return (\i. i)
Warning: monomorphizing variable 'r' bound via <- (http://link to more detailed discussion on wiki)
() -> ()
```

**Comment by byorgey** [comment]
Started working on this in `monomorphize-bind` branch.

**Comment by byorgey** [comment]
I honestly don't remember what progress I made on the `monomorphize-bind` branch.  Not much, it seems.  I seem to recall I got stuck but I can't remember what I got stuck on, and it seems I didn't write it down. :cry:

**Comment by byorgey** [comment]
Here's the one commit I made: https://github.com/swarm-game/swarm/commit/3ba9826e197d4b94519341761d6c3ef09e7a4fe3  Copying the commit comment here for reference:

---

There's really something deeper going on here, e.g.
```
> return (\i.i)
\i. i : ∀ a1. a1 -> a1
```
This should not yield something polymorphic either.  The issue is not really `<-`, but rather the fact that `cmd` should not be impredicative.

Also, being able to generate warnings from inside the typechecker is going to require a bit of plumbing...

**Comment by byorgey** [comment]
Updated the title to reflect my current understanding of the issue: we just want to disallow impredicativity in types.  So we should not be able to have types like `(forall a. a -> a) * Int` or (especially) `cmd (forall a. a -> a)`.  The question is how to actually implement checking for / disallowing these.  I'm sure this is folklore but I'm not sure where to find it.

**Comment by xsebek** [comment]
@byorgey can we replace all inner `forall` with `void` or something? :slightly_smiling_face:

I imagine it as a final pass after `infer`.

**Comment by byorgey** [comment]
That would be nice, but it's not quite that simple, because as the examples in this ticket show, we also have to prevent impredicative types that show up *during* the type inference process even if they don't end up as the final output.

**Comment by xsebek** [comment]
@byorgey but looking back to the original example, we survived the first typechecking.

Can this occur in a middle of type inference? AFAIK not, because we are happy to constrain types by later usage.

Maybe there is something I am missing? 🤔

**Comment by byorgey** [comment]
But consider the original example `r <- return (\i. i)`.  What is the type of `r`?  Its type is unconstrained, so the only reasonable type would be something like `forall a. a -> a`.  However this is only true if you assign the type `cmd (forall a. a -> a)` to the subterm `return (\i. i)`, which we don't want to allow.  So in fact `r <- return (\i. i)` should be an error.

**Comment by xsebek** [comment]
@byorgey well that is even simpler than my proposal, no?

I agree that the unconstrained type is bad, but it only kills us if we let it live after inferring the type of the whole expression.

Consider this:
```
f <- return (\x.x); g <- return (\y. f (f y))
```

You can paste this into the REPL and hit Enter. It seems to me, that only after you type something new into the REPL will we use the incorrectly saved types from context to typecheck the current input.

What I am saying is that we can parse and infer the type of this Swarm term like we are used to. _But_ before we save the type as valid, we should either monomorphise it (replace `forall a. a` with `()`/`void`/`GHC.Types.Any`) or throw an error.

@byorgey you seem to be suggesting that something needs to be done while inferring the type, right? :confused:

**Comment by byorgey** [comment]
I sat down with @ccasin today to look at this.  He convinced me that it is actually fine to return `forall a. a -> a` as the type of `r` in `r <- return (\i.i)`, even though we can never have a type `cmd (forall a. a -> a)`.  Basically in a Hindley-Milner-style system it is *always* safe to generalize at any time.

The real problem --- which I was very close to discovering in [an earlier comment](https://github.com/swarm-game/swarm/issues/351#issuecomment-1146274801) --- is simply that we need to generalize the type of variables bound by `<-` --- but we need to make sure to do so *before* putting that variable in the context.  PR coming soon!
