### ISSUE TITLE
Display world preview under description when selecting a scenario from the New Game menu

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#353]
When the cursor is highlighting a particular scenario in the New Game menu, the description of the scenario is displayed to the side.  It might be nifty to also display a preview of the world (especially for challenge scenarios that have a custom world).  For example, something like this:

```                                                                                                                        
Scenarios > Challenges                  A very difficult challenge that will test the utmost limits of your ability to                    
                                        'move' and 'grab'. This is actually a placeholder challenge and will be                           
Test challenge                          replaced with more suitable challenges soon.                                                      

                                                              ┌─────┐
                                                              │>░λ░░│
                                                              │░░░░λ│
                                                              │░░░λ░│
                                                              └─────┘

**Comment by byorgey** [comment]
How about this:

- *If* the scenario has a `map`, we display a 11x11 patch of it (or some suitable constant size) centered on the base.
- Otherwise (e.g. for the Classic game), we don't display anything.

**Comment by byorgey** [comment]
I think doing this properly might require some refactoring of our current world drawing code to make it more modular, so we can reuse it to display world previews.

**Comment by xsebek** [comment]
> Otherwise (e.g. for the Classic game), we don't display anything.

Why not? I think it would be nice to preview the random world as well.

Or do you mean to hide it to not spoil the seed? For example, Factorio allows you to preview the random world (or not if you don't want to get spoiled) in an overview map where you can see the resource patches in a large area:

![factorio new world](https://user-images.githubusercontent.com/44544735/201148042-e1ae35b0-d8bd-4774-8b85-fb93eb63cc95.png)

Once we allow customizing the seed in UI, hiding the preview would not make sense.

**Comment by byorgey** [comment]
> Why not? I think it would be nice to preview the random world as well.

You're right. I have no idea why I originally said that.  Maybe just out of a sense that as a first cut, it would be easier to only handle explicit maps.  Then we could later look into previewing generated worlds as well.

**Comment by xsebek** [comment]
Now that we can specify the seed in UI scenario options, it would be nice to show a preview. 🙂
