### ISSUE TITLE
Documentation for how to author scenarios

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#354]
This is potentially related to #346 and #347, but is fundamentally separate.  We need some documentation somewhere (e.g. on the [wiki](https://github.com/swarm-game/swarm/wiki)?) explaining the format of the `.yaml` files used to describe scenarios and what all the different options mean.

**Comment by byorgey** [comment]
Started working on https://github.com/swarm-game/swarm/wiki/Authoring-scenarios .

**Comment by byorgey** [comment]
Now that I think about it, the wiki is not a great place for it, since we want to make sure we keep it up to date if we change the format in the future.  Hence something under version control seems more appropriate.  I will put it in `SCENARIOS.md` (unless anyone has a better suggestion).

**Comment by xsebek** [comment]
@byorgey the Wiki is actually a separate repository under version control too. :wink: 

But keeping it in sync here is a good idea. :+1:

I would like to have the document next to examples of scenarios. A README.md would show in GitHub when opening the scenario folder. Maybe we could have a symlink "scenarios -> data/scenarios" to make it more discoverable?

**Comment by byorgey** [comment]
Good idea!  I didn't actually realize git can handle symlinks properly.
