### ISSUE TITLE
Improvements to challenge scenario UI

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#356]
Some ideas:

- [x] Instead of having a special item denoting the goal, there should be a special `goal` field in the scenario description file; the goal can then be shown in a pop-up dialog box when the scenario is first loaded, with a key shortcut to pop up the goal dialog again any time the user wants. #450 
- [x] When completing a scenario, the "congratulations" dialog box should give the options to continue or return to the menu.

**Comment by TristanCacqueray** [comment]
- [ ] keep track of the completed scenarios and adds a mark in the menu for the one that are already done.

**Comment by byorgey** [comment]
@TristanCacqueray see #357 .

**Comment by byorgey** [comment]
Closing now since the only thing not done is #357.
