### ISSUE TITLE
Save scenario completion status

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#357]
From #296 : 

> Save challenge status (Not started/In progress/Finished) in XDG_WHATEVER_DIR (for browsing in the menu)

Some kind of icons could then be shown in the "New game" menu showing the status of each scenario.  For now, there are just two states: completed / not completed.  Once we have #50 we can also have an "in progress" status.

**Comment by xsebek** [comment]
@byorgey I might have some time over the weekend, shall I take a look at this or do you want to do this yourself? 🙂

**Comment by byorgey** [comment]
I have some code already written for this, I'll either keep working on it tomorrow or, if I don't have time, at least push what I have up to a branch so you can use it (or not).

**Comment by byorgey** [comment]
@xsebek I pushed up what I have (not much) in the `completion-status` branch --- some data types to represent the status of scenarios; my plan was then to have a `Map` from scenario paths to status values and load and save that from a file.  But I'm not going to have much time to work on this for the next little while.  If you want to take a look at it, feel free to use what's there, or start over from scratch if you have a different design in mind, I truly don't care either way.
