### ISSUE TITLE
Allow player to choose a specific seed through the UI

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#358]
Currently, a specific seed can be chosen on the command line, *e.g.*
```
stack run -- -c 00-classic -s 0
```
But if you choose *e.g.* classic mode via the "New Game" menu, you get a random seed with no way to override it.  There should be some (optional) mechanism by which the user can specify a seed if they wish (e.g. for "set seed"-style speedruns, to play the same world as their friend, etc.).

**Comment by xsebek** [comment]
How about showing the seed in grey somewhere and hinting at the <kbd>R</kbd> key to regenerate it? :slightly_smiling_face:

**Comment by byorgey** [comment]
Showing the seed in grey somewhere sounds fine for #359 .  But I don't see how having an `R` key helps here.  By "regenerate" do you mean "choose a different random seed value"?  I want to allow the user to specify the seed, not just cause it to be re-chosen randomly.  And if by "regenerate" you mean e.g. "pop up a dialog asking the user to set the seed", it seems strange to have to start a new game with a random seed, then hit `R` to be able to set the seed yourself.  You should just be able to set it *before* starting the game.

**Comment by byorgey** [comment]
How about this: when starting a game with no `seed` and no `default` cell specified, we first pop up a dialog asking the user to enter a seed, or to leave the field blank for a random one.  This would mean slightly more keypresses to get a basic game started, but I don't think it would be too irritating, and it would be very obvious to anyone who wanted to play with a specific seed how they can do that.

**Comment by xsebek** [comment]
As an alternative, we could always provide a default and then specify if it is possible* to override the seed.

Then when you press <kbd>E</kbd> we would bring up a form to edit the scenario parameters (#558) but for now, that would only be the seed. Brick ships with functions to create forms ([`Brick.Forms`](https://hackage.haskell.org/package/brick-1.3/docs/Brick-Forms.html)) that we could use. Later we could add other parameters, like likelihood of resources in the world function, etc.

<sup>*) The `--cheat` falg would of course ignore that restriction. In speedruns some seeds are more plentiful and we do not want to allow setting a custom one.</sup>

**Comment by kostmo** [comment]
Created a related issue about specifying from the command line: #1006
