### ISSUE TITLE
Provide a mechanism for learning the current seed

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#359]
Currently, if you start a game with a randomly chosen seed, there is no way to find out what seed was used, which means that there is no way to play the same world again later, or tell a friend the seed so they can play the same super-cool world you discovered, etc.  There should be some mechanism for displaying the chosen seed to the player. Perhaps it could simply be displayed somewhere in the UI, or perhaps there should be some kind of key command for showing the seed.  I don't think there should be a robot command for returning the seed, since it seems to be mixing levels in a strange way: the seed used is a meta-aspect at the level of the game, but it is not something robots would ever be able to learn from within the world.

**Comment by xsebek** [comment]
Well we do have a command-line flag `--seed`, but I just tested it and it seems to be ignored :sweat_smile: 

If it was supported, then one could do:
```
seed=$RANDOM
cabal run swarm:swarm -- --seed $seed; echo $seed
cabal run swarm:swarm -- --seed $seed; echo $seed
```
The generated world should be the same.

**Comment by byorgey** [comment]
What do you mean it is ignored?  It works for me...

Anyway, this is not really sufficient, because it is possible to start the game, then select classic mode from the "New game" menu.  At that point the game chooses a random seed for you.  You should be able to find out what it is.

**Comment by xsebek** [comment]
> random seed is chosen for you

I do not understand - what is the point of the flag if not to override this?

Running first with seed 0:
![image](https://user-images.githubusercontent.com/44544735/172026516-69c19364-41bd-4614-98d3-96231b14abd5.png)

Second time:
![image](https://user-images.githubusercontent.com/44544735/172026537-0d58e11c-d4d9-4d6d-8a69-cac6e58f504b.png)

**Comment by byorgey** [comment]
Ah, I see, if you specify *only* a seed, it has no effect.  Choosing a scenario from the menu will use the seed specified by the scenario (or choose a random seed).  If you want to specify a seed on the command line you have to also specify a scenario, like `cabal run swarm:swarm -- --seed 0 --scenario 00-classic`.

I suppose we could change it so starting it with only the `--seed` flag will cause it to remember that seed and apply it to whatever scenario is chosen from the menu.  But this is a bit strange, actually --- if you then quit back to the menu and select a different scenario, should it continue to use the same seed specified on the command line?

I see a couple options:
- Make it an error to use only the `--seed` flag, and have it print an error message advising you to also use the `--scenario` flag
- Just make classic mode the default scenario, so if you use the `--seed` flag it will immediately start classic mode instead of showing you the menu.

I am leaning towards the second option.  This is actually very similar to #363.

**Comment by xsebek** [comment]
I would be fine with the first option too (except for writing `00-`) :slightly_smiling_face: 

But given #363 I am voting for a default classic :+1:

**Comment by byorgey** [comment]
Yeah, I don't like the `00-` part either.  That is there so that we can specify the order of scenarios in the menu.  But maybe we need a better way to do that, and/or automatically allow leaving that part off.

**Comment by xsebek** [comment]
Well sorry for distracting from seed in the game UI twice :sweat_smile: 

My two cents would be to add <kbd>F2</kbd> window showing the configuration and allowing edits.
We could also use it for game speed, showing game save location and maybe debugging stuff (cells, active robots).

**Comment by byorgey** [comment]
Hah, no worries.  F2 screen sounds like a good idea to me.
