### ISSUE TITLE
Get rid of `m` key to switch modes unless explicitly enabled via "cheat mode"

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#360]
Now that we can start a new game in either classic or creative mode, there probably no longer should be a way to switch between the modes arbitrarily (as we currently have with the `m` key on the world).  However, being able to switch between modes is still useful for testing (e.g. to quickly generate a certain device and then test how it works in classic mode).  So I propose:

- Add a command-line flag `--cheat` which enables "cheat mode" (off by default)
- Normally, when cheat mode is off, there is no way to toggle creative mode.
- However, when cheat mode is enabled, then we can toggle creative mode with the `m` key as we can now.

**Comment by xsebek** [comment]
I like it, once we store progress in the XDG directory, we can *not* update progress if the user is cheating. :grinning:

**Comment by byorgey** [comment]
Reopening since we need to update the tutorial to match.
