### ISSUE TITLE
Command line `--run` is broken

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#363]
```bash
cabal run swarm:swarm -- --run example/list.sw
```
![image](https://user-images.githubusercontent.com/44544735/172026373-9a118f9f-b3e3-4af8-80b8-f2789784d336.png)

**Comment by byorgey** [comment]
Hmm, I guess the problem is that it doesn't know which scenario to use so it just uses a blank default game state. It works if you do
```
cabal run swarm:swarm -- --run example/list.sw -c 00-classic
```
I guess we should just make classic mode the default if no scenario is specified?
