### ISSUE TITLE
Ensure copper is not too hard to get initially

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#385]
A small amount of copper is necessary in the early game - it's needed to make motors, and hence drills, so you need to get some surface copper to bootstrap your way into drilling more.  Copper is also needed for strange loops, which is not strictly necessary but is very helpful early on to be able to use functions like `forever`.

However, in my experience, in many worlds copper ends up being rather far away, and in particular there might not even be any visible on the screen depending on terminal size.  It seems a bit too difficult to get, especially considering that new players won't even necessarily know that they need it.

I am not quite sure what to do about this.   I don't just want to cover the world in lots of copper.  A few ideas, but I'm open to more:

- Change the function that looks for a good starting spot for the base so that it finds somewhere near both trees and copper.
- Start out the base with a bit of copper ore in its inventory.

**Comment by xsebek** [comment]
We could also make a beginner mode where we place some copper, bits and whatever else is needed close to the base.
Something like the starting patches in Factorio.

**Comment by byorgey** [comment]
I like that idea --- and I do want to make the world function configurable.  However, I'm not sure adding a special beginner mode goes far enough.  This is not only about making things easier for beginners --- even for experienced players, if there is no copper anywhere within the initial view, it can be difficult to even find it.  One option is to send robots off in various directions so you can `view` them, but if we implement #17 that won't be possible any more.  Otherwise, you are stuck programming a robot to wander around in some large pattern outside your view conditionally trying to harvest copper, but there is a big danger that it will run into something and get stuck.

I guess what I'm saying is that whatever we do should be in the normal classic mode rather than just a special beginner mode.

**Comment by byorgey** [comment]
For example, here is a random starting world:
![init](https://user-images.githubusercontent.com/533859/173253919-48bd415b-2629-405c-bf3a-894cd37cb201.png)
I can see what looks like plenty of everything else I need (trees, mountains, water, lambdas, rocks, bits, ...) but I don't see any copper.  The yellow things I think are sand.  However, if I maximize the window,
![big](https://user-images.githubusercontent.com/533859/173253970-ccc70585-05ca-49b5-9a3a-1d54deaa2d8d.png)
it looks like there might be some copper way over to the left.  (But I'm not sure, that might be sand.)

**Comment by xsebek** [comment]
@byorgey You are right, about half of the creative worlds I checked did not have copper in sight.

How about we check that a list of entities is present in the starting 64x64 tile? That should be fairly efficient. :thinking:

**Comment by byorgey** [comment]
Ah, @xsebek , that's an interesting idea, I hadn't thought of that.  Though 64x64 is still quite big (I think the screenshot of the second, maximized window I posted above shows approximately two 64x64 tiles).  But actually 64x64 is just an implementation detail of the current tile size, we could apply the same principle to find, say, a 32x32 square with all the required entities, and place the base somewhere in that square.

**Comment by byorgey** [comment]
It seems like this approach will work well!  I'll submit a PR shortly, once I clean it up a bit.
