### ISSUE TITLE
`halt` command to cancel a robot's running program

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#392]
**Is your feature request related to a problem? Please describe.**
Robots can be reprogrammed or salvaged when they are done; but currently there is no way to halt a robot's running program in the middle.  This is annoying especially in the case of robots set up to do something forever in an infinite loop.  If you messed up the program, or you just decide that you want to do something else now, there's currently no way to stop a robot in an infinite loop.

**Describe the solution you'd like**
There should be some way to explicitly tell a robot to stop its program.  Probably you should (1) need an explicit reference to the robot and (2) be physically close the robot. (If you want to be able to tell robots to halt from far away, well, you can program that yourself once we have #94 .)  For example, maybe it can be as simple as a new primitive `halt : robot -> cmd ()` which tells the given robot to halt if it is on the same cell as (or maybe within Manhattan distance 1 of) the robot executing the `halt` instruction.

**Describe alternatives you've considered**
I suppose an alternative would be to just say "tough luck, if you wanted to be able to cancel a robot program then you should have programmed that in from the beginning", with some kind of `cancellable_forever` function that has some built-in polling to see whether it should quit or keep going. But that would be pretty annoying.  No one can plan perfectly for the future.

**Comment by byorgey** [comment]
Idea: have `halt` provided by a `halting oracle` device.  Proposed description:

> A device to solve the halting problem.  When asked if a particular robot program will halt, it always answers YES.  And it is always correct. Or else.

**Comment by TristanCacqueray** [comment]
I like it. Perhaps we could also introduce a `chaitin constant` entity to make the oracle recipe :)
