### ISSUE TITLE
`take` command

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#393]
I think we should consider adding `take : robot -> string -> cmd ()` as a counterpart of `give`, which takes a specific item from another robot instead of giving it.

Pros:
- It is nice and symmetric
- It should enable some cool "just-in-time/pull-based" manufacturing pipelines where you can request a certain end product and robots fetch and assemble the necessary raw resources.  This is my main motivation.

Cons:
- It maybe feels a bit weird for robots to not be in control of their own inventory.
- If and when we add #218 this might be even weirder.  Can you steal stuff from alien robots?  Can they steal stuff from you?
- I remember while coding something like `salvage` that it seemed like some invariants could possibly be violated if there was a `take` command.  I don't remember what the issue was though.

An alternative we might consider, which would give us the benefits of pull-based manufacturing without the downsides of being able to steal from robots without their consent, is to allow `take` to work only on *boxes* instead of robots (see #115 ).  So you can place a box somewhere as a "depot" and then robots can place items into it or take items out of it.

**Comment by byorgey** [comment]
Actually, I think I have changed my mind.  I think it is very nice to maintain the invariant that robots are in control of their internal state (I guess `give` already violates this a bit, but `take` seems much worse).  Following the same "object-oriented" train of thought, the way you should get something from another robot is to send it a *message* requesting that it give you something.  Of course the other robot will have to be programmed to expect this.  So we don't need a `take` command to implement pull-based manufacturing, we just need `give` + #94 .

**Comment by xsebek** [comment]
Yeah, `take` would be practical, but we should ask for consent. :innocent: 

With #94 you could write something like:
```
def caseC = \m.\com. case m (\i. return ()) com end

forever {
  doSomething;
  me <- readNow myStringChannel;
  mr <- readNow myRobotChannel;
  caseC me (\e.
    caseC mr (\r.
      give r e
    )
  );
}

**Comment by byorgey** [comment]
OK, I think I will close this then.  But I'm glad we at least have a conversation to point to if this comes up again.
