### ISSUE TITLE
Wrong device reported missing

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#397]
**Describe the bug**
In certain situations with devices that don't exist, an error is generated saying that some other device is missing (even though it is not).

**To Reproduce**

- Start a classic mode game with `--cheat`
- Switch into creative mode and `create "branch predictor"`
- Switch back out of creative mode
- Type `build {move; if (1 > 2) {} {}}`
    - As expected we get an error saying no device provides the `compare` capability.
- Now type `build {move; turn left; if (1 > 2) {} {}}`
    - All we have done is add `turn left`; we would expect to get the same error.  Instead we get an error like `You do not have the devices required for: 'move; turn left; if (1 > 2) {noop} {noop}'  please obtain:   - branch predictor`
    - But we do have a branch predictor, so this error is bogus.  Not sure yet whether the capability checking or error reporting is to blame.

**Additional context**
First noticed this in https://github.com/swarm-game/swarm/pull/373#issuecomment-1154533582 .  Note that once #395 is merged then we *will* have a `comparator` device so the above example won't work any more.

**Comment by byorgey** [comment]
An example that still shows this problem now is `build {move; teleport base (2,3)}` vs `build {move; turn left; teleport base (2,3)}`.  The first gives an appropriate error, whereas the second says we are missing `treads`.

**Comment by byorgey** [comment]
I've traced this as far as seeing that the `Incapable` exception given to `formatExn` is already bogus.  `formatExn` seems to be doing its job properly, the problem is with wherever the `Incapable` exception is generated (probably the `checkRequirements` function).

**Comment by byorgey** [comment]
The example with `teleport` no longer works since we get an error about needing an ADT calculator instead.  However, the problem still exists and can be illustrated by the difference between `build {move; x <- whereami}` (correct) vs `build {move; turn left; x <- whereami}` (incorrect).

**Comment by byorgey** [comment]
Strangely both `move` and `turn left` are required in the examples here.  Omitting either one leads to the correct output.  Including a single one of those commands twice (e.g. `move; move`) also leads to correct output.  I've tried mixing other commands and the only thing so far that seems to trigger the incorrect output is to have *both* a call to `move` and a call to `turn left` before invoking a command without a device, such as `whereami`.

**Comment by byorgey** [comment]
I think the problem has to do with the fact that in this code:

https://github.com/swarm-game/swarm/blob/main/src/Swarm/Game/Step.hs#L1600-L1606

`deviceSets` is defined via `nubOrd` (hence it does not necessarily have the same length as the original `capDevices`) but yet we later do `zip caps deviceSets`, expecting the entries of `deviceSets` to still line up with `caps`.

I think this code

https://github.com/swarm-game/swarm/blob/main/src/Swarm/Game/Step.hs#L1583-L1588

is a bad idea: it creates an easy-to-get-wrong invariant that anything coming from that list must be kept in the same order and no duplicates dropped, since later it will get zipped with something.  We should instead do the `zip` right here and carry along the capabilities through the rest of the process, safely paired up with their corresponding devices.

**Comment by xsebek** [comment]
@byorgey the lines have shifted a bit it seems - if you use a link with specific commit GitHub should even show a preview. 😉
