### ISSUE TITLE
Known entities do not include installed devices

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#410]
## To Reproduce

1. Open Creative game
2. See that base has an installed drill in the inventory panel
3. Type `give base "drill"`

```
give: What is a drill ?
```

## Expected behaviour

I would expect installed devices to count as known - the same as `drill  0`.

I expect the same is true for devices `install`ed to other robots or built in.

**Comment by byorgey** [comment]
- Looks like we have an opportunity to refactor out some common code between `give` and `install`.
- A nice opportunity might be to notice whether we are in creative mode, and if so, add a hint to this error message (or the related one saying you don't have X) that you could make one with `create`.
