### ISSUE TITLE
Order recipes by whether the entity is an input, catalyst, or output

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#418]
In some circumstances there are a lot of "uninteresting" recipes cluttering up the view, hiding the more "interesting" ones.  A great example is the recipes related to `copper ore`:

![copper-recipes](https://user-images.githubusercontent.com/533859/174292408-3f0b5c3e-8ff4-45a5-902a-816bcb67959c.png)

All the recipes about drilling come first, which is tedious because there are many combinations of types of drill, whether you are drilling a mountain or a mine, etc.  The most interesting recipes (that you can make `copper pipe` or `copper wire` from `copper ore`) are buried at the bottom.

I am not quite sure what a good solution would be; I am not even quite sure how to formulate exactly what the problem is.  But it seemed worthwhile to open a discussion.

**Comment by byorgey** [comment]
Yes, that would probably go a long way.  I would suggest listing them in the order

1. Recipes where the entity is an input --- these should go first since the first thing you will want to know when you obtain a new entity is what you can do with it.
2. Recipes where it serves as a catalyst --- for the same reason.
3. Recipes where it is an output --- these should go last, since if you have it, you probably already figured out how to make it.

**Comment by TristanCacqueray** [comment]
I created a related issue in #436 . Perhaps the recipes list could also be ordered by what is currently available, e.g. if you only have a `furnace`, but not a `big furnace`, then the recipes that needs a `furnace` should be displayed first.
