### ISSUE TITLE
Invisibility

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#421]
Robots should have a flag specifying whether they are visible or invisible.  Potential applications include:

- It could be fun to have a (powerful, difficult to construct) "cloaking device" with which a robot can make itself invisible.  This would be merely a curiosity at this point, but could become more interesting/important if we ever add some kind of networked PvP mode in the future.
- More practically, invisible system robots could impart some sort of global dynamicism or interactivity to the world without having to appear in a specific location.  As a simple example, suppose we wanted an additional entity (say, a snake) to spawn in a specific location every 10000 ticks.  We could effect this by having an invisible system robot at the location, programmed to `build` a new snake every 10000 ticks.

Invisible robots obviously should not be rendered, but also should not be detectable by #306 .

**Comment by xsebek** [comment]
I was wondering what is the current approach? How are we hiding system robots?

The best I could quickly come up with for the portal challenge was using the same attribute as the background.

**Comment by byorgey** [comment]
There is no current approach; we don't hide system robots at all.

**Comment by xsebek** [comment]
Oh, so if you grab a tree, then the `.` there is the system robot which self-destructs afterwards and is currently untouchable by other robots.

Could we use a low `priority` display which would put the robot underground so to speak? We currently use high priority for mountain tunnels.

**Comment by byorgey** [comment]
Right, and if we add "creatures" that can move around they will be system robots too.

The priority thing could work in theory (though I'm not sure we have any priority low enough to be drawn "underground" currently).  But it would only solve the issue of not drawing invisible robots; it wouldn't solve the issue of not letting other robots interact with them.  I think adding a new flag to the robot state is the simplest and best solution.
