### ISSUE TITLE
List missing ingredients when `make` fails

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#425]
Currently, when `make` fails because you lack the proper ingredients, you get only a message saying `You don't have the ingredients to make a foo`.

https://github.com/swarm-game/swarm/blob/af2b3ce799275b6cf39a74ceafa5569f308899cd/src/Swarm/Game/Step.hs#L890

It would be nice if the error message also told you exactly what you lacked. Something like this:
```
You don't have the ingredients to make a foo.  Missing:
  - circuit (3)
  - 3D printer
  - quartz (19)
```

I realize this may not be entirely straightforward because there might be multiple recipes for the thing we want to make.  In that case perhaps we should even list all of them separated by OR, like so:
```
You don't have the ingredients to make a foo.  Missing:
  - circuit (3)
  - 3D printer
  OR
  - iron gear (6)
```

**Describe alternatives you've considered**
An alternative is to stick with the status quo, if we decide that figuring out what ingredients you are missing is just part of the game.  But to me, it doesn't seem like a very interesting part of the game if so.

**Comment by xsebek** [comment]
Also, the same message is used if you are missing only the catalyst like the `3D printer` which is slightly confusing.

I would add "(not installed)" there instead of count.
