### ISSUE TITLE
Available recipes and capabilities view

### ISSUE THREAD

**Issue by TristanCacqueray** [swarm-game/swarm#436]
**Is your feature request related to a problem? Please describe.**
Perhaps I'm doing it wrong, but so far, each time i acquire a new item, either through `grab`/`give` or `make`, then i have to go through the entire inventory to see if there is anything new i can make with it.

**Describe the solution you'd like**
I would like to have a "Available" view list, ordered by my the most recently unlocked one, along with a popup message or a notification icon when the list changed. I think that would be more user friendly than having to remember all the different recipes, in particular if we are going to add many more of them.

A similar mechanism could be used for capabilities, when building an installable device, then a similar view can be used to display the new available commands.

**Describe alternatives you've considered**
A more traditional tech tree view could be useful too, but that does not help much when the available recipes are not usable right away.

**Additional context**
Here is a concrete example:
- Get `tree`, list contains `log` recipe.
- Make `log`, list contains `board` recipe.
- Make `board`, list contains `box` recipe.
- Get `bit 0` and `bit 1`, list contains `drill bit`

**Comment by byorgey** [comment]
First of all, let me just point out that when you acquire a new item, you should in theory only need to look at the item itself to find out what you can make with it, rather than looking through the entire inventory.  However, with that said, I think this is a fantastic idea. I'm definitely in favor of anything that makes things in the game more easily discoverable.  The challenge of the game should be the programming, not having to find or remember all the entities and recipes.

A tech tree view might be difficult since (1) we are more constrained by the need to draw things in ASCII, and (2) it's really more of a tech DAG than a tech tree.

Were you thinking in terms of having something that pops up with a hotkey?

**Comment by TristanCacqueray** [comment]
A tech tree would probably also need some sort of science item and research action, but I figured it's worth mentioning as it is also a good system to guide the player.

 For the visualization, how about adding <kbd>F2</kbd> `Recipes` and <kbd>F3</kbd> `Commands` to show the new modal. Then in the help widget, we could add `*` to indicate there is something new?

Then perhaps, in the inventory list, we could also indicate which entities enable something that is not yet available.

**Comment by byorgey** [comment]
All that sounds good to me!

**Comment by xsebek** [comment]
> Then in the help widget, we could add * to indicate there is something new?

Personally, I would see bold orange text easier, but having both would be best for accessibility I guess.

I am fully in favour of adding a new <kbd>F2</kbd> and <kbd>F3</kbd> views :+1:

Could we put the <kbd>F1</kbd>,<kbd>F2</kbd> and <kbd>F3</kbd> hint on the top line, to leave more space on the line between REPL and the World view? It would also make them more distinct, given they would open new modals. :thinking:

**Comment by xsebek** [comment]
> A tech tree would probably also need some sort of science item and research action, but I figured it's worth mentioning as it is also a good system to guide the player.

Well for start we could generate a [DOT file](https://graphviz.org/doc/info/lang.html) from recipes and see how complicated the graph is.
Perhaps it would be useful to design the recipes too. :slightly_smiling_face:  #344
