### ISSUE TITLE
Select inventory items via click

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#446]
After #437, clicking on a panel now shifts the focus to that panel.  It would be nice if clicking on the inventory panel in particular not only switched the focus to the panel, but actually caused the clicked inventory item to be highlighted.  This would obviously require a bit of work to translate a screen click location into an inventory list index.

See https://github.com/swarm-game/swarm/pull/437#discussion_r901157888 .

**Comment by TristanCacqueray** [comment]
Perhaps this could be done by adding a new `Name` constructor for list element so that we can attach a `clickable` instance. That way, the event could contains the element position, and we wouldn't have to deal with the screen position.
