### ISSUE TITLE
Add a info command

### ISSUE THREAD

**Issue by TristanCacqueray** [swarm-game/swarm#460]
**Is your feature request related to a problem? Please describe.**
The problem is that there is no available documentation from the REPL

**Describe the solution you'd like**
A new command, similar to the `help` of the Python REPL, or `:info` of the GHCi would be useful. 

**Additional context**
See #426

**Comment by TristanCacqueray** [comment]
I meant, the new menu proposed in #458 is what i was actually looking for when I started #426, but having an interactive command sounds useful too. I closed #426 to keep the PR backlog tidy, but it's a good starting point for this feature.

**Comment by byorgey** [comment]
Several times I've considered adding special commands to the REPL but decided not to.  For example I thought about adding a `:type` command but instead made the type of the current expression dynamically shown in the top right of the REPL window.  For some reason I just like the idea that everything you type at the REPL is an expression to be evaluated.  So I like Python's `help` as a model, where `help` is "just" a function (of course it's a very magical function, but that's OK, it still feels like you are only ever evaluating expressions).
