### ISSUE TITLE
Get rid of numeric prefixes on scenario file names

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#463]
Currently we put numeric prefixes on scenario file and directory names to make sure they sort in a specific order, then we strip the prefixes before displaying them.  This is a horrible hack, and it means a lot of annoying effort renaming files if we want to change the order.  It also means we have to type annoying things like `swarm -c 01-creative`.

Instead, we should have a special `MANIFEST` file (or some other appropriate name) in each folder whose job is just to specify the order of the other files and folders.

**Comment by xsebek** [comment]
I kind of like how the tutorial is automatically sorted in editor view, but [15b16d9](https://github.com/swarm-game/swarm/pull/411/commits/15b16d9e25ed0f7ec7c950b7e4707885a513f61e) ("Rename all") was not very enjoyable. :sweat_smile:

I would say it is highly likely we will want to insert new challenges or collapse several challenges into a multi-step one. We should definitely address this before that, as it causes a lot of unnecessary effort and also requires renaming in tests, which causes a recompilation. :roll_eyes:
