### ISSUE TITLE
Sand should not be so easy to get

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#474]
Right now, `sand` respawns immediately and infinitely.  This is not very realistic and it also makes it far too easy to get sand.

Perhaps we should make sand more like `rock` and `copper ore`: it does not regrow, but there is a way to produce more of it.  For example, perhaps drilling a `rock` produces some number of `sand`.

**Comment by xsebek** [comment]
I imagined the sand just slowly pours back. Maybe we could increase its growth time and tweak the seed so it does not show the seed and the stem. 😄 

We could also make some rule like “grows with 1 water 1 square away”, so that you could not produce a desert from a grain of sand.

Drilling rocks sounds good too! ♻️

**Comment by byorgey** [comment]
Relatedly, it is nice to be able to "clear" various areas of land (e.g. for farming).  Right now there are various things that can't be cleared:

- sand
- water
- mountains

It would be nice to be able to actually get rid of sand.  Eventually I'd like to make a way to e.g. fill in water with dirt.  Mountains can't be cleared and I think that's OK.

Given this, I'm leaning towards the idea of
- Sand no longer regrows at all
- Make rocks renewable by having a few rocks result from various mining operations, then have the ability to grind rocks into sand.

**Comment by xsebek** [comment]
> - mountains

Huh, I guess these could be in the way if you were creating a big factory. Placing a `detonator` could solve that. :bomb:  Maybe it's some high-energy device, like the hydrogen cell from Terminator 3? :robot: 

Another short story from [Karel Čapek](https://en.wikipedia.org/wiki/Karel_%C4%8Capek) (the inventor of the word "robot") is about [a race of salamanders destroying mountains](https://en.wikipedia.org/wiki/War_with_the_Newts) so they can make the oceans less deep for them to breed. :lizard: 

Exploding mountains to make debris for filling water areas sounds like fun! :laughing:

**Comment by byorgey** [comment]
> Exploding mountains to make debris for filling water areas sounds like fun! 😆

Hah, agreed!  This is a nice idea.
