### ISSUE TITLE
`grabif` primitive to provide a lock/semaphore mechanism

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#479]
**Is your feature request related to a problem? Please describe.**

Consider the following code:
```
b <- ishere "tree"; if b { grab } {}
```
Seems straightforward: we check if a tree is present, and if so, we grab it.   Of course if we just executed a bare `grab`, it might throw an exception when there's no entity present; so that's why we included the `if`.  In contrast to a bare `grab` command, the above code can never crash... right?

Wrong!  There is a race condition here: if our robot's execution just so happens to be suspended in between evaluating `ishere` and executing the `grab`, another robot could `grab` the tree out from under us in the meantime.  The `grab` would then crash when execution resumes.  (Of course we could use `try` to catch the exception thrown by the `grab`, but that's a more advanced feature, and it doesn't really address the fundamental issue, it can only mitigate its impact.)

I am not sure whether I have encountered this in the wild, but I think I possibly may have.  It's very difficult to tell, of course.  But thinking about possible causes of some unexpected behavior led me to realize this issue.

**Describe the solution you'd like**

I would like to have a primitive command `grabif : string -> cmd bool` which **atomically** grabs the named entity if one is present (and does nothing otherwise), returning a `bool` to tell us which happened.  In other words, the test for the entity and the grab happen as one atomic operation which cannot be interrupted.

In addition to resolving the above issue with `grab`, this primitive could be used to implement foolproof locks/semaphores; it is basically the Swarm equivalent of a [compare-and-swap primitive](https://en.wikipedia.org/wiki/Compare-and-swap).   For example, an entity at a specific location in the world can serve as a lock; when a robot needs to execute some critical code, or have exclusive access to some resource, it can first try to acquire the lock by executing `grabif`.  Even if multiple robots try to grab the lock at the same time, exactly one of them will succeed.  Once the robot is done it can simply `place` the item to release the lock.

As another example (this was my original motivating example), `grabif` can also be used to program safe resource acquisition from a "depot".  The depot is programmed to place a certain resource whenever its cell becomes empty.  Other robots wishing to acquire the resource can come to the depot, wait for the resource to be placed, and then grab it.  However, using separate `ishere` and `grab` instructions, the race condition is a problem: if multiple robots come to acquire the resource at the same time, there is a chance that one of them will crash when it tries to grab the resource that it thinks is there but which has actually just been grabbed by the other robot.  If the robots use an atomic `grabif` instruction instead, this problem cannot happen.

**Describe alternatives you've considered**

I suppose there are other atomic primitives we might consider that could be used to implement similar features, but I have not thought much about this area before.

We might also consider a corresponding `placeif` which atomically does a `place` only if the cell is empty; doing an `ishere` test followed by a `place` suffers from the same race condition as the version with `grab`.  On the other hand, it is possible to implement `placeif` using `grabif`: have an item at location 1 serve as a lock; if a robot wants to attempt to place an item at location 2, it must first acquire the lock using `grabif`, and only then can it attempt to place an item at location 2.

**Additional context**

The only additional question is what capability should be required, and what device(s) might provide it.  It seems natural to say it should require *both* the `sensehere` *and* `grab` capabilities, but I literally [just got through saying](https://github.com/swarm-game/swarm/pull/458/files#r906234923) that we should just make every command require at most one capability. :facepalm:   So I guess I'll put my money where my mouth is and suggest that we make a new device, called, um... a `smart grabber`?  (bikeshedding welcome), with the recipe `smart grabber = scanner + grabber`, that provides the `grabif` capability.

**Comment by TristanCacqueray** [comment]
I would be happy to revert my change and support multiple capabilities requirement. I don't mind either way.

**Comment by xsebek** [comment]
I think it could work either way, it’s just about which design choice will be easier to use for future capabilities and will cause us less headache.

I am still not sure the metal drill was a good idea, hopefully its not too buggy.

**Comment by byorgey** [comment]
> I wonder if we could implement an `atomic` function that would take a command sequence and (if it was allowed) execute it all in one tick.

I thought about that.  The problem I see is that it might be easy to accidentally put some code inside `atomic` that takes a long time (even an infinitely long time! :fearful: )  to execute, which would cause all the other robots to freeze.  Using `grabif`, you can kind of implement your own `atomic` (relative to other robots who care) using a lock, which can't cause the game to freeze.

As for requiring multiple capabilities vs requiring a new device, I actually kind of like the idea that simply having a `scanner` and a `grabber` (which you will have at the start of the game) doesn't automatically let you use `grabif`. You have to intentionally decide to consume a `scanner` to make a `smart grabber`.  (I am imagining that a smart grabber will still give you the same capabilities as a `grabber`, with one additional capability, but it will *not* give the capabilities of a `scanner`.)

**Comment by byorgey** [comment]
> because those can then install or not depending on timing of any building robot.

I want to make sure I understand --- you mean *e.g.* if you `build` a robot that executes the `drill` command, then you either get a `drill` or a `metal drill` installed depending on which you happen to have in your inventory?  I think that issue could be solved by #201 --- you can just say `require "metal drill"` and then you will be sure to get the specific device you requested.

**Comment by xsebek** [comment]
@byorgey Yes, #201 and #480 should hopefully make sure that it works deterministically as expected. But I have not played much through the game, so I don't trust it yet. :smile:

> The problem I see is that it might be easy to accidentally put some code inside atomic that takes a long time (even an infinitely long time! :fearful: ) to execute, which would cause all the other robots to freeze.

Well, I was proposing to ban any such commands, particularly any user-defined commands (so no recursion). It should suffice to `grab`, `place`, `scan`, `blocked`, `whereami`, `has`, `count`, `turn` and all the pure functions including `if`.
This would not even include `try` and should be restrictive enough while giving more flexibility than `grabif` and hoping other robots follow the same protocol flawlessly.

**Comment by byorgey** [comment]
> Well, I was proposing to ban any such commands, particularly any user-defined commands (so no recursion).

Ah, interesting.  Yes, I think that would work.

I agree `grabif` is much easier to implement (in fact, it is quite trivial), so we should probably just do that first.  Implementing `atomic` would definitely be more involved.  It couldn't even just be a function, it would have to be a special built-in syntactic form, because of the need to check the argument to make sure it didn't have any "banned" commands.  Then when we get around to executing it we have to do something like set a flag so we do not decrement the robot's allocated steps for the current tick until completing it.

**Comment by byorgey** [comment]
So now that we have merged #503 , I guess we would need `harvestif` in addition to `grabif` and `placeif`?  @xsebek 's idea to just implement a generic `atomic` primitive is starting to look better to me.

**Comment by byorgey** [comment]
So I've implemented an `atomic` wrapper, but unfortunately at the moment it's not possible to use it to implement `grabif`!  To prevent infinite recursion etc., it forbids referring to any variables defined outside the atomic block. But that means this would be invalid:
```
grabif : string -> cmd bool
grabif = \thing. atomic (b <- ishere thing; if b {grab; return true} {return false})
```
because the atomic block refers to the variable `thing`, which is not bound inside the block.  In *this* example it is obviously fine, but I am having trouble coming up with a sensible, elegant way to allow the above definition of `grabif` but still rule out other things we don't want.

**Comment by byorgey** [comment]
Hmm, maybe we can allow references to external variables as long as they have a primitive, first-order type such as `string`, `int`, etc.?  Since swarm is strict, we know any such variables have already been fully evaluated before entering the atomic block.  As long as we disallow references to variables with function types, delay types, etc. we should be OK.  I will try that.
