### ISSUE TITLE
Make `counter` easier to construct

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#481]
`counter` devices are useful on their own, as they let you count how many of an item you have (though there are ways around this), and they also can be used to construct a `calculator` which is extremely useful.  However, a `counter` requires a lot of bits (8 of each) and bits grow slowly.  For comparison, here are the current [min,max] growth rates for various entities:

```
flower: [30, 50]
lambda: [100, 200]
tree: [500, 600]
bit: [1000, 1500]
pixel: [1000, 1500]
LaTeX: [2000, 3000]
```

To me it feels a little unbalanced --- to construct counters at the rate I would like, I would need a really massive bit harvesting operation.

There are a couple ways I can think of to make things more balanced:
- Require fewer bits for a `counter`.  (Though I kind of like the number 8 here; it feels like it makes sense that a `counter` can hold 1 byte.)
- Make bits grow faster.  I'm thinking something like `[200, 400]`---slower than lambda but faster than trees.

Open to other suggestions as well.

**Comment by TristanCacqueray** [comment]
Perhaps a device could be used to trigger the respawn? For example a robot with a magnet could force the creation of bit when used at a empty bit location. Well I'm not there yet, but could that be a simple initial thing to automate?

Otherwise increasing the growth sounds better than reducing the counter cost.

**Comment by byorgey** [comment]
Hmm, that's an interesting idea, that maybe the way to "grow" bits is different than the way that other things like trees grow...

**Comment by xsebek** [comment]
I agree it should grow a bit faster :+1:

Also do you not require two of them with opposite parity for pretty much anything? Being able to flip the bit would simplify the planting logistics, even if it was costly. :slightly_smiling_face:

**Comment by byorgey** [comment]
Hmm, I do like the idea of being able to flip bits.  How would it work?  Maybe you have to heat them up, like `1 log + furnace + bit (0) -> bit (1)` and vice versa?  Hmm, no, that's kind of boring, that's already how we make copper wire, iron plates, etc.  @TristanCacqueray mentioned magnets above, what if we turn a few of the `rock`s into `lodestone`s (like, maybe 1 out of every 10 rocks is now a lodestone) which can be used to flip bits? Like, `bit (0) -- lodestone --> bit (1)` (with the `lodestone` as catalyst).  `lodestone` would also make a good addition to the `compass` recipe, perhaps.

**Comment by byorgey** [comment]
OK, I went ahead and made bits grow faster.  I'm leaving this issue open in case we want to keep discussing a way to flip bits into each other.
