### ISSUE TITLE
Give the player control over whether growable entities regrow

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#490]
After some discussion in the comments, I am refocusing on the central issues:

- The player ought to be able to control when and where growing things regrow (except for instantly regrowing things like water).
- I think *not* regrowing ought to be the default.  If the player wants to farm things, they have to do a bit more work.

Below is my original proposal for a `harvest` command, though that is not the only possible solution (and indeed, probably not the best solution).  I would be happy with any solution that fulfills the above two criteria and does not complicate things too much.

Original `harvest` proposal
------------------------------------

**tl;dr**: I propose providing both a `grab` command and a `harvest` command.  The former would simply remove an entity from the current cell; the latter would leave behind a seed if the entity is growable (*i.e.* what the `grab` command currently does).

We could simply have both commands provided by a `grabber`; or, perhaps a better idea would be to have a `grabber` only provide `grab`, whereas to `harvest` you need to build a `harvester` device, which would have some suitably simple recipe (e.g. something you can make out of a few trees) since it would be one of the first things you want to build.

Motivation
--------------

- This would greatly simplify the process of clearing an area for farming.
- It turns out that having growable entities *always* regrow *every* time you grab them is limiting and annoying.  Read on for the full story of how I realized this below.

Backstory
--------------

I had an issue with my tree and bit harvesting operations.  It would work fine for a while but then the flow of trees or bits would slow to a trickle.  It took me an embarrassingly long time to figure out what was wrong, but with the help of #483 I was able to figure out which robot was failing, and then with some loggers I was able to find the exception that caused it to fail.  Once I knew that I figured out the rest pretty quickly.

As [described here](https://github.com/swarm-game/swarm/issues/393#issuecomment-1161845144), I have come up with a simple scheme to support pull-based manufacturing: a *provider* robot obtains some resource somehow, and then it sits on a particular square and places one entity.  When it notices the cell is empty, it places another entity, and so on.   Other robots that want to obtain the resource come to the square, wait for an entity to appear, and then grab it.  (Of course the grabbing should happen atomically, as in #479 , but that's not the issue here.)

My tree processing operation involves 5 robots, but for the purposes of this story you only need to know about three:
- A harvester robot continually goes over a rectangular plot of trees, harvesting any trees that grow, and giving them all to the tree provider robot.
- The tree provider robot sits in the same place and acts as a tree provider (in the sense of the description above).
- Another tree processing robot obtains trees from the tree provider, processes them into branches and logs, then gives the results to some other robots.

This worked fine for a while but it seemed to stop working eventually.  I suspected some kind of race condition but I couldn't figure it out. After we merged #483 , I was able to determine that eventually it was the tree provider that switched to `idle`, i.e. it had crashed, and trees just started accumulating in its inventory. Mysteriously, though, the tree processing robot still occasionally processed some trees.  Once I put a logger in the tree provider robot, I found out that `place` was crashing with the message `There is already an entity here`.  But I didn't know how that could be possible --- the tree provider was the *only* robot that ever `place`d anything in that cell.  The tree harvester would simply `give` its trees to the tree provider, and the tree processor would only ever `grab` trees placed by the provider.

Have you figured it out yet? :smile: 

It suddenly dawned on me that every time the tree processing robot `grab`bed a tree from the cell of the tree provider, a seed started to grow!  In fact, after a while, there would in theory be a whole bunch of tree seed robots all growing in that same cell.  It was just a matter of time before encountering the standard `grab`/`place` race condition (#479) --- the tree provider would be interrupted just after testing the cell and finding it empty; a tree seed would then finish growing; and hence, from the tree provider's point of view, a tree grew in the instant in between checking to make sure the cell was empty and executing `place`.  The tree processor kept working since trees still kept showing up in the provider cell.  Probably even more than one were growing concurrently, so it was more than we would get from harvesting a single tree, but the overall effect was a much reduced throughput.

So part of the solution could of course be a `placeif` primitive like in #479 .  That would prevent the tree provider from crashing in this case.  But we also just really don't want trees to regrow in the tree provider cell. At that point, we want to just think of them as a commodity to be passed around, not as something that should grow.

Lessons learned
----------------------

- Shared memory concurrency is hard.
- Good debugging tools are worth their weight in `mithril`.

**Comment by xsebek** [comment]
How would harvest/place work with water, which is AFAIK an instantly growable entity?

I would prefer not to complicate things with a harvester device if possible.

I think we should make the seed a physical entity and remove the seed robot when the seed entity is grabbed.
Presumably, seeds are small so you could place other things on them and the seed would be destroyed.
That to me seems like the safest way to sort out the parallel seed problems.

**Comment by byorgey** [comment]
Hmm, good question, I honestly forgot about water.

Making a seed a physical entity is an interesting idea. What if we do something similar to Minecraft, where grabbing a `tree` also yields one or more `tree seed`s.  Placing a `tree seed` then generates an invisible system robot that causes the seed to turn into a tree at some point in the future.

I'd like a solution that does not *automatically* create a seed every time you grab a growable entity.  In other words, I think things *not* growing back should be the default, and if you want to grow things you have to do some extra work, instead of having to do extra work to kill off things that you don't want to grow.

**Comment by TristanCacqueray** [comment]
Could we also have `plant` to place growable entities, where `place` would not trigger the regrowth process? Or perhaps `drop` to place an entity without regrowth, and keep `place` as is.

**Comment by byorgey** [comment]
@TristanCacqueray can you elaborate? I'm not sure I understand what you propose for `plant` to do.

**Comment by TristanCacqueray** [comment]
If the user `plant` a tree, then `grab` would leave a seed and a new tree will appear after some time.
If the user `place` (or maybe `drop` is a better name) a tree, then `grab` would not leave a seed.

**Comment by byorgey** [comment]
OK, I see.  That makes a lot of sense from a "real world" point of view --- when you `plant` a tree, it is standing in the ground, alive, and it might leave some seeds behind; when you `drop` a tree, it is just lying there, and picking it up does nothing.  However from a gameplay point of view it seems too complicated.  We would basically now have to keep track of two kinds of trees.  Making them be different entities seems too complex (what would we call them?  `live tree` and `dead tree`?  What happens if you `plant` a `dead tree`? How would we record the relationship between them in `entities.yaml` and `recipes.yaml`? etc.).  On the other hand making them the same entity means there is some hidden boolean we have to keep track of.  How would we keep track of it?  How would the player be able to tell the difference?

**Comment by TristanCacqueray** [comment]
I see, then it seems like we would need a new mechanism to handle things that are dropped. Then I think `harvest` is a better solution. I meant to mention `plant` as a brainstorm idea.

**Comment by byorgey** [comment]
> I meant to mention `plant` as a brainstorm idea.

Of course, and it's a great idea.  Definitely helped me think more carefully about what it is I really want in this issue.

Just to summarize at this point, I think there are 3 viable ideas that have been mentioned.

1. Make seed entities that spawn as soon as you grab a growable item, but which can be easily stopped from growing (e.g. by grabbing them or by placing something on top of them).
2. Make a `harvest` command.
3. Make seed entities that drop when grabbing a growable item, and grow a new entity when placed.

In my opinion, these are ordered from simplest to most complex.

- To accomplish (1), all we would need to do is make a new `seed` entity, and program seed robots to place one as soon as they start running, and self-destruct if the seed ever disappears.  So this definitely seems like the simplest solution, though I don't prefer it since it still has regrowth as the default, with extra work required if you *don't* want something to regrow.  More on this below.
- For (2), we could add a new `harvester` device with a recipe, providing a `harvest` command that would cause the harvested thing to regrow.  This still feels pretty simple to me --- one additional device + command; and the code for `harvest` and `grow` could literally be the same, they would both just call a function that does what `grab` does now, but with a parameter specifying whether it should try to regrow things or not.
- (3) is a little more complex, because we would apparently need a new kind of `seed` entity per growable thing (i.e. we need `tree seed` and `lambda seed` and ...) with a way to specify in `entities.yaml` which entity is a seed for what, etc.

Definitely still open to other ideas.  

Let me say a little bit more about why I want regrowth to no longer be the default.  For robots to work together, they need to communicate.  Eventually we may have things like printers (#116) and wireless communication (#94), but we don't have those yet, and even when we do have them you will not be able to use them until later in the game.  Barring those things, one of the easiest ways for robots to communicate is by placing and grabbing entities in prearranged locations.  So you end up wanting to write generic functions for grabbing and placing things, that will work for any entities.  It is therefore very annoying if certain entities will always generate a seed when grabbed, and others will not.  To make a truly generic entity-processing function, you have to write a bunch of conditional code to somehow get rid of any seeds that appear.  (1) above at least makes this relatively easy (much easier than the status quo), but it would be so much nicer if we didn't have to worry about it in the first place.

**Comment by xsebek** [comment]
Just to clarify on 1. I think seed entities tackle a different aspect of the problem of "placing tree breaks communication".

The problems are (and @byorgey please correct me if we handle these currently):
1. there could theoretically be more seed robots in the same place
2. once there is a seed it could sprout after the entity was placed and removed
3. you can not sense the seed, so stuff like atomic `placeif` is needed and its also weird

Basically, robots do not block placing entities and are not destroyed by them, but seed robots should be.
Tying them to entities could make the game more consistent.

I think this would be a separate improvement that could work with current grab, future harvest or Minecraft-like obtaining seeds.

---

> with a way to specify in `entities.yaml` which entity is a seed for what, etc.

IMHO  `growable` should be enough to allow us to post-process entities list and add the seed entities.
Or just ignore them at the start and then dynamically add them to the entity map unless there is already a seed there.
I might want to try some post-processing of recipes for #480, so we will see how hard that is. :slightly_smiling_face:

**Comment by byorgey** [comment]
Ah, yes, the thing about having multiple seed robots in the same place is indeed weird.  I hadn't even thought about that possibility until typing up this issue.  I'm not as concerned about it because it doesn't really cause any problems that I know of, and it even seemed like maybe it could be a fun hidden feature, like you can do "intensive farming" if you repeatedly place and grab a growable entity on the same spot and then sit there harvesting each one as soon as it grows.  :laughing:  But it still is a bit strange and I'm definitely fine with getting rid of that possibility.

Re: (3), the reason atomic `placeif` is needed has nothing to do with whether you can sense the seed, it is needed regardless.

Anyway, I agree that having seeds be physical entities would be a nice improvement.  And post-processing the entities list to add seeds is a good idea.  In which case maybe idea (3) is not so complex after all.
