### ISSUE TITLE
Web based debug interface

### ISSUE THREAD

**Issue by TristanCacqueray** [swarm-game/swarm#493]
**Is your feature request related to a problem? Please describe.**
Being able to debug complex issue, such as the one described in #490 might become tricky to do with the ncurses based interface.

**Describe the solution you'd like**
The game starts a wai application that can be used to query the current game state. Initially the interface provides a simple `/export` endpoint to dump the state. But the interface could also serve a little web ui to display the state through a web browser.

**Describe alternatives you've considered**
With #50, we might be able to inspect the save file for debug purpose too. Though the web service might be more convenient to debug live situations.

**Additional context**
The web service could also receive REPL commands so that the IDE could directly interact with the game, without having to switch focus and use the `run` command.

It also open the possibility of a new web base interface for the game. Though that is a subject for another discussion, the purpose of this issue is purely for adding a debug capability.

**Comment by TristanCacqueray** [comment]
Note that we can mostly avoid adding javascript and html to the project by using [lucid](https://hackage.haskell.org/package/lucid) and [htmx](https://htmx.org/).

**Comment by xsebek** [comment]
Another great improvement from separating UI and state would be the possibility to open game windows (entity description, goal, robot list,...) in a separate terminal. I think that Dwarf fortress has something like that.

Once the TUI application can communicate with a separate state-holding application you almost have a multiplayer game! :rocket:

**Comment by byorgey** [comment]
So we definitely have a very simple version of this now.  I'm wondering what other features people want in this vein, or if we can close this issue.

**Comment by byorgey** [comment]
I think I'm going to close this issue now, since we do indeed have a simple web debugging interface, with new features being added to it regularly.  If there are specific features anyone would like to see added to the web UI we can of course open specific issues to track those features.
