### ISSUE TITLE
Add 3D printer recipe

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#496]
Let's add a way to create more 3D printers to let more robots build robots (and solar panels).

Suggested recipe by @byorgey in #26:

> Idea for `3D printer` recipe:
> - `printer` (see #116)
> - 5 `circuit`
> - 1 `iron plate`
> - 3 `copper pipe`
> - 16 `iron gear`

**Comment by byorgey** [comment]
I no longer think a `3D printer` should require a `printer`.  Now I'm thinking perhaps the recipe for `3D printer` should just be like a scaled up, more difficult version of the recipe for `printer`.  For example:

- `printer`:
    - 1 `circuit`
    - 1 `board`
    - 8 `wooden gear`
- `3D printer`:
    - 4 `circuit` (one to control each axis and one to control the extruder :smile: )
    - 1 `iron plate`
    - 3 `copper pipe`
    - 16 `iron gear`
