### ISSUE TITLE
Add randomness device

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#497]
We are missing a device and recipe for the `random` command (and capability).

Proposed recipe:

- `bit (0)` + `bit (1)` + `gold coin` --> `bitcoin`
- `gold` | `furnace` ---> 8x `gold coin`

Gold is almost the hardest thing to get, but I do not want to miss the opportunity to make golden bitcoin the randomness provider, so let's at least give many gold coins from one gold nugget. 

Suggestions are welcome, particularly on the (not so though out) gold part. :slightly_smiling_face:

**Comment by xsebek** [comment]
Funny idea: add separate devices copper/iron/golden bitcoin that would have progressively better randomness.

So copper only goes 0/1 and maybe is a bit more likely to go 0, iron still goes 0/1 but is balanced and golden bitcoin allows up to 2048 bits as random as we can get.

**Comment by byorgey** [comment]
Haha, I love it!

**Comment by byorgey** [comment]
I wonder if `₿` would be supported in most fonts.  Otherwise,  we might consider using `©`.

**Comment by xsebek** [comment]
I want to finish this for #26, but I think I will leave multiple coins after #480.
