### ISSUE TITLE
Add a way to visualize a robot's currently executing program

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#5]
That is, a way to display the current state of the CEK machine for the focused robot.  This would require first overhauling CEK machine pretty-printing.  I am imagining showing the continuation stack as *nested* frames rather than a sequence of frames.  For example given the program `let x = 3 + 2 in x * 4`, when we are currently focused on evaluating the `3`, we could imagine something like
``` 
[let x = [[3] + 2] in x * 4]
```
or maybe even without all the brackets except the ones around the 3.  This would probably require some creativity in certain cases but I think it could be done in a nice, compact way.

The second part of this would be devising ways both (1) for the user to possibly choose whether they want to see this, and (2) figuring out a good place for it in the UI.

**Comment by byorgey** [comment]
Perhaps it should only be enabled when pausing and single-stepping the game.

**Comment by byorgey** [comment]
Maybe we could have a "debugger" or "tracer" device or something of that sort.  Then, when viewing a given robot and focusing on that installed device, the current machine state would show in the text box at the bottom left of the UI.

**Comment by byorgey** [comment]
I split out the idea of better CESK pretty-printing into #644.

**Comment by xsebek** [comment]
@byorgey as to where it should be placed in the UI, I would suggest the robot modal, but only show it for selected robots.

Imagine you open the list, scroll to the desired robot, hit <kbd>I</kbd> and the one robot line expands to few more lines showing (likely rapidly changing) pretty printed CESK stack.

**Comment by byorgey** [comment]
Having CESK debugging info show up in the robot modal makes sense, and the motivation of wanting to inspect several robots quickly makes sense.  However, it wouldn't be good if the robot modal was the only way to view pretty printed CESK machines, because the modal hides your view of the world.  I can easily imagine wanting to single-step the game while seeing what a robot is doing in the world and also viewing its CESK machine.

**Comment by xsebek** [comment]
Good point, both are good. :+1:

**Comment by xsebek** [comment]
Btw. how about increasing the priority, since it would have been so handy for debugging? :slightly_smiling_face: 

Also, it seems to me like a very interesting thing from players' perspective, as it allows them (me really) to understand the evaluation model better.

**Comment by byorgey** [comment]
I started working on this in `feature/tweezers`.  One difficulty I realized is that even when you pause and single-step the game, you are still only stepping at the granularity of *game ticks*, not individual CESK machine steps.  So it can still be a bit difficult to tell what is going on since the CESK machine may take up to 100 steps per game tick, especially when it is doing a bunch of internal computation and not causing external commands such as `move` to happen.  Off the top of my head I'm not sure what would be needed to allow single-stepping the current robot's CESK machine.

**Comment by xsebek** [comment]
>  you are still only stepping at the granularity of game ticks

I thought about this too, it would be nice to see how the CESK changed over the last tick (or a few ticks).

Assuming it does not take up too much space, I suggest we list some number of previous states.

**Comment by xsebek** [comment]
> Off the top of my head I'm not sure what would be needed to allow single-stepping the current robot's CESK machine.

If we want to preserve game flow and time mechanics, then we would need to have an alternative mode:
```Haskell
data TimeMode = Running | StepWorld | StepRobot RID Int -- remaining steps for robot in current tick
```

Once the remaining steps for the robot reach zero, we would go through the robots after it, return to the beginning and go through all the robots again. 

It would be like the ordinary world stepping by ticks _with an extra counter_ for the robot steps once we reach it.

**Comment by byorgey** [comment]
> I suggest we list some number of previous states.

That could be a bit awkward since we would have to save the previous states somewhere just in case we wanted to display them later.

> If we want to preserve game flow and time mechanics, then we would need to have an alternative mode:

Hmm, yes, I think something like that could work.

**Comment by xsebek** [comment]
@byorgey yes, I was thinking about keeping a fixed number of those only for the selected robot from the moment the game was paused. I agree it might lead to memory issues if done incorrectly.

Alternatively, a Web API could be used to query the pretty printed CESK machine state, but it might be a bit harder to get it in every step.

**Comment by xsebek** [comment]
@byorgey I saw you put the pretty CESK in the `tweezers` panel like `logger`. To me, it feels a bit small there. It also does not show in the pop-up so it gets hidden off the edge of the screen:
![image](https://user-images.githubusercontent.com/44544735/216619925-cd3d4eb2-b715-4e10-8a27-11b26ef3a02a.png)

If there is any `log` in the computation the focus will shift to the logger, which might be a bit distracting/annoying.

Since REPL is not doing anything else useful and will show `...` the whole time, maybe it could be shown there? :slightly_smiling_face: 

Sorry for being nosy and not waiting for the final PR. :smile:

**Comment by byorgey** [comment]
Good ideas!  Yes, I agree this needs a lot of improvement, this was really just a MVP to play with the idea.  I don't even know if I'm going to finish it any time soon; if you have ideas and motivation feel free to work on it!
