### ISSUE TITLE
`build` does not always install a minimal set of devices

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#508]
For example, a `grabber` and `harvester` might both be installed when the `grab` and `harvest` capabilities are needed, even though a `harvester` already provides both capabilities.  It would be nice if the analysis figured out that it could get away with just installing a `harvester` alone.

Note, this depends on merging #503 , where this problem was first noted.

To reproduce, make sure you have a `harvester` in your inventory, then execute `r <- build {grab; harvest}; view r`.  You can see that the newly built robot has both a `harvester` and a `grabber` installed.

...actually, I am not sure whether this is a problem.  Right now, *every* robot has a `grabber` installed whether it needs one or not.  We will have to see if this is still a problem after merging #361 .

**Comment by byorgey** [comment]
The test we added (`508-capability-subset`) actually *succeeds* and I don't yet understand if it's because the bug is not a bug, or if it just so happens to succeed but another similar test would fail.

**Comment by xsebek** [comment]
@byorgey it seems to me like the harvester commit fixed it. :smile:

**Comment by xsebek** [comment]
I guess we could wait for #361 to be merged and if everything works then, we would close this issue.

But I suspect we just got lucky with the current order of entities and other capabilities/devices will not work.

**Comment by byorgey** [comment]
Yeah, I suspect the same thing.  I want to at least spend some time studying the code to think about what it does, and maybe come up with a failing test case if I can.

**Comment by byorgey** [comment]
In general, if the result depends on some arbitrary order, and can change when other unrelated entities are added, I would consider that a bug in and of itself!

**Comment by byorgey** [comment]
Hah, OK, so I looked at the code and indeed it depends on the order of the entities for each capability.  But the entities are stored in a `Set Entity`, and hence ordered by *hash*.  😄   Obviously this is very unpredictable and could change if, say, someone edited the punctuation in the description of one of the entities.

**Comment by byorgey** [comment]
My idea for solving this is to add a minimization post-processing step.  After figuring out which capabilities we need, and then finding which devices that we have could provide each capability, we end up with a collection of non-empty `Set Entity`, one per capability.  That is, for each capability, we have a set of devices which are in our inventory that would provide that capability.  Right now, we simply convert these sets to lists and choose the first device from each set, which guarantees that every capability will be covered.  Instead, we can do something like this:
- If there are any singleton sets, those devices must be chosen, so add them to a set $D$.
- Now go through each of the remaining sets.
    - If a set $S$ contains at least one device which is already in $D$, we can simply use that device, so ignore $S$ and move on.
    - Otherwise, arbitrarily choose an element of $S$ and add it to $D$.

That's the simple greedy version, which will probably work just fine in practice, though it is not optimal in general.  More generally, the problem is, given a collection of sets $S_i$, to find a set $D$ such that (1) $D$ has a non-empty intersection with each $S_i$, that is, each $S_i$ has at least one element in common with $D$, and (2) $D$ is as small as possible.  This is called the [Hitting Set Problem](https://en.wikipedia.org/wiki/Set_cover_problem#Hitting_set_formulation), and it is NP-complete.  I think the non-optimality of the greedy algorithm I outlined above would only be relevant if we had lots of devices providing overlapping sets of multiple capabilities.  But in fact the vast majority of our devices only provide a single capability, and there are very few cases of devices that provide overlapping capabilities.

**Comment by xsebek** [comment]
Sounds good, I think we could get an even better version if we chose the one with most capabilities - or with #480 the upgraded version.

**Comment by byorgey** [comment]
> we could get an even better version if we chose the one with most capabilities - or with #480 the upgraded version.

Yes, that's true, any additional heuristics like this will help.

**Comment by byorgey** [comment]
I'm planning to address this as part of my work on #201 since I will be touching all that code anyway.
