### ISSUE TITLE
Revive message queue

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#513]
From #26:
> I was thinking `say` would become useful as a global God log (we could read `messageQueue` in some pop-up creative window) and check in the tests (no log required). Maybe other robots could hear you too if they are nearby and `listen`.

- add an <kbd>F7</kbd> window where the message queue would be shown in cheating/creative mode
- consider using `LogEntry` instead of raw `Text`, which could help with message formatting:
    ```Haskell
    Say -> case vs of
      [VString msg] -> do
        rn <- use robotName -- TODO: use robot name + ID
        emitMessage (T.concat [rn, ": ", msg])
    ```
- bonus: add a `listen: cmd (robot * string)` command that would allow you to hear other robots `say` something

**Comment by noahyor** [comment]
If we implement paper/printers (referenced in #455) then I think that having a say command wouldn't be a good option.

**Comment by xsebek** [comment]
@noahyor please expand, I do not see your point?
