### ISSUE TITLE
Build fails on prepositive `qualified` in autogen module with `cabal` < 3.6

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#528]
This is what happens when I do `stack build`:

```
10:40:36 starting   stack test --fast --flag=swarm:ci
Building all executables for `swarm' once. After a successful build of all of them, only specified executables will be rebuilt.
swarm> build (lib + exe + test)
Preprocessing library for swarm-0.1.0.0..
Building library for swarm-0.1.0.0..
[ 1 of 37] Compiling Paths_swarm
            
/home/brent/projects/swarm/.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.4.1.0/build/autogen/Paths_swarm.hs:11:8: error: [-Wprepositive-qualified-module, -Werror=prepositive-qualified-module]
    Found ‘qualified’ in prepositive position
    Suggested fix: place  ‘qualified’ after the module name instead.
   |        
11 | import qualified Control.Exception as Exception
   |        ^^^^^^^^^
Progress 1/2

--  While building package swarm-0.1.0.0 (scroll up to its section to see the error) using:
      /home/brent/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_3.4.1.0_ghc-9.0.2 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.4.1.0 build lib:swarm exe:swarm test:swarm-integration test:swarm-unit --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
10:40:36 exited:    failed: 1
10:40:36 took       0.55s
```

-  It works if I use `cabal-3.6.2.0` to build directly.  
- But I noticed that the above build is using `cabal-3.4.1.0`. If I downgrade to that version and try `cabal build -fci`, it fails with the same error as above.

So I think this is not really a `stack` vs `cabal` thing, it's just that only the latest version of `cabal` works, and `stack` has its own idea about which version of `cabal` it wants to use with specific versions of GHC.

Is there a way we can turn off the `-Wprepositive-qualified-module` only for the autogenerated `Paths_swarm` module?

**Comment by byorgey** [comment]
Or maybe we should just disable `-Wprepositive-qualified-module` for now?

**Comment by xsebek** [comment]
We could separate Paths into another library with `-Wnoprepositive-qualified-module` that we would then import.

We could also add a `STACK` flag and keep the warning behind `if not flag(STACK)` or only check that if `flag(CI)` but that would be annoying locally.

**Comment by byorgey** [comment]
It's not really possible to write `getDataDir` and `getDataFileName` by hand, because they depend on the specific location in which the files were installed, which for example for me is currently something like `/home/brent/projects/swarm/.stack-work/install/x86_64-linux-tinfo6/4212aaa36a7f04e7fbf2edcd31a2fd5134b2a6441641e98e01d7958fcad65c55/9.0.2/share/x86_64-linux-ghc-9.0.2/swarm-0.1.0.0`.  That's why they have to be autogenerated.

Separating `Paths_swarm` into a separate library with different flags sounds like it could work.

**Comment by byorgey** [comment]
I tried putting `Paths_swarm` in a separate internal library but I could not get it to work.
