### ISSUE TITLE
Highlight commands in descriptions

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#545]
I want the commands in descriptions (entities, goal) to be highlighted instead of surrounded with ticks.

For shorter descriptions, it does not matter, but with longer ones like the goal or grabber device, I find it hard to read.

This would also be a good opportunity to use backticks to disambiguate them from normal ticks that English uses and be compatible with Markdown syntax.

As a small code refactoring, we could call the attribute "highlight" instead of using the robot attribute. :sweat_smile:

*update, 15 May 23*: Collecting some related links here for easy access: #309, #574, https://github.com/jtdaugherty/brick/issues/400, #1106

**Comment by byorgey** [comment]
Related: #309 .

**Comment by xsebek** [comment]
Just to be clear about the higlight attribute, there is a `highlightAttr` that means cyan foreground and `robotAttr` that means bold white foreground, which is used as bold for some table headers. I think it is funny, but not very readable. :sweat_smile:

**Comment by byorgey** [comment]
Yeah, we should add a new `bold` attribute or something.  Agree we should not use `robot` attribute for so many things!

**Comment by byorgey** [comment]
Note, the difficulty with applying attributes to things in descriptions is that we have to give text to a function that does the text wrapping and constructs a widget.  So we have no opportunity to apply formatting to individual words.  This might require some kind of upstream PR to `brick` to give us the functionality we need.

**Comment by xsebek** [comment]
Well at least the triple backtick examples should be doable with separate widgets.

I wonder if we could compose widgets so that they would still look like text and create our `markdownTxt` function to do it where relevant. That might be useful enough to publish as an open-source library. :smile:

**Comment by byorgey** [comment]
> Well at least the triple backtick examples should be doable with separate widgets.

Maybe?  I am not 100% sure how easy that will be.



> I wonder if we could compose widgets so that they would still look like text and create our `markdownTxt` function to do it where relevant.

I'm not sure I understand what you mean.

**Comment by xsebek** [comment]
I thought we could layout parts of the text to look like one text.

But looking at [`str`](https://hackage.haskell.org/package/brick-0.70.1/docs/src/Brick.Widgets.Core.html#str) it might be necessary to create a custom rendering function for the widget - some bit more complicated version of `Text` -> [`Image`](https://hackage.haskell.org/package/vty-5.35.1/docs/Graphics-Vty-Image.html#t:Image). But we should look through the [brick projects](https://github.com/jtdaugherty/brick/blob/master/README.md#featured-projects) if someone did not figure this out already. :thinking:

**Comment by xsebek** [comment]
I split out the easier part for highlighting code blocks.

As a prerequisite, we should change the inline code to use backticks, so that we can at least find it and get markdown support for free. AFAIK we only use it for valid swarm commands, but in case we wanted to support more languages, Pandoc has an [Extension: inline_code_attributes](https://pandoc.org/MANUAL.html#extension-inline_code_attributes) that looks like this:
```markdown
Try typing `build {}`{.swarm} - ...
```

**Comment by byorgey** [comment]
I think at this point most (all?) of the inline code in entity descriptions, tutorial goal text, etc. has been converted to use backticks.

**Comment by xsebek** [comment]
@byorgey thanks for updating on this. 👍 

Next up, we need new data structure to represent text that has parts of it code.

---
After that we have to wrap _that type_ by lines (not widgets). Once we have lines those can be turned into widgets.

Or we wait a little while until brick/other library makes the wrapping and assigning attributes easier for us.

---

This is mostly a TLDR of the discussion in jtdaugherty/brick#400.
