### ISSUE TITLE
`teleport` does not update `robotsByLocation` map

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#555]
The `robotsByLocation` map in the `GameState` is supposed to be kept up to date with the robots at each location.  However, when `teleport` is applied to a robot other than `self`, it does not get updated.  This was not apparent since we were not using the `robotsByLocation` map to draw the world.  However, other commands which do use `robotsByLocation`, such as `salvage`, will not work correctly if you try to apply them to a robot which has just been teleported.

I noticed this when I switched the world drawing to make use of `robotsByLocation`, and teleported robots did not get drawn correctly.  I am already fixing this as part of my work in another PR (and in such a way that it will be much harder to make the same mistake again), but just wanted to file this issue so we have a place to discuss it and refer to it in the future.

**Comment by TristanCacqueray** [comment]
Thank you for keeping track of these defects, it's unfortunate they exist, but the investigation and the followup fix are great to read :) On a related note, I guess it's a bit late to consider using `apecs` (or any other component system), but I can't help but wonder if such thing would be good to prevent this issue.

**Comment by byorgey** [comment]
I discovered `apecs` shortly after starting on Swarm.  At the time I thought it looked cool but was probably overkill and/or would be too much work to figure out.  I kind of regret that now.  I could definitely imagine at some point in the future doing a massive refactoring/rewrite to use `apecs` or something similar, but not anytime soon.
