### ISSUE TITLE
Drawing robot starting locations in scenario descriptions

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#557]
**Is your feature request related to a problem? Please describe.**
It's frustrating, when creating a challenge scenario, having to do a lot of manual counting to specify the starting locations of the robots relative to the map and its upper left corner.

**Describe the solution you'd like**
I'd like to be able to DRAW the locations of the starting robots on the map somehow.  Not quite sure exactly how this will work.  We would need to be able to specify the starting location of the robot AND the entity and terrain at that cell.
- The `loc` field for a robot should be optional.
- One possibility would be to (optionally) use TWO characters per cell when drawing the map, one for the terrain+entity and one for a robot.
- Another interesting possibility is that it will simply take the terrain+entity under a robot to be the majority value from the surrounding cells.
- Or the palette could simply specify that a specific character corresponds to a specific robot+entity+terrain.
- I can't think of any good way to draw more than one robot on the same cell, but that's OK.  In that case you can still specify their locations manually.

**Comment by xsebek** [comment]
I like the palette triple “robot+entity+terrain” — we can use the normal direction characters, number the robots or describe the robots with emoji/math symbols.

As a bonus, you could use this mechanism to copy&paste robots with same program on the map. 🙂 

The parsing order would be:
1. entities
2. robots (needed for palette triples)
3. palette and the rest

**Comment by byorgey** [comment]
> I like the palette triple “robot+entity+terrain” — we can use the normal direction characters, number the robots or describe the robots with emoji/math symbols.

Yeah, I think you're right, this is probably the simplest/best solution that will cover the majority of use cases.

> As a bonus, you could use this mechanism to copy&paste robots with same program on the map.

Yes, agreed!  I'm thinking something simple like:
- If a robot in the `robots` section has a specific `loc` specified, then one will be created at that location.  Otherwise, one will not be created by default, but the robot will still be available to the palette.
- The palette can specify robots (by name, I assume) and then copies of that robot will be created anywhere it gets drawn in the map.

For palette entries, maybe it could be as simple as each entry is a list of length one, two, or three, specifying respectively the terrain, or terrain + entity, or terrain + entity + robot.
