### ISSUE TITLE
Update to new `brick` API

### ISSUE THREAD

**Issue by jtdaugherty** [swarm-game/swarm#561]
I'm working on an overhaul of `brick`'s `EventM` API and I'd love to get your feedback on how it might impact `swarm`. Please see the details and post comments on https://github.com/jtdaugherty/brick/issues/379. Thanks!

**Comment by xsebek** [comment]
Thanks, @jtdaugherty, that looks like it could simplify things a bit in our `Controller.hs`. :slightly_smiling_face: 

There we use the `S -> EventM Name (Next S)` functions a lot, so changing it to `EventM Name S ()` would hopefully make the code look more like the functions in `Step.hs` where we use lenses for state updates.

I can test your branch with swarm this week unless @byorgey is faster. :wink:

**Comment by xsebek** [comment]
I started working on this in the [brick-event](https://github.com/swarm-game/swarm/tree/brick-event) branch. :construction: 

The controller code will require some shuffling of parameters, but I look forward to replacing `StateT AppState (EventM Name) ()` with `EventM Name AppState ()` :+1:

**Comment by jtdaugherty** [comment]
Nice!

**Comment by jtdaugherty** [comment]
Hi, folks - Brick 1.0 is out. Here are the details: https://github.com/jtdaugherty/brick/blob/master/CHANGELOG.md#10

Note that 1.0 also includes the custom keybinding API to help you with #523. Let me know how that turns out!
