### ISSUE TITLE
Add capability for working with type sums and products

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#563]
There should be some capability(ies) and device(s) for working with type sums (alternative) and products (tuples):
- sums: **Inl**, **Inr**, **Case**
- products: **Fst**, **Snd**

It would help with organically introducing the language features in-game, provide a reference in entity description and also get notified about it by flashing command help as you obtained new capability.

Ideas:
- `printer + calculator --> typing device` that would allow both sums and products, with the explanation that you are performing arithmetic on types
  - the downside is that `calculator` is hard to make, so maybe the `typing device` could also provide normal arithmetic?

**Comment by byorgey** [comment]
Hah, I like the idea of making some kind of upgraded calculator to do type arithmetic.  And having it also provide normal arithmetic sounds fine. Some additional bikeshedding thoughts:
- I don't see what a `printer` has to do with anything.
    - Maybe a `calculator` + some sort of flying/lifting device (because you are doing arithmetic "lifted up to the type level")?
        - Maybe we could make a (difficult-to-construct) `wings` device which would also provide robots the ability to fly over mountains, boulders, and water?
        - That could be fun regardless of what we decide about this issue.
    - Oh, hmm, maybe you meant it as a pun on `typing`?  How about changing the name of a `printer` to `typewriter`? :smile:  Then `typewriter` + `calculator
- I'd like to come up with a funnier / less generic name than `typing device`.  `smart calculator` seems to obvious.  `type-level calculator` is also too generic and maybe too long.  Hmm, how about an `ADT calculator`, and we make a joke in the description that says it stands for `advanced display technology`?  Just brainstorming here, very open to other ideas.

**Comment by xsebek** [comment]
Typewriter was what I was going for. 👍 

I am not sure what the in-word-description of such advanced display technology would be, but I am all for more jokes and puns! 😄
