### ISSUE TITLE
Make pause, single-step, and speed adjustment available as global key shortcuts

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#569]
**Is your feature request related to a problem? Please describe.**
It's very annoying that it is only possible to pause the game or adjust the ticks/second by first highlighting the world panel, then pressing `p` or whatever.

**Describe the solution you'd like**
These commands feel like they ought to be available via global key shortcuts.  For example, I suggest
- `Ctrl-p` to pause/unpause
- `Ctrl-]` to single-step while paused (and perhaps pause the game if it is unpaused)
- `Ctrl-,` and `Ctrl-.` (or `Ctrl-<`, `Ctrl->`) to decrease and increase speed

Of course once we implement #523 then players can pick whatever shortcuts they want.

**Comment by xsebek** [comment]
Thanks for making an Issue for this @byorgey, this is exactly what I was missing in #565. :+1: 

I would not say that #523 solves this, you still need to have these actions globally available to configure them. :raised_eyebrow:
