### ISSUE TITLE
Add listen command

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#577]
Once #565 is merged it would be nice to also allow robots to hear each other and react programmatically.

## Proposed solution
- add the command `listen: cmd string`
  - it will get the first message said by any robot within a radius of 32 cells
  - if there are more messages, take the closest one
  - if there are still more messages, take one at random or jumble them together if you are feeling evil :smiling_imp:
- when a message is obtained, add it to the robot log (and filter message notifications to unique)
  - maybe drop the `Bool` from message notifications and add a field if the message was logged or said to the `LogEntry`?
- create a hearing capability provided by some "listening pipe" (pipe + copper wire + paper?) or something better

## Alternatives
- the command could take an `int` timeout parameter or we could have separate `timeout` command
- the command could fold over messages
- the command could wait for only one tick and have return type `() + string`

**Comment by byorgey** [comment]
Sounds good.  I would suggest keeping it simple: `listen : cmd string` can just block and return the first thing said nearby.  Then we can later add `timeout : int -> {cmd a} -> cmd a` which throws an exception if the timeout is reached before the command completes.
