### ISSUE TITLE
Reject unknown fields when parsing `.yaml` files

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#587]
**Is your feature request related to a problem? Please describe.**
I just spent a frustrating 20 minutes trying to figure out why my scenario didn't work the way I wanted, until I finally realized that the `seed:` field should be at the top level, rather than indented under `world:`.  No error was generated because (1) the `seed` is optional, and (2) unknown fields are simply ignored.

**Describe the solution you'd like**
We should have a standard way to check for, and reject, unknown/misplaced/misspelled fields.  For example, see this StackOverflow question: https://stackoverflow.com/questions/67375099/prevent-unknown-field-names-in-aeson-parsejson

**Comment by xsebek** [comment]
We could show a Warning on it and ask the player to confirm:
```
$ swarm --scenario MyScenario.yaml
WARNING: unrecognized field in scenario file (15:2):
- "gaol"
+ did you mean "goal"?
There was 1 warning generated for the scenario file "MyScenario.yaml"!
**Would you like to play it anyway? Type [y]es or [n]o:**
> no please just fix it for me
**Would you like to play it anyway? Type [y]es or [n]o:**
> n
```
We should check for such warnings in tests of course. :+1:

**Comment by byorgey** [comment]
Well that is a lot fancier than what I was thinking, but sure, why not. :smile:

**Comment by byorgey** [comment]
According to the link, for types where the `FromJSON` instance is derived generically, we can just do something like
```
instance FromJSON MyType where
  parseJSON = genericParseJSON $ defaultOptions
    { rejectUnknownFields = True }
```
For other types where we have a custom `FromJSON` instance, we'll have to do more manual checking.  In the linked StackOverflow answer, this happens by checking the keys of the `HashMap` we get from `aeson`.

**Comment by kostmo** [comment]
This is now implemented: https://github.com/swarm-game/swarm/pull/1475#issuecomment-1694890993
