### ISSUE TITLE
Ability to scroll the REPL panel

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#60]
The user can scroll through their history using up/down, but perhaps it would be nice to allow scrolling the entire REPL itself, so they can actually look at what they did in context?  I am not sure of the best way to do this (maybe with the mouse?).

**Comment by mateoatr** [comment]
What about Ctr+Shift+<Arrow>? I kind of expect it to work on terminals I use in Unix systems.

**Comment by byorgey** [comment]
Ah, good point.  I often use Shift+PgUp/PgDown to scroll by pages.  I guess Ctrl+Shift+Up/Down is sometimes used to scroll one line at a time?  I have never used that and I didn't know about it until just now.

**Comment by byorgey** [comment]
I also note that brick `Viewport`s now support a scrollbar, which would fulfill the same purpose as the `. . .` line (probably better).  I'd like to look into adding scrollbars in general.

**Comment by xsebek** [comment]
@byorgey OK, I am convinced, let `Viewport`s rule all! 👍 

REPL is not as bad as messages, there will be fewer entries and they will not get appended while you scroll. But if we figure out how to do messages well, then REPL could also benefit from a slight speedup. 🙂
