### ISSUE TITLE
Add `version` and `author` fields to scenario format

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#611]
A couple things that occurred to me while writing up documentation for scenario description files (#354):

- We should add a (free-form) `author` field, since hopefully in the near future we will have scenarios written by many different people.
- It might also be a good idea to add a `version` field containing an `int`, so that in the future if we change the format for scenario descriptions, we can easily make things backwards compatible, not by going to contortions to make the new format backwards compatible with the old, but simply by leaving in the code to parse the old format, and choosing which code to run based on the version number.

**Comment by xsebek** [comment]
@byorgey I am all for the author field, we can add that to scenario files and the new game UI even before alpha. :+1:

The versioning I am not so clear about. The parsing is split over multiple `FromJSONE` instances inside different files.
When changing from V1 to some V2, we would have to swap out parsing code based on the version which would be passed around in the reader. More problematically, the reader type could change between versions.

Maybe there is some easy way that I am missing, but supporting older scenario versions sounds like a lot of work and accumulating code.

In the ideal world, we would have symmetrical `ToJSON` and `FromJSON` instances, so we could release `swarm-scenario-1to2` binary that loads with `FromJSON` v1 and outputs with `ToJSON` v2. The advantage would be only having to support two versions at the same time.

**Comment by byorgey** [comment]
@xsebek I think you're probably right that leaving in all the parsing code for old versions would be a mess.  The conversion binary sounds like a good idea.  But in any case, no matter what we decide to do with old versions, it seems like a good, low-cost idea to go ahead and include a version number field now.  We can decide exactly how to make use of it later.

Re: author field, great, let's do it.

**Comment by byorgey** [comment]
@xsebek were you already working on this, or shall I?

**Comment by xsebek** [comment]
No, feel free to add it. :slightly_smiling_face:
