### ISSUE TITLE
The F1 Help modal is too greedy

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#626]
The F1 Help modal loads slowly and then has seemingly infinite empty space under the two tables:
![Screenshot from 2022-08-06 20-03-38](https://user-images.githubusercontent.com/44544735/183261255-88ce9541-0f92-4af6-93cc-e1c61f7bfc52.png)
<sup>I took the picture on the web branch, but it is the same on main.</sup>

Scrolling is terribly slow too. What is going on?!

---

After looking at the code, the culprit is the new `maybeScroll` function (da4db6e61) which lets Help greedily take too much space.

**Comment by xsebek** [comment]
OK, so what is going on is that the custom scrolling logic does not work for the help modal.

It seems to greedily take all the provided 1'000'000 lines of vertical space. 10'000 loads much faster.

The solution would be to either use the `maybeScroll` function for all modals except Help or make Help not so greedy.

**Comment by byorgey** [comment]
Yes, I think that's right.  We should make Help not so greedy.  In fact we need to overhaul Help anyway.  The second table of commands needs to be removed, it is very incomplete and we now have the Commands modal anyway.  The first table perhaps needs some extra stuff added to it, and it probably doesn't need to be a table.  And maybe we can add some friendly text with other helpful suggestions, like where to go if you have questions (the wiki, the IRC channel, etc.), where to find example code, etc.

**Comment by xsebek** [comment]
We will definitely need to overhaul it when we implement custom keybinding (#523). :smile: 

I was thinking about putting the seed number there (#359) and the used port number (#493).
