### ISSUE TITLE
Display a pop-up when the web service fail to start

### ISSUE THREAD

**Issue by TristanCacqueray** [swarm-game/swarm#627]
When the web service fail to start, it would be useful to add a logentry to the GameState message queue with the error. To implement that, we might need a new type of event coming from the web service (which would also be used for #625 )

**Comment by xsebek** [comment]
Hmm, we could `emitMessage` with the base robot ID with an `ErrorTrace` source, which would color it red.

We would only have to make sure that the message is not filtered when you do not have logger and hearing aids installed, but hopefully, that will not be an issue.

**Comment by byorgey** [comment]
Sounds like it might be useful to add a new type of log entry (a "system message" or something like that) which is never filtered.  I could imagine that coming in handy in other situations.

**Comment by byorgey** [comment]
It seems overengineered to create a separate system message queue just to possibly display one message.  Maybe in the future if we have more kinds of messages to display, but I don't know what those might be.  How about simply displaying a pop-up dialog with the error message *before* displaying the main menu?

**Comment by TristanCacqueray** [comment]
I think you are right, then let's not bother with the message queue and using a simpler one-shot popup would work nicely.

**Comment by xsebek** [comment]
For this, a popup will work nicely, but I would like to keep their number small so I did not pitch the idea. :sweat_smile: 

> @byorgey: ... but I don't know what those might be.

I recently read about the new [`monad-logger-aeson`](https://hackage.haskell.org/package/monad-logger-aeson), so I was thinking about adding logging to functions that run on AppState.

We could put errors that happen while outside the game in there, like this failing to attach to port or in the future failed query of the current swarm version (#66). I am sure more opportunities for (debug) logging will come up. :grinning:
