### ISSUE TITLE
Update to brick 1.0

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#634]
brick 1.0 is out.  Hopefully this should be as simple as updating our .cabal, cabal.project, and stack.yaml files.

**Comment by xsebek** [comment]
There is also a small change to `AttrName`, which will now look like this:
```haskell
someAttrName = attrName "blah" <> attrName "things"
```
But that is a good thing™️ and will be very easy to fix 🙂

**Comment by byorgey** [comment]
Closed by #641 .
