### ISSUE TITLE
Module types

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#636]
The type of a command should really include the names and types of the names it defines via `def`.  Without this, we go to a lot of contortions to carry along this extra information outside of the types (e.g. see the definition of `Module`).  Eventually, in conjunction with #231 , something like this will be necessary to properly solve #540 . But even without #231 this would still be a useful change; it would simplify the story and code around typechecking of `def` commands, and make it possible to support nested `def` commands (#349) in a very simple way.

The basic idea is that `TyCmd` would now have *two* arguments: a `Type`, as now (the return type of the command), but also a `TCtx` (the context of names and their types defined by the command).  In terms of concrete syntax, it could be written something like `cmd t => {x1 : t1, x2 : t2, ...}`.  I don't think we need to allow users to *write* such types in swarm programs --- in fact, it might be easier if they *can't* write them, so we only have to worry about inferring (not checking) them.  But we could certainly pretty-print them.

I started working on this in the `module-types` branch, but it turns out to be a bit tricky once polymorphism enters the picture: we don't just have `Type` containing a `TCtx`, but also `UType` and `UPolytype` and ... :cold_sweat:   I hope to ask around and see if anyone has pointers to related work that we could look at.

**Comment by JacquesCarette** [comment]
There are two strands of work that immediately come to mind:
1. Brigitte Pientka's work on contextual type theory (without the 'modal' part)
2. Much work on record types that allow various kinds of polymorphism. There the literature is quite vast. 
    - the records of https://hal.archives-ouvertes.fr/hal-03426711 (appendix C.2) are somehow appealing, though the system seems over-complicated
    - much more elegant is https://homepage.cs.uiowa.edu/~jgmorrs/pubs/morris-popl2019-rows.pdf

**Comment by byorgey** [comment]
@JacquesCarette thanks!  Will definitely check those out.

**Comment by xsebek** [comment]
> @byorgey: I don't think we need to allow users to write such types in swarm programs --- in fact, it might be easier if they can't write them, so we only have to worry about inferring (not checking) them. But we could certainly pretty-print them.

By pretty printing, do you mean printing the types of definitions that got added to the outer scope?
```c
> def m = move end; m; return 0
m: cmd ()  // NEW!
0: int
```

**Comment by byorgey** [comment]
@xsebek Yeah, something like that perhaps.
