### ISSUE TITLE
Custom entities persist when quitting scenario

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#689]
This is a placeholder for now to remind me to fix custom entities persisting across games by storing generic entitymap in new runtimestate, rebuilding GameState from scratch every time.

---

This is a duplicate of #516, but leaving it open since the discussion below about the new `RuntimeState` is relevant.

**Comment by xsebek** [comment]
Is this #516?

Anyway, recently I added an extra `RuntimeState` to `AppState`, do we want to put the persisting parts of `GameState` there?

**Comment by byorgey** [comment]
Oh, yes, this is #516 , I forgot I had already filed it.  Anyway, yes, seeing the new `RuntimeState` is exactly what made me think of this --- it's the perfect way to fix this issue.  Any state that should persist across games (such as the `EntityMap` loaded from `entities.yaml`) should go in the `RuntimeState`, and the `GameState` should be regenerated from scratch every time we load a new scenario.

**Comment by kostmo** [comment]
Just encountered this bug, so adding my data point.  After playing the `2048` challenge, the inventory for a `Creative` game is full of powers of two:

![image](https://user-images.githubusercontent.com/261693/201751537-d939e041-9ebc-4ec7-a85c-abe590323540.png)

**Comment by xsebek** [comment]
@kostmo interesting, they might be visible in inventory because they are _known_, I guess? :thinking:

This can serve as a manual test case for #516. 👍
