### ISSUE TITLE
Persist typechecking result after hitting Enter in the REPL panel

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#692]
When the current REPL input typechecks, its type is shown in grey in the upper right of the panel; the type disappears as soon as you hit Enter to evaluate/execute the input.  We should make the type information persist in the upper right even after hitting Enter, until the user starts to type something else.  That will make things easier for people who are confused about how to get type information, or even just people who want to see the type and then hit Enter by mistake/muscle memory.

**Comment by xsebek** [comment]
Also maybe we should make it more visible, perhaps some brighter color then gray. 🤔

**Comment by byorgey** [comment]
> perhaps some brighter color then gray.

Sure, good idea.  I think I chose gray initially because I didn't want it to be too distracting, but maybe I went too far in the other direction.  :thought_balloon: "When you type an expression, its type will be displayed in the upper right of the REPL in color 0x010101, so as not to be distracting.  Trust us, it's there." :laughing:

**Comment by byorgey** [comment]
:thinking: What color should types be?  My brain seems to insist they should be blue or green of some sort.  But I think they are purple in some syntax highlighting schemes, purple would be OK too.
