### ISSUE TITLE
Salvaged robots don't disappear

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#699]
**Describe the bug**
Salvaged robots are properly salvaged and don't show up in the robots list any more, but they can still be seen in the world view.

**To Reproduce**
- Start a new classic game. 
- `build {}`
- `salvage`

**Expected behavior**
The robot should disappear, so that we can only see the base again. 

**Screenshots**
![salvaged-robot](https://user-images.githubusercontent.com/533859/192116401-c6028d85-a7a9-490a-98e4-357479c2fbb2.png)

**Comment by byorgey** [comment]
According to `git bisect`, the bug was introduced by 120b7b4b79f83ae4c77347c561345026969305b7 .

**Comment by byorgey** [comment]
As an aside, we don't have enough tests to catch UI regressions like this.  I don't even know how we would make UI tests though.

**Comment by xsebek** [comment]
Oh, sorry about that. :sweat_smile: I will try to fix that shortly, see my reply on that commit.

**Comment by xsebek** [comment]
@byorgey I think we should note somewhere what exactly system robots can do.

I think there is a distinction between ordinary/system/creative robots and sometimes I am unsure what I can expect when writing scenarios. There are probably even special cases like the `As` and the `Salvage` commands that we should be wary of. :confused:

**Comment by byorgey** [comment]
> I think we should note somewhere what exactly system robots can do.

Agreed.  For example, in `Swarm.Game.Robot` we could add a comment to the documentation of the `systemRobot` field.
