### ISSUE TITLE
Allow multiple robots in one cell

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#710]
Currently, we only allow specifying one robot in a cell palette. Any additional robots have to be added using location.

In some scenarios, it would be easier to specify multiple robots in the same cell using the palette and not bothering with the location.

For example:
```yaml
  palette:
    '.': [blank]
    '┌': [blank, upper left corner]
    '┐': [blank, upper right corner, upright]
    'L': [blank, "2", upleft, upright2]
```

Formally, the "cell" JSON list would have a length _greater than one_, with the first mandatory element being the terrain, the second optional parameter being the entity and the rest will be the names of robots.

**Comment by byorgey** [comment]
Makes sense to me!
