### ISSUE TITLE
Save invalid inputs in REPL history with down arrow

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#713]
**Is your feature request related to a problem? Please describe.**
The basic problem is that the only way to get a REPL input added to the history is after it successfully parses and type checks and is actually executed.  It's always frustrating when I type in a long REPL input but then realize I need to do something else first.  For example, suppose I type a long input but then realize that it uses some functions that are defined in `my_stuff.sw` but I forgot to load `my_stuff.sw`.  In that case my input doesn't even type check.  Or maybe my long input does type check but I realize that there's some other command I need to execute first in preparation for it.  The reason this is so frustrating is that the only solution is to clear the input, type the other command first, and then retype the long input from scratch, because there is no way to save it in between.

I guess the way the REPL currently works is actually pretty similar to the way shells or, say, ghci work.  But somehow it seems frustrating with Swarm, perhaps because it feels natural/encouraged to type longish commands at the REPL.

**Describe the solution you'd like**
I really like the way irssi handles this: at any time you can hit the "down" arrow key, which adds the current input to the history and clears it.  So for example if you are in the middle of typing a longer message but want to pause in the middle in order to respond to something else quickly, you can just hit "down", type and send the new message, and then hit "up" a couple times to retrieve your partially complete message and continue composing it.

**Comment by xsebek** [comment]
My workaround has been to comment out the line:

Hit <kbd>Ctrl</kbd>+<kbd>A</kbd> to move to the beginning of the line and then type `//` to comment the line out.

But I like the solution with the <kbd>⬇</kbd> key, that should be easy enough to do! :+1:

**Comment by xsebek** [comment]
This will be necessary for #1426.

Whatever the immediate response will be, we have to assume that the client may not receive it. In that case, the web client should be able to search history for its command and the result.

@byorgey could be drop the error popup entirely? We now have arrow-up to bring back the last command, so I do not see the design reason for it anymore.

**Comment by byorgey** [comment]
> @byorgey could be drop the error popup entirely? We now have arrow-up to bring back the last command, so I do not see the design reason for it anymore.

Which error popup are you talking about?  And I'm not sure I understand what arrow-up has to do with error popups, could you elaborate?

**Comment by xsebek** [comment]
In case you have invalid (can not parse/typecheck) REPL prompt and hit Enter, we show an error popup.

I propose we instead save it in history and show the error like output. I.e. like GHCi does it.

If the player wants to fix the prompt, they can hit the up-arror, so there is no need for us to keep the prompt the same.

**Comment by byorgey** [comment]
Ah, I see, yes, that makes sense.  To make it ergonomic we should probably address #60 first though.  And maybe add a key shortcut to fullscreen the REPL?

I think even so, this feature (being able to hit the down arrow to add the current input to the history) would still be nice, because maybe I *know* my current input is incomplete and I know why, so I don't want to hit enter and pollute the REPL window with a big error message just to save my incomplete input.
