### ISSUE TITLE
Fatal error: Bad machine state

### ISSUE THREAD

**Issue by rybern** [swarm-game/swarm#736]
**Describe the bug**
See screenshot

**To Reproduce**
Here's my script file: https://gist.github.com/rybern/4f42f178ae3b987613eabf2290d1b8d3

You can see the last command I ran; I don't know what other context is relevant

**Expected behavior**
The bot should keep farming :)

It seems to halt at the second iteration of `farm2Next`

**Screenshots**
![2022-10-07-223413_3840x2160_scrot](https://user-images.githubusercontent.com/4982341/194683830-dd0e53a7-b592-4495-a525-f0e74723f38b.png)

**Additional context**
By the way I am _loving_ this game!

**Comment by byorgey** [comment]
Thanks for the report, and glad you're enjoying the game!  Just a quick guess, this is probably #681.  But I'll take a closer look tomorrow.

**Comment by byorgey** [comment]
After looking into this a bit more, I'm now quite certain this is an instance of #681.  The binding of `b` in the definition of `sharv` (i.e. `b <- ishere i`) leaks out into the definition of `pick` and from there into `pickerBot`; the `times` function also uses the name `b`, and at some point one of them erroneously overrides the other, so we end up with `true` (the value of `b` from `sharv`) being applied to an argument (which is how `b` is used in the definition of `times`).

As a workaround, you could try renaming one of the occurrences of `b`. 

But I really need to fix #681, it is a kind of embarrassing bug. :flushed:

**Comment by rybern** [comment]
Successful workaround, thanks! I'll stick to unique local names.
