### ISSUE TITLE
Update Swarm to work with GHC 9.4 and latest package versions

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#748]
There are a bunch of packages (`lens`, `brick`, `vector`, ...) with newer versions that we have not tested Swarm with.  We also have not tested with GHC 9.4.  It's probably a good idea to work on testing and relaxing the upper bounds in the `.cabal` file where possible, with the ultimate goal of being able to build with the latest versions of everything.

**Comment by xsebek** [comment]
Updating `brick` is a good idea because there was a performance improvement for `hBox` and it will also be useful for some of our UI Issues. 👍

**Comment by xsebek** [comment]
To get the list of packages that could be updated, you can use [`packdeps`](https://github.com/snoyberg/packdeps/tree/web/packdeps-cli):
```
> packdeps swarm.cabal
swarm-0.1.1.0: Cannot accept the following packages
aeson 2.1.1.0
base 4.17.0.0
brick 1.3
entropy 0.4.1.10
lens 5.2
lsp 1.6.0.0
mtl 2.3
template-haskell 2.19.0.0
vector 0.13.0.0
vty 5.37
witch 1.1.1.0
```

**Comment by byorgey** [comment]
Note, with recent versions of `cabal` your can also just use `cabal outdated`.
