### ISSUE TITLE
"Congratulations" dialog pops up before scan results are rendered

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#758]
**Describe the bug**
In the "Scan" tutorial, the "Congratulations" dialog pops up before the result of the scan (e.g. mountains) is rendered to the playfield. This leaves the player wondering what they actually accomplished in order to complete the tutorial.

**To Reproduce**
1. Launch the "Scan" tutorial
2. Scan the nearest mountain and upload

**Expected behavior**
Mountains should appear, be visible alongside the dialog

**Screenshots**
When the dialog pops up:
![before](https://user-images.githubusercontent.com/261693/196607165-1f5eff35-a6a3-473e-a9e6-9a4206884885.png)

Immediately after dismissing the dialog:
![after](https://user-images.githubusercontent.com/261693/196607185-07e22dce-864d-407c-a1b1-7acd7fd3e805.png)

**Additional context**
This is from the `main` branch (commit `b895668`), compiled and run via `stack run`.

**Comment by xsebek** [comment]
Good point, we should make sure that the known entities apply immediately. :+1:

**Comment by byorgey** [comment]
I'm guessing it goes something like this: your robot executes `upload`, and then in the same tick the goal condition executes and realizes that you have won.  The world would be redrawn at the end of the tick, except before that can happen we notice the winning flag has been set and pop up the congratulatory dialog.  I am not sure exactly what the best way to fix it would be, but it has something to do with reordering when the world is redrawn vs when the goal condition is checked and/or when the winning dialog pops up.
