### ISSUE TITLE
More obvious navigation between tutorials

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#759]
**Is your feature request related to a problem? Please describe.**

Would like to have an obvious, direct way to go back to the previously completed scenario, or to jump to the next scenario.

Upon first playthrough of the tutorials (having immediately selected "Tutorial" from the game's title screen, and not ever having seen the tutorials list that is accessible via "New Game" -> "Tutorials"), I thought it might be nice to have a HUD, accessible within the main game screen that showed my progress within the tutorial sequence.  And I didn't want to lose my "progress" through the tutorials if I was to quit the game!  But then I realized that when selecting "Quit to menu" from the CTRL+Q, I am taken to the tutorial selection screen.

I came across the related sentiment in #595 that "quit" sounds "drastic".

**Describe the solution you'd like**

I probably would have had that realization sooner if, in the CTRL+Q dialog, instead of saying "Quit to menu", it was more specific about *which* menu we're quitting to, e.g. "Quit to tutorial selection".

**Describe alternatives you've considered**
There could be a "Next Tutorial" and "Previous Tutorial" button right in the CTRL+Q dialog.  But this may be too much clutter.

**Additional context**
This is from the `main` branch (commit `b895668`), compiled and run via `stack run`.

**Comment by xsebek** [comment]
Hi @kostmo, could you please try the fix in #754 by @byorgey? Ideally, it should solve this issue too. :slightly_smiling_face:

**Comment by byorgey** [comment]
Well, I think @kostmo also has a good point that the dialog should say "Quit to tutorial selection" or something like that instead of just "Quit to menu".  I can add that to #754.

**Comment by byorgey** [comment]
@kostmo I think #754 now addresses this issue --- what do you think?

**Comment by kostmo** [comment]
Yep, looks good!
