### ISSUE TITLE
Display the name of the current tutorial

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#760]
**Is your feature request related to a problem? Please describe.**
Would like to know what the name of the current tutorial is so that I can quit and come back to it.  This concern is peripherally related to #759.

**Describe the solution you'd like**
Display the title in a status bar along the bottom of the screen, like in the `vim` editor.

**Describe alternatives you've considered**
Alternatively, could display the name in the CTRL+G "goal" dialog.

**Additional context**
This is from the `main` branch (commit `b895668`), compiled and run via `stack run`.

**Comment by xsebek** [comment]
Hi @kostmo, I like this idea! :+1: 

We can easily put the name in <kbd>Ctrl</kbd>+<kbd>G</kbd> dialog title which is currently empty:
https://github.com/swarm-game/swarm/blob/758b3d0192fca1d61fe330340c6716cc1f36c7b6/src/Swarm/TUI/View.hs#L488-L493

I am not sure where on the screen we could put it, it is getting crowded. :smile: 

The bottom of the screen could interfere with the REPL; the top is already used for time and <kbd>Fn</kbd> modals.

Would a layout with the name in the top left corner work for you?
```
+-----------+-----------+
|Name       |           |
+-----------+   World   |
|Inventory  |           |
+-----------+-----------+
|Description| REPL      |
+-----------+-----------+
```
What do you think @byorgey? I would like to have the name somewhere but it should not take up too much space.

**Comment by byorgey** [comment]
I think replacing `Goal` with the name of the challenge in the goal dialog definitely makes sense.  As for putting the name somewhere else on the screen, I'm not sure.  The top left corner could work, though I don't think it should be on the border of the inventory panel, since that would make it look like it was somehow labelling or giving information about the inventory.  @xsebek , not exactly sure what you had in mind from your ASCII art.  Maybe it could just go on a line by itself, above the inventory panel?  Not sure how bad it would look to have the top edge of the inventory panel not lined up with the top edge of the world panel.

**Comment by xsebek** [comment]
@byorgey I was thinking bout putting the name on its own line at the top.

I did not realize I should draw the segments separately, so here is more accurate drawing:
```
+-----------++------------+
|Name       ||            |
+-----------+|   World    |
+-----------+|            |
|Inventory  ||            |
|           |+------------+
+-----------+ [^v] creative
+-----------++------------+
|Description|| >>>        |
|           || >>> REPL   |
+-----------++------------+
```

Even the three lines seem OK to me, maybe we will wind other uses for that space. :slightly_smiling_face:

**Comment by byorgey** [comment]
Well, there is a way to get brick to draw a single box with a dividng line, but yeah, if we put it in the upper left at all I think we should put it in a separate box - again,  so it does not look like a label on the inventory specifically.  Definitely willing to try it out.

**Comment by xsebek** [comment]
Closing, as we have the name in the Goal title now and it would be redundant to display the name in two places. 🙂
