### ISSUE TITLE
Better advertise ability to pop up entity description

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#764]
> > We should add a way to show the description in a popup modal so that such long descriptions are easier to read. 

> That already exists, just hit `Enter` on an inventory item.  But clearly we need to advertise it better!

_Originally posted by @byorgey in https://github.com/swarm-game/swarm/issues/753#issuecomment-1283999856_

- [x] Change `[Ret] focus` hint to something like `[Ret] pop out`
- [x] Add hint to the tutorial
- [x] Highlight `[Ret] pop out` when the info panel scrolls
- [x] Highlight all panel-specific keyboard shortcuts

**Comment by byorgey** [comment]
I have a few ideas how to improve this.
- @xsebek pointed out that currently the key help menu says `[Ret] focus` which doesn't do a good job conveying what will happen.  We should improve that --- any ideas what would be better?  Maybe `zoom`?  `pop out`?
- That doesn't really go far enough though.  I think there's a place in the tutorial where it advises you to go read about `treads` which has a fairly long description.  That could be a good place to insert a hint that you can hit Enter on the item to pop up a box.
- What if, whenever the item description doesn't fit in the info panel, the `[Ret] focus` (or whatever it ends up getting changed to) in the key shortcut help menu is highlighted?

**Comment by xsebek** [comment]
> What if, whenever the item description doesn't fit in the info panel, the [Ret] focus (or whatever it ends up getting changed to) in the key shortcut help menu is highlighted?

I like that idea. Maybe we could highlight the panel-specific actions all in some colour. That way players can more easily notice that there are new actions available now that they have selected that panel.

The <kbd>Enter</kbd> could be in bold whenever the description is too long. We already put the `. . .` in UI when there is more text beneath, so it should be possible to store that knowledge in the UI state. :thinking:

**Comment by byorgey** [comment]
> Maybe we could highlight the panel-specific actions all in some colour.

That's a good idea too.

> We already put the `. . .` in UI when there is more text beneath, so it should be possible to store that knowledge in the UI state.

Yes, we already have the `uiMoreInfoBot` and `uiMoreInfoTop` fields in the `UIState`.
