### ISSUE TITLE
Make integer literal syntax discoverable

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#779]
For a while we have had the ability to write integer literals in binary, octal, or hexadecimal format in addition to the usual decimal.  However, currently, there is no way for players to discover this.  I could imagine a few routes we could take:

- One option is to simply mention the available syntax in the tutorial somewhere.
- Another option is to make the use of the extra integer literal syntax dependent on one or more devices. Then you could discover the ability to build the device(s), and once built, the description of the device would explain the syntax it enables.
    - Currently, the parser simply turns any integer literal syntax into a `TInt`.  We would probably just add an extra field to `TInt` specifying which syntax was used to write the literal; then we could depend on that field to determine the required capabilities.

Open to discussion and to other possibilities as well.

**Comment by xsebek** [comment]
How about we instead add commands to serialize/parse integers in octal/hexadecimal/binary? The device that would provide that capability could explain how it's also possible to use that syntax in code.

Requiring a capability to use the syntax in code does not make sense to me - we already allow decimal which is the weirdest of the bunch. Realistically the base syntax should be binary, but I would not want to use that by default. :rofl:

**Comment by byorgey** [comment]
Yeah, that could work.

**Comment by byorgey** [comment]
A device to serialize/parse integers doesn't seem that useful since elsewhere we seem to be headed towards various typed communication channels --- it would be annoying to have to serialize and parse every time you want to communicate, save a value for later, etc. (even though of course that's how it works in the real world).

Another possibility to consider is that not every little language feature needs to be discoverable in-game.  Perhaps we should just create a comprehensive language reference on the wiki (or elsewhere) and leave it at that.

**Comment by byorgey** [comment]
Given my last comment, I'm going to close this.  Feel free to re-open if there are new ideas about how we could make these notations discoverable in-game.
