### ISSUE TITLE
Running a script bypasses capability check

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#785]
**Describe the bug**

One can utilize a lambda in a function definition, even without possessing a Lambda in one's inventory, by writing the function definitions in an external script instead of the REPL.

**To Reproduce**
1) Save the following script to `bypass-requirement.sw`:
    ```
    def do2 = \x. x; x; end;
    build {do2 move};
    ```
2) Start the "First Steps" tutorial:
    ```
    stack run -- --scenario data/scenarios/Tutorials/world101.yaml
    ```
3) In the REPL, execute the script:
    ```
    run "bypass-requirement.sw"
    ```
4) Observe that the robot moves two spaces north.

**Expected behavior**

The robot should not begin to move; an exception should be thrown.  This is in fact the case if the same code is defined and executed entirely within the REPL.  Type the following in the REPL:
```
def do2 = \x. x; x; end;
build {do2 move};
```
The log then says:
```
build: You do not have required
  devices, please obtain:
  - lambda
```

**Additional context**
Observed on the latest `main` branch: commit `13e7dfe`

**Comment by xsebek** [comment]
Hi @kostmo, this is not a REPL vs `--run` problem, but a known limitation of our capability checking _in the same expression_.

You can run this in REPL:
```Haskell
def do2 = \x. x; x; end; build {do2 move};
```

See:
- #231

I would suggest closing this in favour of the existing Issue, but thanks for reporting this! :+1: At least it's good to know that this is something that players might run into often.

**Comment by byorgey** [comment]
Yeah, this is an instance of #540, I think.  In the case of something like `def m = move; build {m}` the built robot crashes at runtime because it is not given `treads`.  On the other hand, the use of lambdas is not capability-checked at runtime like commands are, so the examples in this issue do not crash, but instead let you get away with executing functions without having a lambda.

**Comment by byorgey** [comment]
Just adding a note here that when solving #540 with #827, I verified that this issue is also resolved.  For example, running `def do2 = \x. x; x; end; build {do2 move}` now fails with an error about needing a `lambda`, as it should.
