### ISSUE TITLE
The "Bind notation" tutorial does not necessitate the use of a bind

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#786]
**Describe the bug**
The "Bind notation" tutorial can be solved without binding anything.

**To Reproduce**
1. Launch the "Bind notation" tutorial:
    ```
    stack run -- --scenario data/scenarios/Tutorials/bind.yaml
    ```
3. In the REPL, simply type:
    ```
    place "Win"
    ```
    This completes the challenge.

**Expected behavior**
Play a scenario in which `bind` is necessary to complete the scenario goal.

**Comment by xsebek** [comment]
@kostmo That is expected - we can not _force_ you to use bind notation, because we can not check that value... yet!

If we had channels (#737) we could use those to send the bound value to a judge robot.

But if I had to think out of the box, we could make a tutorial that is hard to solve without bind notation.
For example:
- judge:
  ```Haskell
  def replicate = \n. \m.if (n==0) {""} {m ++ replicate (n-1) m} end;
  r <- random 1000;
  let secret = replicate r "_SECRET_" in
  say secret;
  waitUntilBaseSays $ "I heard: " ++ secret;
  create "Win";
  ```
- solution:
  ```Haskell
  l <- listen;
  say ("I heard: " ++ l)
  ```

You will always be able to cheese it using `it0`, but that is probably OK.

**Comment by byorgey** [comment]
Yeah, on the one hand, this is a tutorial --- we are providing players with an *opportunity* to learn and play with things, but there's no particular reason we need to *enforce* that they do certain things.  Ultimately it doesn't matter if they choose to make use of the opportunity or not.

With that said, sure, if there's some simple thing we can do to require it we might as well.  But as @xsebek says I don't think there's any way to force the player to use bind notation.  @xsebek 's solution is clever but I don't know if the extra complication is worth it.

**Comment by kostmo** [comment]
Currently, these three tutorials exist in sequence:
1. Bind notation
2. Install
3. Build

As it happens, the Build tutorial goal text has a this note:
> TIP: You can use the name of the flower directly ("pickerelweed"), or you can use bind notation: `f <- harvest; ... ; place f;`.

Perhaps we can still keep this text, but preferably an earlier tutorial will force the player to have used this idiom already.  If we instead taught the player how to "build" a robot before the "Bind" tutorial, then we could contrive a situation where binding is required.

The playfield would contain one "?".  The goal text could invoke the concept of feng shui:
> There's something on the ground, but it doesn't seem like it belongs there.  Let's put it somewhere else.

The player shall not be equipped with a `scanner`.  The user will have to build a robot to `grab` the item, `move`, and `place` it again. However, the player doesn't know the item's name, so the only way they can place it is by a reference obtained from binding the output of `grab`.

For fun, that thing could be named ["Hastur"](https://wiki.c2.com/?HeWhoMustNotBeNamed).

**Comment by byorgey** [comment]
Hmm, yes, I think moving the bind tutorial until after the build tutorial could be a good solution.  Indeed, then you could be forced to use bind notation in order to build a robot that picks up an unknown item and places it somewhere else.

**Comment by xsebek** [comment]
@kostmo I like the eldritch monster name idea. 👍 🐙 

I think we should limit the installed and available devices as much as possible. That way you can not bring it back and build a second robot after you salvaged the first one. It may be pedantic, but we have a restart button, so we might as well use it. 😈
