### ISSUE TITLE
Include known device(s) that provide commands in command help dialog

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#788]
**Is your feature request related to a problem? Please describe.**
The commands dialog (F4) is great, but there's currently no way to remind yourself what device(s) are needed for a particular command other than looking through your inventory and reading descriptions, or simply trying the command and seeing what error message results.  I imagine this could be overwhelming and frustrating for new players.

**Describe the solution you'd like**
I'd like the commands dialog to have another column which shows device(s) you know about which provide each command.  We certainly know this information internally, so in theory it shouldn't be hard to display it to the player.  Perhaps something like this (but with color of course):
```
    not : bool -> bool                     o lodestone
     if : ∀ a. bool -> {a} -> {a} -> a     y branch predictor
harvest : cmd text                         ≤ harvester
   grab : cmd text                         < grabber, ≤ harvester
```

**Comment by xsebek** [comment]
@byorgey good point, this would be useful. :+1: 

There are more things we could show about a command, namely its description, which would be nice to show in an expanded widget. But I think showing the device that provides it would be neat to see in the overview as you say, so the expanding widget is not necessary for it.

**Comment by byorgey** [comment]
> There are more things we could show about a command, namely its description, which would be nice to show in an expanded widget. 

Ah, nice idea.  I'm imagining something like being able to browse through the commands in the command dialog and hit Enter on the highlighted one to pop up a dialog with its description etc.  Let's make that into a separate issue.
