### ISSUE TITLE
Order of robots on map determines base

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#790]
I've constructed three minimum reproducible test cases to demonstrate, with a `2x1`-sized map.
In the `palette`, I've mapped the character `b` to what is supposed to be the "base" robot, and the character `a` to a second robot.
In the screenshots, the contents of the "F2" menu is displayed.

Differences:
* The only difference in the scenario file between the **first** and **second** column is the `system: true` property added to the robot named "fake" (`a` in the palette).
* The only difference in the scenario file between the **second** and **third** column is the positioning of the robots in the map.

| Two normal robots | One system robot, to the right of base robot | One system robot, to the left of base robot |
| ---| --- | --- |
| ![Screenshot from 2022-10-24 23-00-48](https://user-images.githubusercontent.com/261693/197694507-2fd3dead-2767-437d-bdcb-e9dd7753228b.png) | ![Screenshot from 2022-10-24 23-11-31](https://user-images.githubusercontent.com/261693/197695998-8aaf4480-a836-445f-9a97-18811a8fde99.png) | ![Screenshot from 2022-10-24 23-13-35](https://user-images.githubusercontent.com/261693/197696402-7a92e99e-e524-4f62-ac33-843852ba5005.png) |
| [code](https://gist.github.com/kostmo/96ab073e9f626da2ec67d54ff3adcf40) | [code](https://gist.github.com/kostmo/ba0c8ecc6efc30c61aae36c8d4d66036)  | [code](https://gist.github.com/kostmo/4e229b76ff8a283fad56a1e2467a694c) |
| Map layout: `ba` | Map layout: `ba` | Map layout: `ab` |

In the third column, I would have expected the system robot to not be listed in the "F2" menu.

**Comment by byorgey** [comment]
Hmm, notice how in the third column it says `fake (-1,0)` in the upper left instead of `base (-1,0)`?  I wonder if in the third scenario the `fake` robot is being treated as the base somehow.

**Comment by byorgey** [comment]
OK, I am able to reproduce this.  An indeed, it seems like in the third scenario the `fake` robot is actually the base (i.e. commands typed at the REPL are executed on it).  You can observe this by starting the scenario with `--cheat` enabled, hit Ctrl+V to switch into Creative mode, and type `whoami` at the prompt:
```
> whoami
it0 : text = "fake"
```

**Comment by xsebek** [comment]
Oh, right that is what this is. I thought we already discussed adding a `base: true` or something, but I can not find any issue for it.

After adding all the robots on the map, there would have to be exactly one `base` robot.

We could default to the robot named "base", to make things easier and less surprising. 🙂

**Comment by xsebek** [comment]
Hehe, I made a new label for this. 😁
