### ISSUE TITLE
Achievements system

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#797]
Creating this issue as a nucleation point for ideas around an achievements system.

* There should be a toplevel "trophy case" accessible from the main menu.
* Achievements should be definable within scenario files as some combination of goals.  #795 would probably be a prerequisite to make this work.
    * Goals would then probably also need to support some "identifier" to make them referenceable by the achievements definitions elsewhere in the file.
* Since scenario files may come and go, would probably represent the global achievements list as **hashes** of the distributed achievement definitions.
* In addition to scenario-level achievements, it would also be nice to earn achievements through either **non-scenario** or **cross-scenario** activities.  For example:
    * Completing your first tutorial
    * Completing *all* of the tutorials
    * Surpassing *N* hours of total game time
    * Exploring the complete menu of tutorials
    * Driving a robot into the water
    * (Attempting to) self-destruct your base

I recognize that peppering the game code with achievement-persistence functions has a maintainability cost, i.e. if it breaks encapsulation or purity of some part of the code.  So if it can't be done cleanly, we may want to avoid such achievements.

If the "Classic" game is considered the "canonical" way to play Swarm, perhaps some of these latter examples would just be defined in the `classic.yaml` file, and only achievable in "Classic" mode.

**Comment by xsebek** [comment]
I love this idea! 👍 Let's make Swarm feel like a proper game! 🎮 💻 

We can definitely add some system-wide achievements like the ones you mentioned. If they are checked once at the end of the tick or even at the end of the game, they will likely not even be noticeable.

Some of them, like self-destructing, can be checked in one place in the step function. In this case, when we catch exceptions. In other cases, it will be "the first time you execute teleport" or something like that.

Checking custom achievements can use the same infrastructure as the objectives. Maybe they could even _be_ parallel _optional_ objectives marked as achievements? 🤔

---

> Since scenario files may come and go, would probably represent the global achievements list as hashes of the distributed achievement definitions.

Noooooooo! 🤣 We already have unique names of scenarios and _our players and developers are not attackers_. To me, this looks similar to how packages are distributed. They simply have unique names and a centralized repository from where you can download them.

This does not prevent distributed achievements, you can have anything you want on your machine and when sharing with others you just pick a unique name. Or just add a number to it, or underscore or change it a little.

I think everyone in this time and age knows the importance of picking a good name on a platform first. 😆 It is its own kind of game and using hashes takes away all the fun.

It will also be hard for me personally. Please no more hashes than absolutely necessary for performance. 🥺 

---

> I recognize that peppering the game code with achievement-persistence functions has a maintainability cost, i.e. if it breaks the encapsulation or purity of some part of the code. So if it can't be done cleanly, we may want to avoid such achievements.

@kostmo do not worry, we already access the whole `GameState` in `Step` and we also have `IO`. I think we can put "game-wide" achievements in the `GameState` and save them along with the best time once you finish. 😁 

The achievements like "completing tutorial" could live in `RuntimeState`. We can recompute this one if we need it, but others will probably need to be saved on exit.

**Comment by xsebek** [comment]
@kostmo is this complete? I think so, but if there are any remaining ideas here that I overlooked, please split out an issue and close this one afterwards. :wink:
