### ISSUE TITLE
Autoplayed games should not earn best time

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#816]

**Comment by byorgey** [comment]
Could this be accomplished simply by having `--autoplay` automatically imply `--cheat`?

**Comment by xsebek** [comment]
@byorgey yes, I think we just need to tweak how the parameters are parsed and saved.

Something like this:
```Haskell
autoplay <|> ((,) <$> cheat <*> run) :: Parser (Bool, CodeToRun)
```
