### ISSUE TITLE
Swarm swarm

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#829]
I had the idea of trying to organize a sort of virtual Swarm get-together/hackathon (which should, of course, be called a "swarm" :wink:), open to anyone, both regular contributors as well as newcomers.  The goal would just be to have fun working on Swarm together, perhaps make some progress on bigger/more difficult issues, perhaps onboard some new contributors, etc.  The purpose of this issue is to gauge interest and figure out some details.

1. Would you be interested in attending such a thing?
2. If so, do you have opinions about modes of interaction? 
    - For example, we could just keep it to IRC, or we could set up a discord channel, or a gather.town space, etc.
    - Something that supports screen sharing would probably be nice.  
    - The big question is whether we should have some kind of audio and/or video chat.  On the one hand that can be really fun and much higher bandwidth than IRC.  On the other hand I want to be sensitive to the fact that some people might not be as comfortable with audio or video chat.  I wouldn't want a situation where some people felt excluded because they were uncomfortable with audio/video chat for whatever reason.
3. What kind of dates/times might work for you?
    - Personally, I wouldn't be able to do this until after my semester is over around the beginning of December.  The week of December 12 would work particularly well for me.  But other times could work too, and if we have to plan much farther out to find a time that will work, that's fine.
    - What time zone are you in, and what kind of waking hours do you regularly keep?
4. Any other thoughts?

Tagging people who have been involved currently or in the past and who might potentially be interested: @xsebek @kostmo @valyagolev @ussgarci @0xcefaedfe @polux @TristanCacqueray @fryguybob @twitu @lsmor @noahyor

**Comment by TristanCacqueray** [comment]
That sounds great to me. I'd be happy to try gather.town, or use another platform as you prefer. The week of December 12 works for me, I'm in EST. It might be nice to have some sort of an agenda to set the expectation, e.g. duration, topic ideas (e.g. tutorial, roadmap, #50), ...

**Comment by ussgarci** [comment]
1. Count me in! :+1: 
2. I'm partial to Discord as I already have an account.  I know it supports screen sharing and audio chat.
3. The week of December 12 works for me.  I'm in CST and would be available anytime after 8am.

**Comment by xsebek** [comment]
1. Sure, that sounds cool. 👍
2. I would like to try Gather Town, but I can use anything that runs in a browser or on Linux. 🙂 
    - I think audio and screen sharing could make communication easier and faster
3. After the semester works for me. I am in CET (UTC +1) but I can continue late into the night. 🌃 

I like @TristanCacqueray's suggestion about focusing on something concrete. I have never done any hackathons, what are good criteria to select a focus? Or is it best not to choose and let everyone individually improve Swarm and discuss implementation? 🤔

**Comment by 0xcefaedfe** [comment]
Sounds good to me and December would work for me as well. Thanks for
including me too :)

**Comment by byorgey** [comment]
Re: focus/agenda, I don't want to impose some kind of top-down structure, but I agree it is useful to know in advance how we might use the time.   The usual thing would be to make a wiki page ahead of time and let everyone put ideas of what they want to work on etc., and let some kind of agenda coalesce around that.  

> Or is it best not to choose and let everyone individually improve Swarm and discuss implementation?

I think it's best not to choose one single focus --- everyone has different things they are excited about and that's good and healthy.  But that also doesn't mean we must all just work individually --- people can post ideas of things they want to work on and try to convince others to join them.  And I hope that if we use something like gather.town there will be a lot of organic wandering around, seeing what other people are up to, and jumping in to help.

**Comment by byorgey** [comment]
Based on everyone's responses, I will concretely suggest **Wednesday, December 14**, at this time:

https://www.timeanddate.com/worldclock/fixedtime.html?msg=Swarm+swarm&iso=20221214T14&p1=%3A&ah=9

That's 8am-5pm CST / 9am-6pm EST / 2pm-11pm UTC.  Of course everyone should feel free to come and go whenever you can/want.

* Let me know if that time no longer works for you!  We can easily switch to a different day.
* I will set up a virtual space in gather.town.
* I think it makes sense to just commit to one day to start, but if it goes really well and people want to continue for another day or two that would be possible as well.

**Comment by byorgey** [comment]
Thanks everyone for coming today!  It was fun meeting everyone and talking about stuff.  We should definitely do this again sometime.  The Swarm Hive on gather.town will remain accessible anytime.  I may just hang out in there sometimes if I'm hacking on Swarm.  I'll probably be around for at least part of the day tomorrow though I have some grading I have to do as well.

**Comment by byorgey** [comment]
How about another gathering/Hackthon/Swarm swarm/whatever you want to call it?  Next week sometime, perhaps?  I think @ussgarci said Tuesdays or Fridays work best, both would work for me (i.e. June 6 or June 9).  Any other time preferences/constraints from others who might want to join?  @kostmo ? @xsebek ?  @valyagolev @0xcefaedfe @polux @TristanCacqueray @fryguybob @twitu @lsmor ?

**Comment by xsebek** [comment]
Hey, sounds great! 😁 This would be a great way for me to get back into Swarm. 

My trial period at work ends tomorrow, so I will look for some easy tasks to get familiar with the code again.

@byorgey do you want to make a new Issue or reopen this one? 🙂

**Comment by kostmo** [comment]
I vote for June 9.

**Comment by 0xcefaedfe** [comment]
I'd love to participate!

**Comment by ussgarci** [comment]
+ 1 for June 9th  :sunglasses:

**Comment by TristanCacqueray** [comment]
I'll be on vacation this week, not sure I'll be able to join. Enjoy!

**Comment by byorgey** [comment]
Sounds like June 9 is the winner!  I'll be able to start around [9am CDT / 2pm UTC](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Swarm+swarm&iso=20230609T14&p1=%3A) if that works for everyone.

**Comment by 0xcefaedfe** [comment]
That works for me

**Comment by byorgey** [comment]
See you all tomorrow on https://app.gather.town/app/SpqG1ic5pNKM7YqS/The%20Swarm%20Hive at [9am CDT / 2pm UTC](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Swarm+swarm&iso=20230609T14&p1=%3A) !

**Comment by kostmo** [comment]
I should be able to join at +3hrs (5pm UTC)

**Comment by kostmo** [comment]
We can try out the GitHub Discussions feature to take notes: https://github.com/swarm-game/swarm/discussions/1312#discussion-5280293

**Comment by byorgey** [comment]
Let's do another Swarm swarm!  How about June 13, 14, or 15 (Thursday, Friday, or Saturday) 2024?  It's been mostly me and @kostmo holding down the fort recently (and there are some really cool features in the works!) but would love to have this be a chance for some others to get involved again.  Reply with preferences if you'd be interested.

**Comment by byorgey** [comment]
@nitinprakash96

**Comment by nitinprakash96** [comment]
Very much happy to join. The dates work for me!

**Comment by kostmo** [comment]
I'm available at 1pm PDT on June 15.

**Comment by byorgey** [comment]
@nitinprakash96 what time zone are you in?

**Comment by nitinprakash96** [comment]
I am in IST (UTC +5:30) @byorgey

**Comment by byorgey** [comment]
How about we plan to start sometime in the range 9-11am CDT / 7-9am PDT / 7:30-9:30pm IST.  @nitinprakash96 you can stay as long as you want, not sure how late you want to stay up, and @kostmo can come later whenever he is available.  How does that sound?

I don't yet know exactly what time I will be available to start since @noahyor  will have his final band camp performance that morning, and the time depends on which band he is selected for.  I will post here once I know more details.

**Comment by noahyor** [comment]
I would, however love to come to the Swarm swarm.

**Comment by byorgey** [comment]
@noahyor I assume you'll be coming home right after the final concert so you can participate in the Swarm swarm.

**Comment by noahyor** [comment]
Most likely.

**Comment by nitinprakash96** [comment]
I can join anytime from 7:30 PM to 12:30 AM (I usually stay up a little late).

**Comment by twitu** [comment]
I'm in IST (UTC + 530) and I can join on any of the three days :smile:

**Comment by byorgey** [comment]
OK, we will plan to start at [16:00 UTC on Saturday, June 15](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Swarm+swarm+III&iso=20240615T16&p1=1440&ah=6) (10am PDT / 11am CDT / 9:30pm IST).  As usual we will meet in [The Swarm Hive on Gather.town](https://app.gather.town/app/SpqG1ic5pNKM7YqS/The%20Swarm%20Hive).

Note that 16:00 UTC will be the "official" start time but the Swarm Hive is always open.  If anyone wants to hang out in there earlier (especially those in IST, since it sounds like there will be at least 2 of you), feel free!

**Comment by byorgey** [comment]
@ltouro would be glad to have you join!
