### ISSUE TITLE
Fast pathfinding for non-player robots

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#836]
In #835 the objective is to enclose non-player robots and prevent them from drowning in the ocean.

To check that, it is necessary to make sure that there is no path from the robot's location to the ocean, but doing that in Swarm language is slow if done every tick.

## Proposed solution

Add a function `findPath` that will allow robots to better navigate and objectives to check reachability fast.
```java
findPath
  :  (int * int)                      /* start */
  -> (unit + int)                     /* limit */
  -> ((int * int) + entity)           /* goal */
  -> cmd (unit + ((int * int) -> dir) /* (no) path found */
```
We could implement it in Haskell using the A* algorithm to be fast on the 2D Swarm map.

Internally, the positive result would be a map from location to direction. When asked about a location not on the path, throw an error.

This would also be useful in other challenges like the shortest path, or for example making sheep go towards food (if it is close).

## How to return directions

Until we have recursive types (#154) in Swarm I see two options how to return `(int * int) -> dir`:
1. hide the function (`cell @hash`) and internally use Haskell `Map Location Direction`
2. serialize it to Swarm language:
    ```Haskell
    if (l == (0,1)) {north} {if (l == (0,2) {north} {...}}
    ```

**Comment by byorgey** [comment]
Would this require `god` capability?  Or do you imagine this being available in-game through some suitably powerful artifact?

**Comment by xsebek** [comment]
Based on D&D Beyond, [Find the Path](https://www.dndbeyond.com/spells/find-the-path) should require:

> a set of divinatory tools--such as bones, ivory sticks, cards, teeth, or carved runes--worth 100 gold coins

I am open to other suggestions. 🧙‍♂️

**Comment by byorgey** [comment]
Some Haskell packages implementing A* search to look into:
* https://hackage.haskell.org/package/astar
* https://hackage.haskell.org/package/monad-dijkstra
* https://hackage.haskell.org/package/search-algorithms
