### ISSUE TITLE
Disable PR "Merge" button; only allow Mergify bot

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#843]
It has happened before that users have clicked the "Merge" button on Pull Requests, whereas the preferred workflow is to instead add the "merge me" label.  I don't know if it is possible to achieve, but maybe limiting permissions to the `main` branch to `"GitHub <noreply@github.com>"` would prevent this.

Related: #832

**Comment by byorgey** [comment]
I think I can restrict who has push access to a branch and then only allow the `Mergify` user.  We could do that if there is a consensus that's what we want to do.  I think the downsides would be e.g. sometimes no one is around to review your very small PR and this would mean you would no longer be able to just merge yourself. Also sometimes when we change the mergify configuration itself it refuses to merge it, but in that case I think anyone who is an administrator (currently me an @xsebek , I think?) can override the branch protection and still merge things with their administrator power.

I'm not sure this is a big deal, maybe we just need to do a better job communicating expectations/practices to new contributors.

**Comment by xsebek** [comment]
We shouldn’t change Mergify configuration that often, so admin review is not a problem. 😉

I noticed GitHub shows me a big red warning on PRs that do not yet have approval. 😆 

In general I am in favour of making the bad behaviour impossible. There are real benefits to using the merge label as even admins have learned. 😅

**Comment by byorgey** [comment]
I think this has been done now, closing.
