### ISSUE TITLE
Normalizing .yaml files

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#845]
I was looking into using `yq`[^1] to stuff content from a `.sw` script into the `program` field of a `.yaml` file.
This in fact works, with a bit of finagling[^2]:

    PROGRAM=$(cat data/scenarios/Challenges/Ranching/_gated-paddock/enclosure-checking.sw | sed -e 's/[[:blank:]]\+$//') yq -i '.objectives[0].condition = strenv(PROGRAM) | .objectives[].condition style="literal"' data/scenarios/Challenges/Ranching/gated-paddock.yaml

Then I was thinking that we may want to facilitate some kind of automatic modification, or perhaps auto-reformatting (ensuring normalization), of scenario files.  It is possible to do so in bulk:

    find data/scenarios -type f -name '*.yaml' -print0 | xargs -0 --max-args 1 yq --inplace

However, there are a couple of issues:
1. Indentation of lists gets deepened by one level (this is idempotent).  Both the Go and Python implementations of `yq` do this, unfortunately.  If we made a normalization pass across the whole repo to re-standardize on this indentation, it would be a non-issue going forward.  Diffs look like this:
    ```
       - in:
    -    - [1, hinge]
    -    - [1, fence]
    +      - [1, hinge]
    +      - [1, fence]
         out:
    -    - [1, gate]
    +      - [1, gate]
    ```
3. Maps that have a right edge that is not "flat" (i.e. the map makes use of *spaces* (` `) in the palette) get converted to double-quoted YAML style, messing up the formatting.

[^1]: The [Go implementation](https://mikefarah.gitbook.io/yq/), not the [Python implementation](https://pypi.org/project/yq/).  It is available via `snap` on Ubuntu:
        ```
        snap install yq
        ```
[^2]: There are two aspects in this command line invocation that ensure proper formatting of the program as an unquoted literal:
    1. There must be **no** trailing whitespace on any line of the input text (hence, using `sed`)
    2. The replacement text will adopt the pre-existing "style" of the input `.yaml` file for a given field.  So if for some reason (*this bit me, actually*) the field in the original `.yaml` file is double-quoted, then the program will get stuffed into double quotes, all on a single line, with escaped newlines (`\n`), **unless** `style="literal"'` is explicitly supplied to override the original style.

**Comment by xsebek** [comment]
That is actually better than I expected - I thought `yq` would expand our “tuples as lists”.

Spaces in maps can be troublesome and we can replace them by `.` or some other non intrusive characters.

So I am not against formatting but is there any benefit besides that “preprocessor inline run” command?

Normally I would pass the result of `yq` call as a temporary file (`<(yq …)`) where things like indentation changes don’t matter.

@kostmo is there some other use case you have in mind? 🙂

**Comment by kostmo** [comment]
> is there some other use case you have in mind?

Nothing concrete yet, but one use case would be if we need to apply some automated restructuring of all scenarios as the design of `swarm` evolves.  Perhaps #795 will require restructuring scenarios.  Or at least with the capability to restructure the scenario files, we can be less constrained in the new design (i.e. don't need to be backwards-compatible).

**Comment by byorgey** [comment]
If we do this, i.e. standardize on some normalized form, then I think going forward we would need to have something in our CI that requires it.  Maybe that goes without saying but I wanted to make sure it was said anyway. =)

The benefit of normalizing like this is just that future automated edits would incur minimal diffs?  Is that it or are there additional benefits?

**Comment by kostmo** [comment]
> future automated edits would incur minimal diffs?

That's exactly it.

Another use case for normalization is if there exist high-edit-frequency files for which you want to minimize merge conflicts.  But `swarm` is not there yet :)

**Comment by xsebek** [comment]
Having this in CI seems to me like more work than we save.

Unless there is some existing GitHub action that supports YAML formatting? (Restyled?)

**Comment by byorgey** [comment]
> Unless there is some existing GitHub action that supports YAML formatting? (Restyled?)

Apparently restyled supports a restyled called `prettier-yaml`, see https://docs.restyled.io/available-restylers/ .  Not sure what it does exactly.
