### ISSUE TITLE
Add reverse-i-search  to REPL

### ISSUE THREAD

**Issue by lsmor** [swarm-game/swarm#85]
**Summary**
It could be usefull to have reverse-i-search in the REPL as in regular unix shell. 

**Describe the solution you'd like**
Pressing `Crtl+r` should prompt the user with the word to find and it should look into repl history returning the first command containing that word

**Comment by lsmor** [comment]
@byorgey  I am trying to complete this, and it is quite of an achivement. I don't know if I'm missing something about the code.

So AFAIK, the repl is represented as just `Text`, whereas input and outputs are properly represented using a ADT. In order to give the repl a behaviour other than just typing comands we should create an ADT representing the "kind" of prompt you want to use. Example

```haskell
-- | The ADT representing REPL functionality.
--   Typing a command, search in history, multiline edition, etc ...
--   The Text field is the text prompted to the user
data REPLPrompt = PromptCmd Text | PromptSearch Text | PromptEdit Text

data UIState = UIState
  { ...
  , _uiReplPrompt :: REPLPrompt
  , _uiReplForm   :: Form REPLPrompt AppEvent Name
  }

```
The idea is that it you type something, the behaviour is defferent whether you are in a search prompt or in a comand prompt. With respec to visualization, the REPL would become kind of a `Form REPLPrompt AppEvent Name` and all functions dealing with `uiReplForm` lens, should adapt to the new type. 

I willing to make this work, but it seems like a big change and I don't know if there is a better way to do it. Let me know If you think of a different solution or you just prefer to keep the repl as it is

**Comment by byorgey** [comment]
Hi @lsmor , yes, it does seem tricky.  It's a shame we can't just reuse something like `haskeline` which already implements all of this, but that's not really possible because of the way the REPL is embedded inside a larger UI, so we have to implement all of these features ourselves. (Down the road it might be a nice idea to spin out some of the REPL stuff info an independent package, e.g. `brick-repl`, but that's quite a ways off at this point.)

I am not sure I understand 100% what the `REPLPrompt` type represents.  But it definitely makes sense that we will need to introduce a sum type somewhere to keep track of what mode the REPL is in.  I don't think there's any simpler way to do it.

**Comment by lsmor** [comment]
> Perhaps implementing `history-search-backward` might be easier to begin with, that is when the user press pgup, look in the history for a line starting with the current prompt.

Yes, actually something like that would be much easier. But I think, sonner or later we will need a sum type for the repl.

> I am not sure I understand 100% what the `REPLPrompt` type represents. But it definitely makes sense that we will need to introduce a sum type somewhere to keep track of what mode the REPL is in. I don't think there's any simpler way to do it.

`REPLPrompt` represent what should be prompted to the user and what is the expected behaviour of the repl. For example, in a regular unix console you have the following workflow:

- Pressing `Crtl + r` will prompt something like `(reverse-i-search):`
- Then you type what ever you want to find
- Then pressing `Enter` will return to normal prompt with the found result.
 
Notice that pressing `Enter` has different behaviour depending on the repl mode you are: in regular mode, it means "execute the command", in searching mode it means "return to normal with the found result plug in". The idea of `REPLPrompt` is to distinguish between them. Also, it can be usefull in the future if, let's say, you want to simulate a remote repl for a robot or something like that.

**Comment by byorgey** [comment]
"Next up/down with prefix" seems like it would be very easy to implement: for that we don't need a separate REPL mode, just change the behavior of the up/down keys so it depends on the current contents of the REPL?  Although it might be more difficult for users to discover; many users are probably going to expect that Ctrl+R will do reverse search.  Maybe we could change Ctrl+R so it prints out a message saying "to do reverse search, type a search prefix then use up/down".

**Comment by byorgey** [comment]
Just to add, I have been doing some classic mode playthroughs recently to test things out, and I have found myself missing this feature very much!

**Comment by lsmor** [comment]
Hi!, It's been a while since I haven't been around... I am catching up new updates on the code. I can reuse some parts of a partial implementation I got for this. Gopefully I can submit a PR soon.

**Comment by byorgey** [comment]
@lsmor welcome back! :smile:   Looking forward to the PR.
