### ISSUE TITLE
Newly initialized game tries to "catch up" after sitting in the menu for a while

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#853]
**Describe the bug**
After spending a while letting the game sit in the menu, when starting a new scenario the game runs really fast for a little bit, as if it thinks it should have been running while the menu was active and it is now trying to "catch up".

**To Reproduce**
I first noticed this when testing out #835 (it was very noticeable since the sheep ran around really fast and quickly drowned themselves) but it can be seen in any scenario where the base has a `clock` installed.
- Start the app
- Let it sit in the menu for a while (e.g. a few minutes)
- Now start the Classic game and look at the clock in the upper right.  It will run fast for a little while and then at some point start running normally.

**Expected behavior**
The game should run at a normal speed regardless of how long you have spent in the menu.

**Comment by xsebek** [comment]
This sounds like a regression. I vaguely remember that the controller used to set some variables to avoid this.

**Comment by byorgey** [comment]
I don't know if it's a regression or not.  This has definitely been tricky to get right with respect to pausing, dialogs, etc. but I don't specifically remember whether we have dealt with it right at the start of the scenario before.  We could in theory do a `git bisect` to figure out if there was a specific point where this was introduced, but that sounds very tedious due to the need to wait in the menu for a few minutes to test it.

**Comment by byorgey** [comment]
I think it's very easy to fix.  Patch incoming once I test it to be sure.
