### ISSUE TITLE
Don't switch to `logger` when there is a new message

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#854]
> Now that we have the Messages dialog which gets highlighted when there is a new message, maybe it's time to stop jumping to the logger every time there's a new message?  That's going to be irritating in more scenarios than just this one.

_Originally posted by @byorgey in https://github.com/swarm-game/swarm/pull/835#discussion_r1020774683_

Currently, whenever the inventory panel is focused and there is a new message in the `logger`, we jump to focus on the `logger` so that the player can read the message.  However, this can be irritating *e.g.* when the player is trying to read about some things in the inventory and there are many messages being generated for whatever reason.  Now that we have the Messages dialog, which gives an alternative mechanism for reading messages and for alerting players to the fact that there are new messages, perhaps we should get rid of this behavior.

**Comment by xsebek** [comment]
I find the mechanism useful, as it alerts me to new messages while I am in REPL. 

How about "if you have the inventory or description panel selected, then do not switch to logger"?

**Comment by byorgey** [comment]
Ah, that's a good idea.  So if you are actively looking at something then it will not switch away from it.
