### ISSUE TITLE
Counting inventory does not work for goal criteria

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#858]
Added test cases in #859 to demonstrate.

**Comment by kostmo** [comment]
As demonstrated in #926, the following does not work as `condition` code:

    x <- has "tree"; not x

However, for multi-objective scenarios, #795 provides a workaround by defining a `NOT` prerequisite.

**Comment by xsebek** [comment]
I wonder if this is a minimal example - i.e. if `not false` works as a condition.

**Comment by xsebek** [comment]
The problem is with the _kind of value_ returned from the hypothetical condition check:
![image](https://user-images.githubusercontent.com/44544735/210170210-f06e8230-6bca-4220-9060-dc14c425a705.png)
