### ISSUE TITLE
Warn of unused variables in LSP

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#863]
I had written code as follows:
```
def hasItemInDirection = \item. \direction.
  x <- scan direction;
  case x (\_. return false;) (\y.
    return $ y == "tree";
  );
  end;
```

I took a while to discover why my program was not working---the `item` parameter was unused.

**Describe the solution you'd like**
* Display unused variable warnings
* Differentiation between *warnings* and *errors* in the LSP

**Comment by byorgey** [comment]
Great idea. I assume we would also do something to allow deliberate suppression of the warning, e.g. any name that starts with an underscore is ignored.
