### ISSUE TITLE
Underline shows upon on mouse hover in world view in GNOME Terminal

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#868]
In fact there were two different regions within the world view where hovering the mouse cursor would trigger this.

See the 5th line from the bottom:
![Screenshot from 2022-11-15 21-33-00](https://user-images.githubusercontent.com/261693/202092483-ea309f05-2b6d-481a-a1ac-7bab64298140.png)

And the second line from the bottom:
![Screenshot from 2022-11-15 21-34-11](https://user-images.githubusercontent.com/261693/202092493-b975ae7b-3a12-48a7-a995-910cde4454e0.png)

The screenshot does not capture the mouse cursor, but upon hovering, the mouse cursor turned from an arrow to a pointing finger.  This makes me think that the terminal (GNOME Terminal) parsed the characters in that line (which happened to include letters (`T`), an `@` sign, and a dot (`.`) and decided it was an e-mail address.

It seems that there is [no way to disable this behavior](https://askubuntu.com/a/673461/7770) in GNOME Terminal itself.

I'm happy to close this as `Won't Fix`, but wanted to make note of it anyway.

**Comment by xsebek** [comment]
I remember seeing this at some point, but definitely not regularly. 🤔 

The discussion you linked suggests that updating Gnome should solve the issue and I am running the latest Fedora and Gnome, so it would make sense I am seeing it less.

@kostmo could you check by outputting  the same characters in shell that this is not Swarm specific? 🙂

**Comment by kostmo** [comment]
Yes, this does it:
```
echo "TTTTT@▒▒▒.▒"
```
![Screenshot from 2022-11-16 21-33-52](https://user-images.githubusercontent.com/261693/202364700-69296451-04ac-481d-9ef9-6f0876d3ab09.png)

**Comment by xsebek** [comment]
Great, then it’s not a Swarm issue and it should go away in newer Gnome releases. 🙂
