### ISSUE TITLE
Abilities unique to "heavy" robots

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#886]
Currently, the `heavy` attribute is strictly a limitation---it forces use of `tank treads`.

However, there is no incentive (or even any possible mechanism, currently) to build a `heavy` robot, so only the `base` is ever `heavy`.

Perhaps a "heavy" robot would support a larger inventory.  Or be the only robots capable of carrying certain entities.  Or would be invulnerable to certain types of damage.

Should "heavy" be a (irrevocable?) trait that can be granted programmatically to other robots?

**Comment by xsebek** [comment]
> Currently, the heavy attribute is strictly a limitation---it forces use of tank treads.

That is its purpose, but I would like to put it differently: _it separates robots that can use normal threads to move and those that can not in a way that is configurable in scenarios_.

For example, you could have a scenario with a stationary turret robot and simulate tower defense game.
It does not make sense for the turret to be compensated for being unable to move. _It's what the turret was meant to be._

---

That said, I am definitely not against scenarios where heavy treads also give some bonus capability. 😉

**Comment by xsebek** [comment]
> there is no incentive (or even any possible mechanism, currently) to build a heavy robot

Good point, a scenario with system factory that produces heavy robots could make sense.

**Comment by byorgey** [comment]
After thinking about this a bit more, I think I agree with @xsebek here.  Especially with #1548 we have been moving in the direction of having capabilities be more fine-grained.  So I think it makes sense for `heavy` to *only* mean "whether `tank treads` are needed to move or not".  Beyond that, we can of course make other capabilities that confer other abilities, and then (1) it is up to scenario designers to use capabilities in combinations that make sense, and (2) as a separate issue, we can consider special ways of generating robots with certain capabilities via `build`.

I think I'm going to close this, but feel free to re-open if there are new ideas or more to discuss.
