### ISSUE TITLE
Logging suggested in "Install" tutorial is not observable

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#896]
**Is your feature request related to a problem? Please describe.**
The "Install" tutorial suggests the player to

    build {log "Hello World!"}

First of all, since the goal condition check runs immediately, the player would have no opportunity to see the log output (see #758).
However, that is not the real problem; the user may choose to "Keep playing" from the "Congratulations" dialog for an opportunity to see the updated log.  But even then it does not appear!

What the user would need to do instead is:

    build {log "Hello World!"; upload base}

If they then select "Keep playing", they would be able to see "Hello World!" in the log.

**Describe the solution you'd like**

Remove the `log "Hello World!"` suggestion from this tutorial.

**Describe alternatives you've considered**

Add `upload base` to the suggested `build` command after `log` (and also add a `scanner` to the `base` inventory).

However, this would obligate more explanation for why `upload` is required, and that the user wouldn't see it unless they select "Keep playing".

**Comment by byorgey** [comment]
Good point.  Maybe it should just say `build {move}` or something?
