### ISSUE TITLE
More editing shortcuts in REPL

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#897]
Would be nice to have a few more keyboard shortcuts familiar to Bash users.  In particular, I find myself attempting CTRL+w ([`unix-word-rubout`](https://www.gnu.org/software/bash/manual/html_node/Commands-For-Killing.html#index-unix_002dword_002drubout-_0028C_002dw_0029)) a lot.  Also potentially [`backward-kill-word`](https://unix.stackexchange.com/a/119513/124811) (M-Backspace) would be useful.

Perhaps these could be provided in some kind of layerable event-handler helper function and potentially upstreamed to Brick (c.f. [Editor editor keybindings](https://hackage.haskell.org/package/brick-1.5/docs/Brick-Widgets-Edit.html#t:Editor), and also worth mentioning [vi list keybindings](https://hackage.haskell.org/package/brick-1.5/docs/Brick-Widgets-List.html#v:handleListEventVi)).

**Comment by byorgey** [comment]
I also find myself wanting backward-kill-word a lot.  For anyone looking at this issue in the future, this would probably involve adding some code around here:

https://github.com/swarm-game/swarm/blob/ff349d8a3ee7f92230e50390d77e9e1b22feff4f/src/swarm-tui/Swarm/TUI/Controller.hs#L1198
