### ISSUE TITLE
A toplevel notification system (for achievements, etc.)

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#916]
Should have either a status bar or **non-modal** popup/dialog overlays (c.f. [Toast](https://developer.android.com/guide/topics/ui/notifiers/toasts) on Android) to alert the user of certain events (e.g. attaining achievements (#797)).

This should not be the same as the "robot messages" window.

**Comment by xsebek** [comment]
As a note, one implementation that we discussed could be to add another layer to the entire game.

Currently, only the running game has two layers (dialogues and base layer) while the main menu only has one layer.

This way, achievements could popup even on the `About` page.

**Comment by byorgey** [comment]
Hmm, yes, adding another layer with non-modal popups could be a good, consistent way to add notifications across the entire game.  A few more thoughts from #1506:

- This would also work for notifications when new recipes or entities are unlocked.
- We'd have to think about what should happen when multiple notifications are triggered at once (e.g. an achievement + new recipes unlocked).  The simplest idea would probably be to just have a queue of notifications and display each for a certain amount of time.
- Now that we have pretty-printing for Markdown we could make use of that for notification messages.
- If we use pop-ups, I suppose putting them at or near the top of the window would probably be the least disruptive place.

**Comment by xsebek** [comment]
> If we use pop-ups, I suppose putting them at or near the top of the window would probably be the least disruptive place.

How about popup only for warning level greater or equal to user configured value? 🙂 (default error)

A UI at my work has it like that with buttons Clear and Hide.

> We'd have to think about what should happen when multiple notifications are triggered at once.

If the popup is a scrollable list, then the preview could just show the categories: `I 3  W 1  E 0` (or ℹ️ ⚠️ 🛑)

Alternatively I would be fine with a preview of the latest most serious notification, which would only be explicitly cleared by the player. Clearing notification could be as simple as right mouse click.

**Comment by byorgey** [comment]
> How about popup only for warning level greater or equal to user configured value? 🙂 (default error)

I was not thinking about popups in terms of errors at all, but rather for notifications of __good__ things like unlocking achievements and recipes.  After merging #1487, most errors and warnings can now be shown inline in the REPL.  Were there additional sorts of "out-of-band" errors that you could imagine most effectively being shown via popups?

Also, for notifications of achievements, recipes, etc. I personally would rather have them just pop up for a certain (configurable) amount of time and then automatically disappear, rather than having to explicitly click to close them.

**Comment by xsebek** [comment]
@byorgey I was thinking about system messages while you are playing the game. But maybe those could be filtered in message view.

I could imagine wanting to see some robot messages as a popup though. 🤔 I think we considered a dynamic system like that as an alternative to current objectives.
