### ISSUE TITLE
Add iron to allow more advanced recipes

### ISSUE THREAD

**Issue by abyo** [swarm-game/swarm#93]
Since copper is already implemented in the game, I'd suggest adding iron in order to allow more advanced recipes. 

When it comes to the world gen, I'd suggest an `F` for the symbol (after the chemical element `Fe`) and choose either an orange color (then change copper to blue, in order to stay as close as possible to real world) or blue to stay close to what most games use those days.

We could add iron veins close to the mountains (and/or make terrains like suggested in #18). That would mean that we could get iron/copper in the wild (like it is now for copper) then have those terrains/veins to farm more for later use.

Finally, this would give options for the potential `robot chassis` suggested in #35 and also add/change other recipe (like the `drill` for example). Here's a few recipe suggestions to start:

- 1 iron ore -> 2 iron plates (1:2 or 1:1)
- 2 iron plates -> 1 iron gear (that would mean to rename the current `Gear` to this or differentiate `Wooden Gear` and `Iron Gear`)
- 2 iron plates + 1 iron gear + 2 copper pipes -> 1 robot chassis
- 1 robot chassis + 4 iron plates + 8 copper wires -> 1 robot

Those are obviously open for discussion.

**Comment by byorgey** [comment]
I like the idea of differentiating `wooden gear` and `iron gear`.  I think the things that currently require `gear`s should not have to wait until after acquiring iron.  (In fact, if I'm not mistaken, currently a `drill` transitively requires some gears.)

**Comment by abyo** [comment]
Yes the `drill` requires a motor which needs 32 gears. It's just that making a box and a motor out of wood is weird in my head. It makes more sense for me to use iron (keeping in mind that you can still find those resources in the wild without having to use a drill in the first plate).

**Comment by byorgey** [comment]
Yeah, that's true.  I didn't want to make it too hard to make a drill, but maybe it makes sense that you have to scrounge up some iron manually in order to bootstrap yourself into being able to collect more.  I am also very open to changing the number of gears required etc.

**Comment by byorgey** [comment]
There are probably still some other things it could make sense to use wooden gears for, e.g. a clock.

**Comment by GnarLito** [comment]
an idea could also be to have a `wooden drill` and a `iron drill`, where the `wooden drill` (the lesser variant) being worse, by for example taking longer to drill or has a higher chance to break the vain / retrieves less from a vain.

This would be an easy way to increase the tech tree size, and gives an good starting point to get iron and copper.

**Comment by byorgey** [comment]
Ah, yeah, like how Minecraft has tools made of different materials.  That could work too.

**Comment by byorgey** [comment]
Making an iron drill 2x faster is nice, but by itself it doesn't seem like sufficient motivation to want to build one.  What if there are also certain things that can only be drilled with an iron drill (Kind of like pickaxes in Minecraft)?

**Comment by xsebek** [comment]
Well, I would like iron to only appear in veins and both veins can be surrounded by mountains, so copper drill would need to be able to drill all of them. :thinking: 

What if we made iron drill boon *quadratic* and added a recipe for base treads, that would take huge amount of iron? So much that you would need to automate the process and make it dramatically faster. :smiling_imp:
