### ISSUE TITLE
How to manage "vendored" boolexpr dependency?

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#934]
The [`boolexpr` package](https://hackage.haskell.org/package/boolexpr) needs [this PR](https://github.com/np/boolexpr/pull/2) to support modern GHC.  I was able to include the "boolexpr" package as a "[vendored dependency](https://stackoverflow.com/a/39643873/105137)" by copying in the code and [adding it as a local package in `stack.yaml`](https://github.com/swarm-game/swarm/blob/98b793e5289083a30def9faae2fda4d1bcad6e38/stack.yaml#L3).  This works with `stack build`.  However, the [CI build](https://github.com/swarm-game/swarm/actions/runs/3791622200/jobs/6447185772) doesn't seem to respect this local dependency.

---

**UPDATE:** The PR np/boolexpr#2 has been merged - thanks @np and @kostmo!

**Comment by xsebek** [comment]
We used to do this in cabal-extra (I think was the name) with other libraries.

The problem is that this will not work for release. The built binary will have the released version of the dependency.

**Comment by xsebek** [comment]
@kostmo I could not find your comment about whether you reached out to the `boolexpr` author via mail in #927.

I reached out to the author on the Keybase messaging platform and will update you with the results. :wink:
