### ISSUE TITLE
Indicate which scenario failed in error message

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#935]
One of the unit tests that I added had a syntax error in the `solution` field of the `.yaml` file.  Running `stack test` emitted the following:
```
swarm>       Testing/428-drowning-destroy:                                                                        FAIL (0.07s)
swarm>         test/integration/Main.hs:246:
swarm>         Failure in initGameStateForScenario: Failed to load scenarios: Aeson exception:
swarm>         Error in $.solution: Could not parse term: 1: Can't unify cmd unit and u0 -> u1
swarm>         Use -p '/Regression tests.Testing\/428-drowning-destroy/' to rerun this test only.
swarm>       Testing/475-wait-one:                                                                                FAIL (0.07s)
swarm>         test/integration/Main.hs:246:
swarm>         Failure in initGameStateForScenario: Failed to load scenarios: Aeson exception:
swarm>         Error in $.solution: Could not parse term: 1: Can't unify cmd unit and u0 -> u1
swarm>         Use -p '/Regression tests.Testing\/475-wait-one/' to rerun this test only.
swarm>       Testing/490-harvest:                                                                                 FAIL (0.07s)
swarm>         test/integration/Main.hs:246:
swarm>         Failure in initGameStateForScenario: Failed to load scenarios: Aeson exception:
swarm>         Error in $.solution: Could not parse term: 1: Can't unify cmd unit and u0 -> u1
swarm>         Use -p '/Regression tests.Testing\/490-harvest/' to rerun this test only.
```

Ideally, after the `Failed to load scenarios:` message, it would indicate which scenario actually failed.
I would think the injection would be done [right around here](https://github.com/swarm-game/swarm/blob/926cede91a66788e1e4c4ee20bfb0e31b74d7c0f/src/Swarm/Game/ScenarioInfo.hs#L350), but I'm not familiar with how to do so in this monad stack.

**Comment by xsebek** [comment]
Those are integration/end to end tests. Unit tests should by definition not all fail when new scenario file does not parse. 😄 

AFAIK when there is a wrong scenario the game itself will not start.

Ideally we should log the parsing failure in game and in tests either:
- only run parsing tests
- allow some scenarios to not load

I think the logs+allowing loading failure are a preferable solution. But if you just want to see the name of the unparsed tests, then skipping the run tests should work as well.

**Comment by byorgey** [comment]
Which scenario failed *is* mentioned if you scroll all the way to the end.  I agree the real issue here is that the entire app shouldn't crash just because one scenario fails to parse.

**Comment by xsebek** [comment]
I tested it now and it seems to no longer break other tests - @byorgey likely your refactoring helped. 👍
