### ISSUE TITLE
Entire project is recompiled when switching from "stack build" to "stack test"

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#936]
Are there any flags that can be passed to the `stack` invocation so that when alternating between `stack build` and `stack test`, it doesn't have to rebuild every module?

**Comment by byorgey** [comment]
Relevant: https://github.com/commercialhaskell/stack/issues/4977#issue-472333287

**Comment by xsebek** [comment]
Shame that the “fix” that adds this logic to build in stack configuration breaks tests. 😕 

@kostmo if this workaround works for you, could you please add it to DEVELOPING.md? 🙂 If I ever convert from Cabal these tips would be very useful. 😄
