### ISSUE TITLE
Crash after completing the first step of the tutorial

### ISSUE THREAD

**Issue by jolitti** [swarm-game/swarm#941]
After building from source, completing the "say Ready" tutorial step crashes the game with the error
`swarm: YamlException "could not open file for write: /home/rizoma/.local/share/swarm/saves/Tutorials_backstory.yaml"`

**To reproduce** 
Install from source with `stack` on Pop Os, launch and open the tutorial. Close the introduction message and type 'say "Ready!"'. After the congratulation message, the first two options will crash the game. Additionally, the menu will not reappear if you select the third option and press Ctrl-g.

**Expected behavior**
The tutorial should progress to the next step

**Additional context**
During the `stack` setup I had to stop two times to install two linkers with `apt`, I might still need some runtime dependencies that I don't know about

**Comment by xsebek** [comment]
Hi @jolitti, thanks for the bug report! :+1: 

This is probably a logic error on my part. The game tries to save your tutorial progress but can not do so.

Could you please include the output of `ls -la ~/.local/share/swarm/`?

**Comment by xsebek** [comment]
Looks like this bug may have been introduced in [097ff5a90571](https://github.com/swarm-game/swarm/commit/097ff5a90571414dd2f2e0cd87655e3deb067803#diff-fbc56104333d3b6cca86ef3181d654860d3675eafbd765bf00aba7d214650112L282-R283).

@kostmo I think you have deleted the logic that creates the `saves` directory during refactoring - now it only creates the parent `swarm` directory. :thinking:

**Comment by kostmo** [comment]
> @kostmo I think you have deleted the logic that creates the `saves` directory during refactoring - now it only creates the parent `swarm` directory.

Whoops, that is possible.  The `getSwarmDataPath` function has a call to `createDirectoryIfMissing` so I must have figured the call in in `getSwarmSavePath` was redundant.

**Comment by jolitti** [comment]
Take all the time you need to fix this, I'm just happy it wasn't a lazy error on my part

**Comment by xsebek** [comment]
@jolitti please give it a try now and if it's not fixed reopen the issue. :wink:

**Comment by jolitti** [comment]
In the meantime I've manually created the `saves` directory and didn't have any more issues after that. Thanks again for the support
