### ISSUE TITLE
requireinv tutorial times out sporadically in tests

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#947]
**Describe the bug**

Twice now the CI builds have failed on 1 out of 4 GHC version due to a timeout on `Tutorials/requireinv`.  [Here's the most recent](https://github.com/swarm-game/swarm/actions/runs/3819577649/jobs/6497250901):

```
Tutorials/requireinv:                                                                                FAIL (1.37s)
        test/integration/Main.hs:261:
        Timed out - this likely means that the solution did not work.
        Use -p '/Tutorial.Tutorials\/requireinv/' to rerun this test only.
```

**To Reproduce**
It is nondeterministic.  Will probably recur with enougth CI builds.

**Comment by byorgey** [comment]
Maybe it usually takes just under the time limit, but occasionally exceeds it?  The simplest thing to try would be just increasing the time limit a bit.

**Comment by kostmo** [comment]
Another data point [here](https://github.com/swarm-game/swarm/actions/runs/3841057656/jobs/6540833617):

      Tutorials/requireinv:       FAIL (1.43s)
