### ISSUE TITLE
Devices that Decouple Turn from Move capability

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#950]
Originally raised in [this comment](https://github.com/swarm-game/swarm/issues/205#issuecomment-1284895726).

Currently, `treads` provide both `CTurn` and `CMove`.  This could be rationalized within swarm-world logic via treads providing "skid steering".  We should create a new device, `rollers`, that offer `CMove` capability but not `CTurn`.

Without the "turn" capability (`CTurn`), robots will only be able to travel forwards along a straight line from the base.  This would facilitate interesting puzzle challenges.

To extend this thought further, we could add a new capability `CReverse` that enables only a single direction change: `turn back`.  This would facilitate challenges where longitudinal, but not lateral, movement is allowed.  This proposed capability is related to the `COrient`.

**Comment by byorgey** [comment]
Alternatively, what about adding a `reverse` command which moves backwards?  `treads` and `rollers` could both provide it.  That way we wouldn't have to go to the trouble of distinguishing directions.

**Comment by xsebek** [comment]
I vaguely remember we created an Issue for challenge DSL - in this case, the base could be given the `reverse` command implemented like:
```yaml
base:
  commands_or_something: |
    def reverse = doWithoutChecks { turn back; } end
```

**Comment by xsebek** [comment]
I am in favour of splitting `CTurn` from `CMove`, that seems like a logical distinction. :+1: 

Taking this further to `CReverse` feels wrong to me. For example, in Robot Karel's language, the basic task is to turn around using only `turn left`. If I wanted to create such a challenge in Swarm, taking the `CReverse` approach would lead me to create a `CLeft` capability.

Taking this much further I would prefer writing scenarios in scenario files using basic building blocks. Having to make changes in the Haskell codebase to express the scenario conditions ("you can not turn right",...) kind of limits it to Swarm maintainers.

**Comment by byorgey** [comment]
Also related: #864 .  If we had that one could easily e.g. make a scenario with a `rollers` device and disallow crafting `treads`.  Though I'm not against adding a globally available `rollers` device.

Also related: #1524 ; using the envisioned ability to attach code to entities, it would be possible to e.g. create a custom `reverser` device that runs the code `turn back`.

**Comment by byorgey** [comment]
Also also related: #1553.

**Comment by xsebek** [comment]
@kostmo, can this be closed? Scenarios can now specify device with separate capabilities for each command.

**Comment by kostmo** [comment]
> @kostmo, can this be closed? Scenarios can now specify device with separate capabilities for each command.

Sure.  I think this issue may have been less about the technical means of assigning capabilities to devices, but rather which capabilities should be partitioned across which devices.  But anyway we have more specific issues like #1029 for that, so let's close this issue at least on the grounds that it's not well-focused.
