### ISSUE TITLE
List type

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#97]
We should add a type of singly-linked, recursive lists to the language (like Haskell lists, but strict and hence finite).  Presumably the capability to use lists should not be obtainable too early on.  It is easy to imagine some commands we could add that might return lists, such as a command to get the contents of a robot's inventory.

**Comment by xsebek** [comment]
Alternatively, we could add a `rec` (like [`Fix`](https://hackage.haskell.org/package/data-fix-0.3.2/docs/Data-Fix.html)) operator and get `list a` from `listf a b = (() + a * b)` as `rec listf` from #46.

Not sure which reserved functions would be necessary to make this type usable, but it would be a fun way to make these advanced data structures. :smile: 

Obviously whatever advanced device gives this ability should mention how to construct `list` and that other data types are possible too. :thinking: 

Related:
- would require #153 to get the `rec` applied to correct types
- #46 
- #7 (so less savvy players could `load data.list.sw` which they would find on Wiki)

**Comment by byorgey** [comment]
> Alternatively, we could add a `rec` (like [`Fix`](https://hackage.haskell.org/package/data-fix-0.3.2/docs/Data-Fix.html)) operator

Nice idea!  Could you create a separate issue for it?

> Not sure which reserved functions would be necessary to make this type usable

All you really need is `roll : f (rec f) -> rec f` and `unroll : rec f -> f (rec f)`.

**Comment by byorgey** [comment]
Also, I really like the idea of providing the pieces out of which to build lists but not provide built-in lists themselves.  It definitely fits with the aesthetic of the game.

**Comment by xsebek** [comment]
I made a separate feature request for `rec` :slightly_smiling_face: 
- #154

**Comment by byorgey** [comment]
I think I will close this in favor of #154 .
