### ISSUE TITLE
Unfold function application in LSP Hover

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#985]
I would like to see all the function parameters in hover in this format:

```markdown
<!--- f a b c -->
Function application of:
* `f: Bool -> Bool -> Bool -> Bool`
with parameters:
* `a: Bool`
* `b: Bool`
* `c: Bool`
```

The required function is:
```Haskell
unfoldApps :: Term -> NonEmpty Term
unfoldApps trm = NonEmpty.reverse . flip NonEmpty.unfoldr trm $ \case
  SApp (Syntax _ t1) (Syntax _ t2) -> (t2, Just t1)
  t -> (t, Nothing)
```

Not sure if it already exists somewhere in the codebase.

---

Honestly, I am already working on this, but I am making an Issue for transparency. :wink:

**Comment by kostmo** [comment]
> but I am making an Issue for transparency

Yes, that's good practice, so that nobody starts duplicating your work.

**Comment by xsebek** [comment]
That somebody would have had 30 minutes to do so. :smile: 

The other plus of this approach is that general design issues can be discussed here and not drowned in the PR discussion.
